// Code generated by go-swagger; DO NOT EDIT.

package client

import (
	"maps"

	"github.com/ThisIsHyum/osago/client/admin"
	"github.com/ThisIsHyum/osago/client/campuses"
	"github.com/ThisIsHyum/osago/client/colleges"
	"github.com/ThisIsHyum/osago/client/groups"
	"github.com/ThisIsHyum/osago/client/parser"
	"github.com/ThisIsHyum/osago/client/schedules"
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// Default open schedule API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host found in Meta (info) section of spec file.
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath found in Meta (info) section of spec file.
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file.
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new open schedule API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *OpenScheduleAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new open schedule API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *OpenScheduleAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client.
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	maps.Copy(transport.Producers, cfg.Producers)
	maps.Copy(transport.Consumers, cfg.Consumers)

	return New(transport, formats)
}

// New creates a new open schedule API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) *OpenScheduleAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(OpenScheduleAPI)
	cli.Transport = transport
	cli.Admin = admin.New(transport, formats)
	cli.Campuses = campuses.New(transport, formats)
	cli.Colleges = colleges.New(transport, formats)
	cli.Groups = groups.New(transport, formats)
	cli.Parser = parser.New(transport, formats)
	cli.Schedules = schedules.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host      string
	BasePath  string
	Schemes   []string
	Producers map[string]runtime.Producer
	Consumers map[string]runtime.Consumer
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// WithProducers overrides the default producers registered by [httptransport.Runtime].
func (cfg *TransportConfig) WithProducers(producers map[string]runtime.Producer) *TransportConfig {
	cfg.Producers = producers
	return cfg
}

// WithConsumers overrides the default consumers registered by [httptransport.Runtime].
func (cfg *TransportConfig) WithConsumers(consumers map[string]runtime.Consumer) *TransportConfig {
	cfg.Consumers = consumers
	return cfg
}

// OpenScheduleAPI is a client for open schedule API.
type OpenScheduleAPI struct {
	Admin admin.ClientService

	Campuses campuses.ClientService

	Colleges colleges.ClientService

	Groups groups.ClientService

	Parser parser.ClientService

	Schedules schedules.ClientService

	Transport runtime.ContextualTransport
}

// SetTransport changes the transport on the client and all its subresources.
func (c *OpenScheduleAPI) SetTransport(transport runtime.ContextualTransport) {
	c.Transport = transport
	c.Admin.SetTransport(transport)
	c.Campuses.SetTransport(transport)
	c.Colleges.SetTransport(transport)
	c.Groups.SetTransport(transport)
	c.Parser.SetTransport(transport)
	c.Schedules.SetTransport(transport)
}
