// Code generated by go-swagger; DO NOT EDIT.

package schedules

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetCollegesCollegeIDSchedulesReader is a Reader for the GetCollegesCollegeIDSchedules structure.
type GetCollegesCollegeIDSchedulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCollegesCollegeIDSchedulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCollegesCollegeIDSchedulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCollegesCollegeIDSchedulesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCollegesCollegeIDSchedulesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCollegesCollegeIDSchedulesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /colleges/{collegeId}/schedules] GetCollegesCollegeIDSchedules", response, response.Code())
	}
}

// NewGetCollegesCollegeIDSchedulesOK creates a GetCollegesCollegeIDSchedulesOK with default headers values
func NewGetCollegesCollegeIDSchedulesOK() *GetCollegesCollegeIDSchedulesOK {
	return &GetCollegesCollegeIDSchedulesOK{}
}

// GetCollegesCollegeIDSchedulesOK describes a response with status code 200, with default header values.
//
// OK
type GetCollegesCollegeIDSchedulesOK struct {
	Payload []*models.DtoScheduleResponse
}

// IsSuccess returns true when this get colleges college Id schedules o k response has a 2xx status code
func (o *GetCollegesCollegeIDSchedulesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get colleges college Id schedules o k response has a 3xx status code
func (o *GetCollegesCollegeIDSchedulesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges college Id schedules o k response has a 4xx status code
func (o *GetCollegesCollegeIDSchedulesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get colleges college Id schedules o k response has a 5xx status code
func (o *GetCollegesCollegeIDSchedulesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get colleges college Id schedules o k response a status code equal to that given
func (o *GetCollegesCollegeIDSchedulesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get colleges college Id schedules o k response
func (o *GetCollegesCollegeIDSchedulesOK) Code() int {
	return 200
}

func (o *GetCollegesCollegeIDSchedulesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/schedules][%d] getCollegesCollegeIdSchedulesOK %s", 200, payload)
}

func (o *GetCollegesCollegeIDSchedulesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/schedules][%d] getCollegesCollegeIdSchedulesOK %s", 200, payload)
}

func (o *GetCollegesCollegeIDSchedulesOK) GetPayload() []*models.DtoScheduleResponse {
	return o.Payload
}

func (o *GetCollegesCollegeIDSchedulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCollegesCollegeIDSchedulesBadRequest creates a GetCollegesCollegeIDSchedulesBadRequest with default headers values
func NewGetCollegesCollegeIDSchedulesBadRequest() *GetCollegesCollegeIDSchedulesBadRequest {
	return &GetCollegesCollegeIDSchedulesBadRequest{}
}

// GetCollegesCollegeIDSchedulesBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type GetCollegesCollegeIDSchedulesBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get colleges college Id schedules bad request response has a 2xx status code
func (o *GetCollegesCollegeIDSchedulesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get colleges college Id schedules bad request response has a 3xx status code
func (o *GetCollegesCollegeIDSchedulesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges college Id schedules bad request response has a 4xx status code
func (o *GetCollegesCollegeIDSchedulesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get colleges college Id schedules bad request response has a 5xx status code
func (o *GetCollegesCollegeIDSchedulesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get colleges college Id schedules bad request response a status code equal to that given
func (o *GetCollegesCollegeIDSchedulesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get colleges college Id schedules bad request response
func (o *GetCollegesCollegeIDSchedulesBadRequest) Code() int {
	return 400
}

func (o *GetCollegesCollegeIDSchedulesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/schedules][%d] getCollegesCollegeIdSchedulesBadRequest %s", 400, payload)
}

func (o *GetCollegesCollegeIDSchedulesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/schedules][%d] getCollegesCollegeIdSchedulesBadRequest %s", 400, payload)
}

func (o *GetCollegesCollegeIDSchedulesBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCollegesCollegeIDSchedulesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCollegesCollegeIDSchedulesNotFound creates a GetCollegesCollegeIDSchedulesNotFound with default headers values
func NewGetCollegesCollegeIDSchedulesNotFound() *GetCollegesCollegeIDSchedulesNotFound {
	return &GetCollegesCollegeIDSchedulesNotFound{}
}

// GetCollegesCollegeIDSchedulesNotFound describes a response with status code 404, with default header values.
//
// Not Found
type GetCollegesCollegeIDSchedulesNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get colleges college Id schedules not found response has a 2xx status code
func (o *GetCollegesCollegeIDSchedulesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get colleges college Id schedules not found response has a 3xx status code
func (o *GetCollegesCollegeIDSchedulesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges college Id schedules not found response has a 4xx status code
func (o *GetCollegesCollegeIDSchedulesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get colleges college Id schedules not found response has a 5xx status code
func (o *GetCollegesCollegeIDSchedulesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get colleges college Id schedules not found response a status code equal to that given
func (o *GetCollegesCollegeIDSchedulesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get colleges college Id schedules not found response
func (o *GetCollegesCollegeIDSchedulesNotFound) Code() int {
	return 404
}

func (o *GetCollegesCollegeIDSchedulesNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/schedules][%d] getCollegesCollegeIdSchedulesNotFound %s", 404, payload)
}

func (o *GetCollegesCollegeIDSchedulesNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/schedules][%d] getCollegesCollegeIdSchedulesNotFound %s", 404, payload)
}

func (o *GetCollegesCollegeIDSchedulesNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCollegesCollegeIDSchedulesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCollegesCollegeIDSchedulesInternalServerError creates a GetCollegesCollegeIDSchedulesInternalServerError with default headers values
func NewGetCollegesCollegeIDSchedulesInternalServerError() *GetCollegesCollegeIDSchedulesInternalServerError {
	return &GetCollegesCollegeIDSchedulesInternalServerError{}
}

// GetCollegesCollegeIDSchedulesInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type GetCollegesCollegeIDSchedulesInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get colleges college Id schedules internal server error response has a 2xx status code
func (o *GetCollegesCollegeIDSchedulesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get colleges college Id schedules internal server error response has a 3xx status code
func (o *GetCollegesCollegeIDSchedulesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges college Id schedules internal server error response has a 4xx status code
func (o *GetCollegesCollegeIDSchedulesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get colleges college Id schedules internal server error response has a 5xx status code
func (o *GetCollegesCollegeIDSchedulesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get colleges college Id schedules internal server error response a status code equal to that given
func (o *GetCollegesCollegeIDSchedulesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get colleges college Id schedules internal server error response
func (o *GetCollegesCollegeIDSchedulesInternalServerError) Code() int {
	return 500
}

func (o *GetCollegesCollegeIDSchedulesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/schedules][%d] getCollegesCollegeIdSchedulesInternalServerError %s", 500, payload)
}

func (o *GetCollegesCollegeIDSchedulesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/schedules][%d] getCollegesCollegeIdSchedulesInternalServerError %s", 500, payload)
}

func (o *GetCollegesCollegeIDSchedulesInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCollegesCollegeIDSchedulesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
