// Code generated by go-swagger; DO NOT EDIT.

package schedules

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetGroupsGroupIDSchedulesParams creates a new GetGroupsGroupIDSchedulesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGroupsGroupIDSchedulesParams() *GetGroupsGroupIDSchedulesParams {
	return NewGetGroupsGroupIDSchedulesParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetGroupsGroupIDSchedulesParamsWithTimeout creates a new GetGroupsGroupIDSchedulesParams object
// with the ability to set a timeout on a request.
func NewGetGroupsGroupIDSchedulesParamsWithTimeout(timeout time.Duration) *GetGroupsGroupIDSchedulesParams {
	return &GetGroupsGroupIDSchedulesParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetGroupsGroupIDSchedulesParamsWithContext creates a new GetGroupsGroupIDSchedulesParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetGroupsGroupIDSchedulesParams].
func NewGetGroupsGroupIDSchedulesParamsWithContext(ctx context.Context) *GetGroupsGroupIDSchedulesParams {
	return &GetGroupsGroupIDSchedulesParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetGroupsGroupIDSchedulesParamsWithHTTPClient creates a new GetGroupsGroupIDSchedulesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGroupsGroupIDSchedulesParamsWithHTTPClient(client *http.Client) *GetGroupsGroupIDSchedulesParams {
	return &GetGroupsGroupIDSchedulesParams{
		HTTPClient: client,
	}
}

/*
GetGroupsGroupIDSchedulesParams contains all the parameters to send to the API endpoint

	for the get groups group ID schedules operation.

	Typically these are written to a http.Request.
*/
type GetGroupsGroupIDSchedulesParams struct {

	// Cabinet.
	//
	// like cabinet of lessons
	Cabinet *string

	// Date.
	//
	// Specific date (yyyy-mm-dd)
	Date *string

	// Day.
	//
	// Relative day
	Day *string

	// GroupID.
	//
	// Group ID
	GroupID int64

	// Teacher.
	//
	// like teacher of lessons
	Teacher *string

	// Title.
	//
	// like title of lessons
	Title *string

	// Week.
	//
	// Week of schedules
	Week *string

	// Weekday.
	//
	// Weekday of schedules
	Weekday *string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get groups group ID schedules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupsGroupIDSchedulesParams) WithDefaults() *GetGroupsGroupIDSchedulesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get groups group ID schedules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupsGroupIDSchedulesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) WithTimeout(timeout time.Duration) *GetGroupsGroupIDSchedulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get groups group ID schedules params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetGroupsGroupIDSchedulesParams].
func (o *GetGroupsGroupIDSchedulesParams) WithContext(ctx context.Context) *GetGroupsGroupIDSchedulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get groups group ID schedules params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetGroupsGroupIDSchedulesParams].
func (o *GetGroupsGroupIDSchedulesParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) WithHTTPClient(client *http.Client) *GetGroupsGroupIDSchedulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCabinet adds the cabinet to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) WithCabinet(cabinet *string) *GetGroupsGroupIDSchedulesParams {
	o.SetCabinet(cabinet)
	return o
}

// SetCabinet adds the cabinet to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) SetCabinet(cabinet *string) {
	o.Cabinet = cabinet
}

// WithDate adds the date to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) WithDate(date *string) *GetGroupsGroupIDSchedulesParams {
	o.SetDate(date)
	return o
}

// SetDate adds the date to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) SetDate(date *string) {
	o.Date = date
}

// WithDay adds the day to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) WithDay(day *string) *GetGroupsGroupIDSchedulesParams {
	o.SetDay(day)
	return o
}

// SetDay adds the day to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) SetDay(day *string) {
	o.Day = day
}

// WithGroupID adds the groupID to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) WithGroupID(groupID int64) *GetGroupsGroupIDSchedulesParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) SetGroupID(groupID int64) {
	o.GroupID = groupID
}

// WithTeacher adds the teacher to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) WithTeacher(teacher *string) *GetGroupsGroupIDSchedulesParams {
	o.SetTeacher(teacher)
	return o
}

// SetTeacher adds the teacher to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) SetTeacher(teacher *string) {
	o.Teacher = teacher
}

// WithTitle adds the title to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) WithTitle(title *string) *GetGroupsGroupIDSchedulesParams {
	o.SetTitle(title)
	return o
}

// SetTitle adds the title to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) SetTitle(title *string) {
	o.Title = title
}

// WithWeek adds the week to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) WithWeek(week *string) *GetGroupsGroupIDSchedulesParams {
	o.SetWeek(week)
	return o
}

// SetWeek adds the week to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) SetWeek(week *string) {
	o.Week = week
}

// WithWeekday adds the weekday to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) WithWeekday(weekday *string) *GetGroupsGroupIDSchedulesParams {
	o.SetWeekday(weekday)
	return o
}

// SetWeekday adds the weekday to the get groups group ID schedules params.
func (o *GetGroupsGroupIDSchedulesParams) SetWeekday(weekday *string) {
	o.Weekday = weekday
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetGroupsGroupIDSchedulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cabinet != nil {

		// query param cabinet
		var qrCabinet string

		if o.Cabinet != nil {
			qrCabinet = *o.Cabinet
		}
		qCabinet := qrCabinet
		if qCabinet != "" {

			if err := r.SetQueryParam("cabinet", qCabinet); err != nil {
				return err
			}
		}
	}

	if o.Date != nil {

		// query param date
		var qrDate string

		if o.Date != nil {
			qrDate = *o.Date
		}
		qDate := qrDate
		if qDate != "" {

			if err := r.SetQueryParam("date", qDate); err != nil {
				return err
			}
		}
	}

	if o.Day != nil {

		// query param day
		var qrDay string

		if o.Day != nil {
			qrDay = *o.Day
		}
		qDay := qrDay
		if qDay != "" {

			if err := r.SetQueryParam("day", qDay); err != nil {
				return err
			}
		}
	}

	// path param groupId
	if err := r.SetPathParam("groupId", conv.FormatInteger(o.GroupID)); err != nil {
		return err
	}

	if o.Teacher != nil {

		// query param teacher
		var qrTeacher string

		if o.Teacher != nil {
			qrTeacher = *o.Teacher
		}
		qTeacher := qrTeacher
		if qTeacher != "" {

			if err := r.SetQueryParam("teacher", qTeacher); err != nil {
				return err
			}
		}
	}

	if o.Title != nil {

		// query param title
		var qrTitle string

		if o.Title != nil {
			qrTitle = *o.Title
		}
		qTitle := qrTitle
		if qTitle != "" {

			if err := r.SetQueryParam("title", qTitle); err != nil {
				return err
			}
		}
	}

	if o.Week != nil {

		// query param week
		var qrWeek string

		if o.Week != nil {
			qrWeek = *o.Week
		}
		qWeek := qrWeek
		if qWeek != "" {

			if err := r.SetQueryParam("week", qWeek); err != nil {
				return err
			}
		}
	}

	if o.Weekday != nil {

		// query param weekday
		var qrWeekday string

		if o.Weekday != nil {
			qrWeekday = *o.Weekday
		}
		qWeekday := qrWeekday
		if qWeekday != "" {

			if err := r.SetQueryParam("weekday", qWeekday); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
