// Code generated by go-swagger; DO NOT EDIT.

package schedules

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetGroupsGroupIDSchedulesReader is a Reader for the GetGroupsGroupIDSchedules structure.
type GetGroupsGroupIDSchedulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGroupsGroupIDSchedulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetGroupsGroupIDSchedulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetGroupsGroupIDSchedulesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetGroupsGroupIDSchedulesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewGetGroupsGroupIDSchedulesConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetGroupsGroupIDSchedulesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /groups/{groupId}/schedules] GetGroupsGroupIDSchedules", response, response.Code())
	}
}

// NewGetGroupsGroupIDSchedulesOK creates a GetGroupsGroupIDSchedulesOK with default headers values
func NewGetGroupsGroupIDSchedulesOK() *GetGroupsGroupIDSchedulesOK {
	return &GetGroupsGroupIDSchedulesOK{}
}

// GetGroupsGroupIDSchedulesOK describes a response with status code 200, with default header values.
//
// OK
type GetGroupsGroupIDSchedulesOK struct {
	Payload []*models.DtoScheduleResponse
}

// IsSuccess returns true when this get groups group Id schedules o k response has a 2xx status code
func (o *GetGroupsGroupIDSchedulesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get groups group Id schedules o k response has a 3xx status code
func (o *GetGroupsGroupIDSchedulesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get groups group Id schedules o k response has a 4xx status code
func (o *GetGroupsGroupIDSchedulesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get groups group Id schedules o k response has a 5xx status code
func (o *GetGroupsGroupIDSchedulesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get groups group Id schedules o k response a status code equal to that given
func (o *GetGroupsGroupIDSchedulesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get groups group Id schedules o k response
func (o *GetGroupsGroupIDSchedulesOK) Code() int {
	return 200
}

func (o *GetGroupsGroupIDSchedulesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{groupId}/schedules][%d] getGroupsGroupIdSchedulesOK %s", 200, payload)
}

func (o *GetGroupsGroupIDSchedulesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{groupId}/schedules][%d] getGroupsGroupIdSchedulesOK %s", 200, payload)
}

func (o *GetGroupsGroupIDSchedulesOK) GetPayload() []*models.DtoScheduleResponse {
	return o.Payload
}

func (o *GetGroupsGroupIDSchedulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetGroupsGroupIDSchedulesBadRequest creates a GetGroupsGroupIDSchedulesBadRequest with default headers values
func NewGetGroupsGroupIDSchedulesBadRequest() *GetGroupsGroupIDSchedulesBadRequest {
	return &GetGroupsGroupIDSchedulesBadRequest{}
}

// GetGroupsGroupIDSchedulesBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type GetGroupsGroupIDSchedulesBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get groups group Id schedules bad request response has a 2xx status code
func (o *GetGroupsGroupIDSchedulesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get groups group Id schedules bad request response has a 3xx status code
func (o *GetGroupsGroupIDSchedulesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get groups group Id schedules bad request response has a 4xx status code
func (o *GetGroupsGroupIDSchedulesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get groups group Id schedules bad request response has a 5xx status code
func (o *GetGroupsGroupIDSchedulesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get groups group Id schedules bad request response a status code equal to that given
func (o *GetGroupsGroupIDSchedulesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get groups group Id schedules bad request response
func (o *GetGroupsGroupIDSchedulesBadRequest) Code() int {
	return 400
}

func (o *GetGroupsGroupIDSchedulesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{groupId}/schedules][%d] getGroupsGroupIdSchedulesBadRequest %s", 400, payload)
}

func (o *GetGroupsGroupIDSchedulesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{groupId}/schedules][%d] getGroupsGroupIdSchedulesBadRequest %s", 400, payload)
}

func (o *GetGroupsGroupIDSchedulesBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetGroupsGroupIDSchedulesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetGroupsGroupIDSchedulesNotFound creates a GetGroupsGroupIDSchedulesNotFound with default headers values
func NewGetGroupsGroupIDSchedulesNotFound() *GetGroupsGroupIDSchedulesNotFound {
	return &GetGroupsGroupIDSchedulesNotFound{}
}

// GetGroupsGroupIDSchedulesNotFound describes a response with status code 404, with default header values.
//
// Not Found
type GetGroupsGroupIDSchedulesNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get groups group Id schedules not found response has a 2xx status code
func (o *GetGroupsGroupIDSchedulesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get groups group Id schedules not found response has a 3xx status code
func (o *GetGroupsGroupIDSchedulesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get groups group Id schedules not found response has a 4xx status code
func (o *GetGroupsGroupIDSchedulesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get groups group Id schedules not found response has a 5xx status code
func (o *GetGroupsGroupIDSchedulesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get groups group Id schedules not found response a status code equal to that given
func (o *GetGroupsGroupIDSchedulesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get groups group Id schedules not found response
func (o *GetGroupsGroupIDSchedulesNotFound) Code() int {
	return 404
}

func (o *GetGroupsGroupIDSchedulesNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{groupId}/schedules][%d] getGroupsGroupIdSchedulesNotFound %s", 404, payload)
}

func (o *GetGroupsGroupIDSchedulesNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{groupId}/schedules][%d] getGroupsGroupIdSchedulesNotFound %s", 404, payload)
}

func (o *GetGroupsGroupIDSchedulesNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetGroupsGroupIDSchedulesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetGroupsGroupIDSchedulesConflict creates a GetGroupsGroupIDSchedulesConflict with default headers values
func NewGetGroupsGroupIDSchedulesConflict() *GetGroupsGroupIDSchedulesConflict {
	return &GetGroupsGroupIDSchedulesConflict{}
}

// GetGroupsGroupIDSchedulesConflict describes a response with status code 409, with default header values.
//
// Conflict
type GetGroupsGroupIDSchedulesConflict struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get groups group Id schedules conflict response has a 2xx status code
func (o *GetGroupsGroupIDSchedulesConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get groups group Id schedules conflict response has a 3xx status code
func (o *GetGroupsGroupIDSchedulesConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get groups group Id schedules conflict response has a 4xx status code
func (o *GetGroupsGroupIDSchedulesConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this get groups group Id schedules conflict response has a 5xx status code
func (o *GetGroupsGroupIDSchedulesConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this get groups group Id schedules conflict response a status code equal to that given
func (o *GetGroupsGroupIDSchedulesConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the get groups group Id schedules conflict response
func (o *GetGroupsGroupIDSchedulesConflict) Code() int {
	return 409
}

func (o *GetGroupsGroupIDSchedulesConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{groupId}/schedules][%d] getGroupsGroupIdSchedulesConflict %s", 409, payload)
}

func (o *GetGroupsGroupIDSchedulesConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{groupId}/schedules][%d] getGroupsGroupIdSchedulesConflict %s", 409, payload)
}

func (o *GetGroupsGroupIDSchedulesConflict) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetGroupsGroupIDSchedulesConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetGroupsGroupIDSchedulesInternalServerError creates a GetGroupsGroupIDSchedulesInternalServerError with default headers values
func NewGetGroupsGroupIDSchedulesInternalServerError() *GetGroupsGroupIDSchedulesInternalServerError {
	return &GetGroupsGroupIDSchedulesInternalServerError{}
}

// GetGroupsGroupIDSchedulesInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type GetGroupsGroupIDSchedulesInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get groups group Id schedules internal server error response has a 2xx status code
func (o *GetGroupsGroupIDSchedulesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get groups group Id schedules internal server error response has a 3xx status code
func (o *GetGroupsGroupIDSchedulesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get groups group Id schedules internal server error response has a 4xx status code
func (o *GetGroupsGroupIDSchedulesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get groups group Id schedules internal server error response has a 5xx status code
func (o *GetGroupsGroupIDSchedulesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get groups group Id schedules internal server error response a status code equal to that given
func (o *GetGroupsGroupIDSchedulesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get groups group Id schedules internal server error response
func (o *GetGroupsGroupIDSchedulesInternalServerError) Code() int {
	return 500
}

func (o *GetGroupsGroupIDSchedulesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{groupId}/schedules][%d] getGroupsGroupIdSchedulesInternalServerError %s", 500, payload)
}

func (o *GetGroupsGroupIDSchedulesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{groupId}/schedules][%d] getGroupsGroupIdSchedulesInternalServerError %s", 500, payload)
}

func (o *GetGroupsGroupIDSchedulesInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetGroupsGroupIDSchedulesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
