// Code generated by go-swagger; DO NOT EDIT.

package schedules

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetCampusesCampusIDSchedulesParams creates a new GetCampusesCampusIDSchedulesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCampusesCampusIDSchedulesParams() *GetCampusesCampusIDSchedulesParams {
	return NewGetCampusesCampusIDSchedulesParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetCampusesCampusIDSchedulesParamsWithTimeout creates a new GetCampusesCampusIDSchedulesParams object
// with the ability to set a timeout on a request.
func NewGetCampusesCampusIDSchedulesParamsWithTimeout(timeout time.Duration) *GetCampusesCampusIDSchedulesParams {
	return &GetCampusesCampusIDSchedulesParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetCampusesCampusIDSchedulesParamsWithContext creates a new GetCampusesCampusIDSchedulesParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCampusesCampusIDSchedulesParams].
func NewGetCampusesCampusIDSchedulesParamsWithContext(ctx context.Context) *GetCampusesCampusIDSchedulesParams {
	return &GetCampusesCampusIDSchedulesParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetCampusesCampusIDSchedulesParamsWithHTTPClient creates a new GetCampusesCampusIDSchedulesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCampusesCampusIDSchedulesParamsWithHTTPClient(client *http.Client) *GetCampusesCampusIDSchedulesParams {
	return &GetCampusesCampusIDSchedulesParams{
		HTTPClient: client,
	}
}

/*
GetCampusesCampusIDSchedulesParams contains all the parameters to send to the API endpoint

	for the get campuses campus ID schedules operation.

	Typically these are written to a http.Request.
*/
type GetCampusesCampusIDSchedulesParams struct {

	// Cabinet.
	//
	// Like cabinet of lessons
	Cabinet *string

	// CampusID.
	//
	// Campus ID
	CampusID int64

	// Date.
	//
	// Specific date (yyyy-mm-dd)
	Date *string

	// Day.
	//
	// Relative day
	Day *string

	// Teacher.
	//
	// Like teacher of lessons
	Teacher *string

	// Title.
	//
	// Like title of lessons
	Title *string

	// Week.
	//
	// Week of schedules
	Week *string

	// Weekday.
	//
	// Weekday of schedules
	Weekday *string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get campuses campus ID schedules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCampusesCampusIDSchedulesParams) WithDefaults() *GetCampusesCampusIDSchedulesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get campuses campus ID schedules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCampusesCampusIDSchedulesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) WithTimeout(timeout time.Duration) *GetCampusesCampusIDSchedulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get campuses campus ID schedules params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCampusesCampusIDSchedulesParams].
func (o *GetCampusesCampusIDSchedulesParams) WithContext(ctx context.Context) *GetCampusesCampusIDSchedulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get campuses campus ID schedules params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCampusesCampusIDSchedulesParams].
func (o *GetCampusesCampusIDSchedulesParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) WithHTTPClient(client *http.Client) *GetCampusesCampusIDSchedulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCabinet adds the cabinet to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) WithCabinet(cabinet *string) *GetCampusesCampusIDSchedulesParams {
	o.SetCabinet(cabinet)
	return o
}

// SetCabinet adds the cabinet to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) SetCabinet(cabinet *string) {
	o.Cabinet = cabinet
}

// WithCampusID adds the campusID to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) WithCampusID(campusID int64) *GetCampusesCampusIDSchedulesParams {
	o.SetCampusID(campusID)
	return o
}

// SetCampusID adds the campusId to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) SetCampusID(campusID int64) {
	o.CampusID = campusID
}

// WithDate adds the date to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) WithDate(date *string) *GetCampusesCampusIDSchedulesParams {
	o.SetDate(date)
	return o
}

// SetDate adds the date to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) SetDate(date *string) {
	o.Date = date
}

// WithDay adds the day to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) WithDay(day *string) *GetCampusesCampusIDSchedulesParams {
	o.SetDay(day)
	return o
}

// SetDay adds the day to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) SetDay(day *string) {
	o.Day = day
}

// WithTeacher adds the teacher to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) WithTeacher(teacher *string) *GetCampusesCampusIDSchedulesParams {
	o.SetTeacher(teacher)
	return o
}

// SetTeacher adds the teacher to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) SetTeacher(teacher *string) {
	o.Teacher = teacher
}

// WithTitle adds the title to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) WithTitle(title *string) *GetCampusesCampusIDSchedulesParams {
	o.SetTitle(title)
	return o
}

// SetTitle adds the title to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) SetTitle(title *string) {
	o.Title = title
}

// WithWeek adds the week to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) WithWeek(week *string) *GetCampusesCampusIDSchedulesParams {
	o.SetWeek(week)
	return o
}

// SetWeek adds the week to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) SetWeek(week *string) {
	o.Week = week
}

// WithWeekday adds the weekday to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) WithWeekday(weekday *string) *GetCampusesCampusIDSchedulesParams {
	o.SetWeekday(weekday)
	return o
}

// SetWeekday adds the weekday to the get campuses campus ID schedules params.
func (o *GetCampusesCampusIDSchedulesParams) SetWeekday(weekday *string) {
	o.Weekday = weekday
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetCampusesCampusIDSchedulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cabinet != nil {

		// query param cabinet
		var qrCabinet string

		if o.Cabinet != nil {
			qrCabinet = *o.Cabinet
		}
		qCabinet := qrCabinet
		if qCabinet != "" {

			if err := r.SetQueryParam("cabinet", qCabinet); err != nil {
				return err
			}
		}
	}

	// path param campusId
	if err := r.SetPathParam("campusId", conv.FormatInteger(o.CampusID)); err != nil {
		return err
	}

	if o.Date != nil {

		// query param date
		var qrDate string

		if o.Date != nil {
			qrDate = *o.Date
		}
		qDate := qrDate
		if qDate != "" {

			if err := r.SetQueryParam("date", qDate); err != nil {
				return err
			}
		}
	}

	if o.Day != nil {

		// query param day
		var qrDay string

		if o.Day != nil {
			qrDay = *o.Day
		}
		qDay := qrDay
		if qDay != "" {

			if err := r.SetQueryParam("day", qDay); err != nil {
				return err
			}
		}
	}

	if o.Teacher != nil {

		// query param teacher
		var qrTeacher string

		if o.Teacher != nil {
			qrTeacher = *o.Teacher
		}
		qTeacher := qrTeacher
		if qTeacher != "" {

			if err := r.SetQueryParam("teacher", qTeacher); err != nil {
				return err
			}
		}
	}

	if o.Title != nil {

		// query param title
		var qrTitle string

		if o.Title != nil {
			qrTitle = *o.Title
		}
		qTitle := qrTitle
		if qTitle != "" {

			if err := r.SetQueryParam("title", qTitle); err != nil {
				return err
			}
		}
	}

	if o.Week != nil {

		// query param week
		var qrWeek string

		if o.Week != nil {
			qrWeek = *o.Week
		}
		qWeek := qrWeek
		if qWeek != "" {

			if err := r.SetQueryParam("week", qWeek); err != nil {
				return err
			}
		}
	}

	if o.Weekday != nil {

		// query param weekday
		var qrWeekday string

		if o.Weekday != nil {
			qrWeekday = *o.Weekday
		}
		qWeekday := qrWeekday
		if qWeekday != "" {

			if err := r.SetQueryParam("weekday", qWeekday); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
