// Code generated by go-swagger; DO NOT EDIT.

package schedules

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetCollegesCollegeIDSchedulesParams creates a new GetCollegesCollegeIDSchedulesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCollegesCollegeIDSchedulesParams() *GetCollegesCollegeIDSchedulesParams {
	return NewGetCollegesCollegeIDSchedulesParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetCollegesCollegeIDSchedulesParamsWithTimeout creates a new GetCollegesCollegeIDSchedulesParams object
// with the ability to set a timeout on a request.
func NewGetCollegesCollegeIDSchedulesParamsWithTimeout(timeout time.Duration) *GetCollegesCollegeIDSchedulesParams {
	return &GetCollegesCollegeIDSchedulesParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetCollegesCollegeIDSchedulesParamsWithContext creates a new GetCollegesCollegeIDSchedulesParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesCollegeIDSchedulesParams].
func NewGetCollegesCollegeIDSchedulesParamsWithContext(ctx context.Context) *GetCollegesCollegeIDSchedulesParams {
	return &GetCollegesCollegeIDSchedulesParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetCollegesCollegeIDSchedulesParamsWithHTTPClient creates a new GetCollegesCollegeIDSchedulesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCollegesCollegeIDSchedulesParamsWithHTTPClient(client *http.Client) *GetCollegesCollegeIDSchedulesParams {
	return &GetCollegesCollegeIDSchedulesParams{
		HTTPClient: client,
	}
}

/*
GetCollegesCollegeIDSchedulesParams contains all the parameters to send to the API endpoint

	for the get colleges college ID schedules operation.

	Typically these are written to a http.Request.
*/
type GetCollegesCollegeIDSchedulesParams struct {

	// Cabinet.
	//
	// like cabinet of lessons
	Cabinet *string

	// CollegeID.
	//
	// College ID
	CollegeID int64

	// Date.
	//
	// Specific date (yyyy-mm-dd)
	Date *string

	// Day.
	//
	// Relative day
	Day *string

	// Teacher.
	//
	// like teacher of lessons
	Teacher *string

	// Title.
	//
	// like title of lessons
	Title *string

	// Week.
	//
	// Week of schedules
	Week *string

	// Weekday.
	//
	// Weekday of schedules
	Weekday *string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get colleges college ID schedules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollegesCollegeIDSchedulesParams) WithDefaults() *GetCollegesCollegeIDSchedulesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get colleges college ID schedules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollegesCollegeIDSchedulesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) WithTimeout(timeout time.Duration) *GetCollegesCollegeIDSchedulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get colleges college ID schedules params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesCollegeIDSchedulesParams].
func (o *GetCollegesCollegeIDSchedulesParams) WithContext(ctx context.Context) *GetCollegesCollegeIDSchedulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get colleges college ID schedules params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesCollegeIDSchedulesParams].
func (o *GetCollegesCollegeIDSchedulesParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) WithHTTPClient(client *http.Client) *GetCollegesCollegeIDSchedulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCabinet adds the cabinet to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) WithCabinet(cabinet *string) *GetCollegesCollegeIDSchedulesParams {
	o.SetCabinet(cabinet)
	return o
}

// SetCabinet adds the cabinet to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) SetCabinet(cabinet *string) {
	o.Cabinet = cabinet
}

// WithCollegeID adds the collegeID to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) WithCollegeID(collegeID int64) *GetCollegesCollegeIDSchedulesParams {
	o.SetCollegeID(collegeID)
	return o
}

// SetCollegeID adds the collegeId to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) SetCollegeID(collegeID int64) {
	o.CollegeID = collegeID
}

// WithDate adds the date to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) WithDate(date *string) *GetCollegesCollegeIDSchedulesParams {
	o.SetDate(date)
	return o
}

// SetDate adds the date to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) SetDate(date *string) {
	o.Date = date
}

// WithDay adds the day to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) WithDay(day *string) *GetCollegesCollegeIDSchedulesParams {
	o.SetDay(day)
	return o
}

// SetDay adds the day to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) SetDay(day *string) {
	o.Day = day
}

// WithTeacher adds the teacher to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) WithTeacher(teacher *string) *GetCollegesCollegeIDSchedulesParams {
	o.SetTeacher(teacher)
	return o
}

// SetTeacher adds the teacher to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) SetTeacher(teacher *string) {
	o.Teacher = teacher
}

// WithTitle adds the title to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) WithTitle(title *string) *GetCollegesCollegeIDSchedulesParams {
	o.SetTitle(title)
	return o
}

// SetTitle adds the title to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) SetTitle(title *string) {
	o.Title = title
}

// WithWeek adds the week to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) WithWeek(week *string) *GetCollegesCollegeIDSchedulesParams {
	o.SetWeek(week)
	return o
}

// SetWeek adds the week to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) SetWeek(week *string) {
	o.Week = week
}

// WithWeekday adds the weekday to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) WithWeekday(weekday *string) *GetCollegesCollegeIDSchedulesParams {
	o.SetWeekday(weekday)
	return o
}

// SetWeekday adds the weekday to the get colleges college ID schedules params.
func (o *GetCollegesCollegeIDSchedulesParams) SetWeekday(weekday *string) {
	o.Weekday = weekday
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetCollegesCollegeIDSchedulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cabinet != nil {

		// query param cabinet
		var qrCabinet string

		if o.Cabinet != nil {
			qrCabinet = *o.Cabinet
		}
		qCabinet := qrCabinet
		if qCabinet != "" {

			if err := r.SetQueryParam("cabinet", qCabinet); err != nil {
				return err
			}
		}
	}

	// path param collegeId
	if err := r.SetPathParam("collegeId", conv.FormatInteger(o.CollegeID)); err != nil {
		return err
	}

	if o.Date != nil {

		// query param date
		var qrDate string

		if o.Date != nil {
			qrDate = *o.Date
		}
		qDate := qrDate
		if qDate != "" {

			if err := r.SetQueryParam("date", qDate); err != nil {
				return err
			}
		}
	}

	if o.Day != nil {

		// query param day
		var qrDay string

		if o.Day != nil {
			qrDay = *o.Day
		}
		qDay := qrDay
		if qDay != "" {

			if err := r.SetQueryParam("day", qDay); err != nil {
				return err
			}
		}
	}

	if o.Teacher != nil {

		// query param teacher
		var qrTeacher string

		if o.Teacher != nil {
			qrTeacher = *o.Teacher
		}
		qTeacher := qrTeacher
		if qTeacher != "" {

			if err := r.SetQueryParam("teacher", qTeacher); err != nil {
				return err
			}
		}
	}

	if o.Title != nil {

		// query param title
		var qrTitle string

		if o.Title != nil {
			qrTitle = *o.Title
		}
		qTitle := qrTitle
		if qTitle != "" {

			if err := r.SetQueryParam("title", qTitle); err != nil {
				return err
			}
		}
	}

	if o.Week != nil {

		// query param week
		var qrWeek string

		if o.Week != nil {
			qrWeek = *o.Week
		}
		qWeek := qrWeek
		if qWeek != "" {

			if err := r.SetQueryParam("week", qWeek); err != nil {
				return err
			}
		}
	}

	if o.Weekday != nil {

		// query param weekday
		var qrWeekday string

		if o.Weekday != nil {
			qrWeekday = *o.Weekday
		}
		qWeekday := qrWeekday
		if qWeekday != "" {

			if err := r.SetQueryParam("weekday", qWeekday); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
