// Code generated by go-swagger; DO NOT EDIT.

package schedules

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetCampusesCampusIDSchedulesReader is a Reader for the GetCampusesCampusIDSchedules structure.
type GetCampusesCampusIDSchedulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCampusesCampusIDSchedulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCampusesCampusIDSchedulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCampusesCampusIDSchedulesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCampusesCampusIDSchedulesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCampusesCampusIDSchedulesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /campuses/{campusId}/schedules] GetCampusesCampusIDSchedules", response, response.Code())
	}
}

// NewGetCampusesCampusIDSchedulesOK creates a GetCampusesCampusIDSchedulesOK with default headers values
func NewGetCampusesCampusIDSchedulesOK() *GetCampusesCampusIDSchedulesOK {
	return &GetCampusesCampusIDSchedulesOK{}
}

// GetCampusesCampusIDSchedulesOK describes a response with status code 200, with default header values.
//
// OK
type GetCampusesCampusIDSchedulesOK struct {
	Payload []*models.DtoScheduleResponse
}

// IsSuccess returns true when this get campuses campus Id schedules o k response has a 2xx status code
func (o *GetCampusesCampusIDSchedulesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get campuses campus Id schedules o k response has a 3xx status code
func (o *GetCampusesCampusIDSchedulesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get campuses campus Id schedules o k response has a 4xx status code
func (o *GetCampusesCampusIDSchedulesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get campuses campus Id schedules o k response has a 5xx status code
func (o *GetCampusesCampusIDSchedulesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get campuses campus Id schedules o k response a status code equal to that given
func (o *GetCampusesCampusIDSchedulesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get campuses campus Id schedules o k response
func (o *GetCampusesCampusIDSchedulesOK) Code() int {
	return 200
}

func (o *GetCampusesCampusIDSchedulesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{campusId}/schedules][%d] getCampusesCampusIdSchedulesOK %s", 200, payload)
}

func (o *GetCampusesCampusIDSchedulesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{campusId}/schedules][%d] getCampusesCampusIdSchedulesOK %s", 200, payload)
}

func (o *GetCampusesCampusIDSchedulesOK) GetPayload() []*models.DtoScheduleResponse {
	return o.Payload
}

func (o *GetCampusesCampusIDSchedulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCampusesCampusIDSchedulesBadRequest creates a GetCampusesCampusIDSchedulesBadRequest with default headers values
func NewGetCampusesCampusIDSchedulesBadRequest() *GetCampusesCampusIDSchedulesBadRequest {
	return &GetCampusesCampusIDSchedulesBadRequest{}
}

// GetCampusesCampusIDSchedulesBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type GetCampusesCampusIDSchedulesBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get campuses campus Id schedules bad request response has a 2xx status code
func (o *GetCampusesCampusIDSchedulesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get campuses campus Id schedules bad request response has a 3xx status code
func (o *GetCampusesCampusIDSchedulesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get campuses campus Id schedules bad request response has a 4xx status code
func (o *GetCampusesCampusIDSchedulesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get campuses campus Id schedules bad request response has a 5xx status code
func (o *GetCampusesCampusIDSchedulesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get campuses campus Id schedules bad request response a status code equal to that given
func (o *GetCampusesCampusIDSchedulesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get campuses campus Id schedules bad request response
func (o *GetCampusesCampusIDSchedulesBadRequest) Code() int {
	return 400
}

func (o *GetCampusesCampusIDSchedulesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{campusId}/schedules][%d] getCampusesCampusIdSchedulesBadRequest %s", 400, payload)
}

func (o *GetCampusesCampusIDSchedulesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{campusId}/schedules][%d] getCampusesCampusIdSchedulesBadRequest %s", 400, payload)
}

func (o *GetCampusesCampusIDSchedulesBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCampusesCampusIDSchedulesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCampusesCampusIDSchedulesNotFound creates a GetCampusesCampusIDSchedulesNotFound with default headers values
func NewGetCampusesCampusIDSchedulesNotFound() *GetCampusesCampusIDSchedulesNotFound {
	return &GetCampusesCampusIDSchedulesNotFound{}
}

// GetCampusesCampusIDSchedulesNotFound describes a response with status code 404, with default header values.
//
// Not Found
type GetCampusesCampusIDSchedulesNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get campuses campus Id schedules not found response has a 2xx status code
func (o *GetCampusesCampusIDSchedulesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get campuses campus Id schedules not found response has a 3xx status code
func (o *GetCampusesCampusIDSchedulesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get campuses campus Id schedules not found response has a 4xx status code
func (o *GetCampusesCampusIDSchedulesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get campuses campus Id schedules not found response has a 5xx status code
func (o *GetCampusesCampusIDSchedulesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get campuses campus Id schedules not found response a status code equal to that given
func (o *GetCampusesCampusIDSchedulesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get campuses campus Id schedules not found response
func (o *GetCampusesCampusIDSchedulesNotFound) Code() int {
	return 404
}

func (o *GetCampusesCampusIDSchedulesNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{campusId}/schedules][%d] getCampusesCampusIdSchedulesNotFound %s", 404, payload)
}

func (o *GetCampusesCampusIDSchedulesNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{campusId}/schedules][%d] getCampusesCampusIdSchedulesNotFound %s", 404, payload)
}

func (o *GetCampusesCampusIDSchedulesNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCampusesCampusIDSchedulesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCampusesCampusIDSchedulesInternalServerError creates a GetCampusesCampusIDSchedulesInternalServerError with default headers values
func NewGetCampusesCampusIDSchedulesInternalServerError() *GetCampusesCampusIDSchedulesInternalServerError {
	return &GetCampusesCampusIDSchedulesInternalServerError{}
}

// GetCampusesCampusIDSchedulesInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type GetCampusesCampusIDSchedulesInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get campuses campus Id schedules internal server error response has a 2xx status code
func (o *GetCampusesCampusIDSchedulesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get campuses campus Id schedules internal server error response has a 3xx status code
func (o *GetCampusesCampusIDSchedulesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get campuses campus Id schedules internal server error response has a 4xx status code
func (o *GetCampusesCampusIDSchedulesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get campuses campus Id schedules internal server error response has a 5xx status code
func (o *GetCampusesCampusIDSchedulesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get campuses campus Id schedules internal server error response a status code equal to that given
func (o *GetCampusesCampusIDSchedulesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get campuses campus Id schedules internal server error response
func (o *GetCampusesCampusIDSchedulesInternalServerError) Code() int {
	return 500
}

func (o *GetCampusesCampusIDSchedulesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{campusId}/schedules][%d] getCampusesCampusIdSchedulesInternalServerError %s", 500, payload)
}

func (o *GetCampusesCampusIDSchedulesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{campusId}/schedules][%d] getCampusesCampusIdSchedulesInternalServerError %s", 500, payload)
}

func (o *GetCampusesCampusIDSchedulesInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCampusesCampusIDSchedulesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
