// Code generated by go-swagger; DO NOT EDIT.

package schedules

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new schedules API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new schedules API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new schedules API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

// Client for schedules API.
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// GetCampusesCampusIDSchedules get schedules by campus ID.
	GetCampusesCampusIDSchedules(params *GetCampusesCampusIDSchedulesParams, opts ...ClientOption) (*GetCampusesCampusIDSchedulesOK, error)

	// GetCampusesCampusIDSchedulesContext get schedules by campus ID.
	GetCampusesCampusIDSchedulesContext(ctx context.Context, params *GetCampusesCampusIDSchedulesParams, opts ...ClientOption) (*GetCampusesCampusIDSchedulesOK, error)

	// GetCollegesCollegeIDSchedules get schedules by college ID.
	GetCollegesCollegeIDSchedules(params *GetCollegesCollegeIDSchedulesParams, opts ...ClientOption) (*GetCollegesCollegeIDSchedulesOK, error)

	// GetCollegesCollegeIDSchedulesContext get schedules by college ID.
	GetCollegesCollegeIDSchedulesContext(ctx context.Context, params *GetCollegesCollegeIDSchedulesParams, opts ...ClientOption) (*GetCollegesCollegeIDSchedulesOK, error)

	// GetGroupsGroupIDSchedules get schedules by group ID.
	GetGroupsGroupIDSchedules(params *GetGroupsGroupIDSchedulesParams, opts ...ClientOption) (*GetGroupsGroupIDSchedulesOK, error)

	// GetGroupsGroupIDSchedulesContext get schedules by group ID.
	GetGroupsGroupIDSchedulesContext(ctx context.Context, params *GetGroupsGroupIDSchedulesParams, opts ...ClientOption) (*GetGroupsGroupIDSchedulesOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

// GetCampusesCampusIDSchedules gets schedules by campus ID.
//
// get schedules by campus ID.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetCampusesCampusIDSchedulesContext] instead.
func (a *Client) GetCampusesCampusIDSchedules(params *GetCampusesCampusIDSchedulesParams, opts ...ClientOption) (*GetCampusesCampusIDSchedulesOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetCampusesCampusIDSchedulesContext(ctx, params, opts...)
}

// GetCampusesCampusIDSchedulesContext gets schedules by campus ID.
//
// get schedules by campus ID.
//
// Do not use the deprecated [GetCampusesCampusIDSchedulesParams.Context] with this method: it would be ignored.
func (a *Client) GetCampusesCampusIDSchedulesContext(ctx context.Context, params *GetCampusesCampusIDSchedulesParams, opts ...ClientOption) (*GetCampusesCampusIDSchedulesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetCampusesCampusIDSchedulesParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetCampusesCampusIDSchedules",
		Method:             "GET",
		PathPattern:        "/campuses/{campusId}/schedules",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCampusesCampusIDSchedulesReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetCampusesCampusIDSchedulesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCampusesCampusIDSchedules: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetCollegesCollegeIDSchedules gets schedules by college ID.
//
// get schedules by college ID.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetCollegesCollegeIDSchedulesContext] instead.
func (a *Client) GetCollegesCollegeIDSchedules(params *GetCollegesCollegeIDSchedulesParams, opts ...ClientOption) (*GetCollegesCollegeIDSchedulesOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetCollegesCollegeIDSchedulesContext(ctx, params, opts...)
}

// GetCollegesCollegeIDSchedulesContext gets schedules by college ID.
//
// get schedules by college ID.
//
// Do not use the deprecated [GetCollegesCollegeIDSchedulesParams.Context] with this method: it would be ignored.
func (a *Client) GetCollegesCollegeIDSchedulesContext(ctx context.Context, params *GetCollegesCollegeIDSchedulesParams, opts ...ClientOption) (*GetCollegesCollegeIDSchedulesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetCollegesCollegeIDSchedulesParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetCollegesCollegeIDSchedules",
		Method:             "GET",
		PathPattern:        "/colleges/{collegeId}/schedules",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCollegesCollegeIDSchedulesReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetCollegesCollegeIDSchedulesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCollegesCollegeIDSchedules: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetGroupsGroupIDSchedules gets schedules by group ID.
//
// get schedules by group ID.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetGroupsGroupIDSchedulesContext] instead.
func (a *Client) GetGroupsGroupIDSchedules(params *GetGroupsGroupIDSchedulesParams, opts ...ClientOption) (*GetGroupsGroupIDSchedulesOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetGroupsGroupIDSchedulesContext(ctx, params, opts...)
}

// GetGroupsGroupIDSchedulesContext gets schedules by group ID.
//
// get schedules by group ID.
//
// Do not use the deprecated [GetGroupsGroupIDSchedulesParams.Context] with this method: it would be ignored.
func (a *Client) GetGroupsGroupIDSchedulesContext(ctx context.Context, params *GetGroupsGroupIDSchedulesParams, opts ...ClientOption) (*GetGroupsGroupIDSchedulesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetGroupsGroupIDSchedulesParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetGroupsGroupIDSchedules",
		Method:             "GET",
		PathPattern:        "/groups/{groupId}/schedules",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetGroupsGroupIDSchedulesReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetGroupsGroupIDSchedulesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetGroupsGroupIDSchedules: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [SchedulesParams].
	ctx context.Context
}
