// Code generated by go-swagger; DO NOT EDIT.

package campuses

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new campuses API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new campuses API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new campuses API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

// Client for campuses API.
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// GetCampusesID get a campus by ID.
	GetCampusesID(params *GetCampusesIDParams, opts ...ClientOption) (*GetCampusesIDOK, error)

	// GetCampusesIDContext get a campus by ID.
	GetCampusesIDContext(ctx context.Context, params *GetCampusesIDParams, opts ...ClientOption) (*GetCampusesIDOK, error)

	// GetCampusesIDSchedulesLast get last lesson date.
	GetCampusesIDSchedulesLast(params *GetCampusesIDSchedulesLastParams, opts ...ClientOption) (*GetCampusesIDSchedulesLastOK, error)

	// GetCampusesIDSchedulesLastContext get last lesson date.
	GetCampusesIDSchedulesLastContext(ctx context.Context, params *GetCampusesIDSchedulesLastParams, opts ...ClientOption) (*GetCampusesIDSchedulesLastOK, error)

	// GetCollegesCollegeIDCampuses get campuses by college ID.
	GetCollegesCollegeIDCampuses(params *GetCollegesCollegeIDCampusesParams, opts ...ClientOption) (*GetCollegesCollegeIDCampusesOK, error)

	// GetCollegesCollegeIDCampusesContext get campuses by college ID.
	GetCollegesCollegeIDCampusesContext(ctx context.Context, params *GetCollegesCollegeIDCampusesParams, opts ...ClientOption) (*GetCollegesCollegeIDCampusesOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

// GetCampusesID gets a campus by ID.
//
// get a single campus by its ID.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetCampusesIDContext] instead.
func (a *Client) GetCampusesID(params *GetCampusesIDParams, opts ...ClientOption) (*GetCampusesIDOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetCampusesIDContext(ctx, params, opts...)
}

// GetCampusesIDContext gets a campus by ID.
//
// get a single campus by its ID.
//
// Do not use the deprecated [GetCampusesIDParams.Context] with this method: it would be ignored.
func (a *Client) GetCampusesIDContext(ctx context.Context, params *GetCampusesIDParams, opts ...ClientOption) (*GetCampusesIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetCampusesIDParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetCampusesID",
		Method:             "GET",
		PathPattern:        "/campuses/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCampusesIDReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetCampusesIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCampusesID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetCampusesIDSchedulesLast gets last lesson date.
//
// get the last lesson date by campus ID.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetCampusesIDSchedulesLastContext] instead.
func (a *Client) GetCampusesIDSchedulesLast(params *GetCampusesIDSchedulesLastParams, opts ...ClientOption) (*GetCampusesIDSchedulesLastOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetCampusesIDSchedulesLastContext(ctx, params, opts...)
}

// GetCampusesIDSchedulesLastContext gets last lesson date.
//
// get the last lesson date by campus ID.
//
// Do not use the deprecated [GetCampusesIDSchedulesLastParams.Context] with this method: it would be ignored.
func (a *Client) GetCampusesIDSchedulesLastContext(ctx context.Context, params *GetCampusesIDSchedulesLastParams, opts ...ClientOption) (*GetCampusesIDSchedulesLastOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetCampusesIDSchedulesLastParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetCampusesIDSchedulesLast",
		Method:             "GET",
		PathPattern:        "/campuses/{id}/schedules/last",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCampusesIDSchedulesLastReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetCampusesIDSchedulesLastOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCampusesIDSchedulesLast: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetCollegesCollegeIDCampuses gets campuses by college ID.
//
// get all campuses by college ID or a campus by college ID with specified name.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetCollegesCollegeIDCampusesContext] instead.
func (a *Client) GetCollegesCollegeIDCampuses(params *GetCollegesCollegeIDCampusesParams, opts ...ClientOption) (*GetCollegesCollegeIDCampusesOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetCollegesCollegeIDCampusesContext(ctx, params, opts...)
}

// GetCollegesCollegeIDCampusesContext gets campuses by college ID.
//
// get all campuses by college ID or a campus by college ID with specified name.
//
// Do not use the deprecated [GetCollegesCollegeIDCampusesParams.Context] with this method: it would be ignored.
func (a *Client) GetCollegesCollegeIDCampusesContext(ctx context.Context, params *GetCollegesCollegeIDCampusesParams, opts ...ClientOption) (*GetCollegesCollegeIDCampusesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetCollegesCollegeIDCampusesParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetCollegesCollegeIDCampuses",
		Method:             "GET",
		PathPattern:        "/colleges/{collegeId}/campuses",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCollegesCollegeIDCampusesReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetCollegesCollegeIDCampusesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCollegesCollegeIDCampuses: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [CampusesParams].
	ctx context.Context
}
