// Code generated by go-swagger; DO NOT EDIT.

package campuses

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetCollegesCollegeIDCampusesReader is a Reader for the GetCollegesCollegeIDCampuses structure.
type GetCollegesCollegeIDCampusesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCollegesCollegeIDCampusesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCollegesCollegeIDCampusesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCollegesCollegeIDCampusesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCollegesCollegeIDCampusesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCollegesCollegeIDCampusesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /colleges/{collegeId}/campuses] GetCollegesCollegeIDCampuses", response, response.Code())
	}
}

// NewGetCollegesCollegeIDCampusesOK creates a GetCollegesCollegeIDCampusesOK with default headers values
func NewGetCollegesCollegeIDCampusesOK() *GetCollegesCollegeIDCampusesOK {
	return &GetCollegesCollegeIDCampusesOK{}
}

// GetCollegesCollegeIDCampusesOK describes a response with status code 200, with default header values.
//
// OK
type GetCollegesCollegeIDCampusesOK struct {
	Payload []*models.DtoCampusResponse
}

// IsSuccess returns true when this get colleges college Id campuses o k response has a 2xx status code
func (o *GetCollegesCollegeIDCampusesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get colleges college Id campuses o k response has a 3xx status code
func (o *GetCollegesCollegeIDCampusesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges college Id campuses o k response has a 4xx status code
func (o *GetCollegesCollegeIDCampusesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get colleges college Id campuses o k response has a 5xx status code
func (o *GetCollegesCollegeIDCampusesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get colleges college Id campuses o k response a status code equal to that given
func (o *GetCollegesCollegeIDCampusesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get colleges college Id campuses o k response
func (o *GetCollegesCollegeIDCampusesOK) Code() int {
	return 200
}

func (o *GetCollegesCollegeIDCampusesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/campuses][%d] getCollegesCollegeIdCampusesOK %s", 200, payload)
}

func (o *GetCollegesCollegeIDCampusesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/campuses][%d] getCollegesCollegeIdCampusesOK %s", 200, payload)
}

func (o *GetCollegesCollegeIDCampusesOK) GetPayload() []*models.DtoCampusResponse {
	return o.Payload
}

func (o *GetCollegesCollegeIDCampusesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCollegesCollegeIDCampusesBadRequest creates a GetCollegesCollegeIDCampusesBadRequest with default headers values
func NewGetCollegesCollegeIDCampusesBadRequest() *GetCollegesCollegeIDCampusesBadRequest {
	return &GetCollegesCollegeIDCampusesBadRequest{}
}

// GetCollegesCollegeIDCampusesBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type GetCollegesCollegeIDCampusesBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get colleges college Id campuses bad request response has a 2xx status code
func (o *GetCollegesCollegeIDCampusesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get colleges college Id campuses bad request response has a 3xx status code
func (o *GetCollegesCollegeIDCampusesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges college Id campuses bad request response has a 4xx status code
func (o *GetCollegesCollegeIDCampusesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get colleges college Id campuses bad request response has a 5xx status code
func (o *GetCollegesCollegeIDCampusesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get colleges college Id campuses bad request response a status code equal to that given
func (o *GetCollegesCollegeIDCampusesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get colleges college Id campuses bad request response
func (o *GetCollegesCollegeIDCampusesBadRequest) Code() int {
	return 400
}

func (o *GetCollegesCollegeIDCampusesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/campuses][%d] getCollegesCollegeIdCampusesBadRequest %s", 400, payload)
}

func (o *GetCollegesCollegeIDCampusesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/campuses][%d] getCollegesCollegeIdCampusesBadRequest %s", 400, payload)
}

func (o *GetCollegesCollegeIDCampusesBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCollegesCollegeIDCampusesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCollegesCollegeIDCampusesNotFound creates a GetCollegesCollegeIDCampusesNotFound with default headers values
func NewGetCollegesCollegeIDCampusesNotFound() *GetCollegesCollegeIDCampusesNotFound {
	return &GetCollegesCollegeIDCampusesNotFound{}
}

// GetCollegesCollegeIDCampusesNotFound describes a response with status code 404, with default header values.
//
// Not Found
type GetCollegesCollegeIDCampusesNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get colleges college Id campuses not found response has a 2xx status code
func (o *GetCollegesCollegeIDCampusesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get colleges college Id campuses not found response has a 3xx status code
func (o *GetCollegesCollegeIDCampusesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges college Id campuses not found response has a 4xx status code
func (o *GetCollegesCollegeIDCampusesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get colleges college Id campuses not found response has a 5xx status code
func (o *GetCollegesCollegeIDCampusesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get colleges college Id campuses not found response a status code equal to that given
func (o *GetCollegesCollegeIDCampusesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get colleges college Id campuses not found response
func (o *GetCollegesCollegeIDCampusesNotFound) Code() int {
	return 404
}

func (o *GetCollegesCollegeIDCampusesNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/campuses][%d] getCollegesCollegeIdCampusesNotFound %s", 404, payload)
}

func (o *GetCollegesCollegeIDCampusesNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/campuses][%d] getCollegesCollegeIdCampusesNotFound %s", 404, payload)
}

func (o *GetCollegesCollegeIDCampusesNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCollegesCollegeIDCampusesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCollegesCollegeIDCampusesInternalServerError creates a GetCollegesCollegeIDCampusesInternalServerError with default headers values
func NewGetCollegesCollegeIDCampusesInternalServerError() *GetCollegesCollegeIDCampusesInternalServerError {
	return &GetCollegesCollegeIDCampusesInternalServerError{}
}

// GetCollegesCollegeIDCampusesInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type GetCollegesCollegeIDCampusesInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get colleges college Id campuses internal server error response has a 2xx status code
func (o *GetCollegesCollegeIDCampusesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get colleges college Id campuses internal server error response has a 3xx status code
func (o *GetCollegesCollegeIDCampusesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges college Id campuses internal server error response has a 4xx status code
func (o *GetCollegesCollegeIDCampusesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get colleges college Id campuses internal server error response has a 5xx status code
func (o *GetCollegesCollegeIDCampusesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get colleges college Id campuses internal server error response a status code equal to that given
func (o *GetCollegesCollegeIDCampusesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get colleges college Id campuses internal server error response
func (o *GetCollegesCollegeIDCampusesInternalServerError) Code() int {
	return 500
}

func (o *GetCollegesCollegeIDCampusesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/campuses][%d] getCollegesCollegeIdCampusesInternalServerError %s", 500, payload)
}

func (o *GetCollegesCollegeIDCampusesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/campuses][%d] getCollegesCollegeIdCampusesInternalServerError %s", 500, payload)
}

func (o *GetCollegesCollegeIDCampusesInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCollegesCollegeIDCampusesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
