// Code generated by go-swagger; DO NOT EDIT.

package campuses

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetCampusesIDReader is a Reader for the GetCampusesID structure.
type GetCampusesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCampusesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCampusesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCampusesIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCampusesIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCampusesIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /campuses/{id}] GetCampusesID", response, response.Code())
	}
}

// NewGetCampusesIDOK creates a GetCampusesIDOK with default headers values
func NewGetCampusesIDOK() *GetCampusesIDOK {
	return &GetCampusesIDOK{}
}

// GetCampusesIDOK describes a response with status code 200, with default header values.
//
// OK
type GetCampusesIDOK struct {
	Payload *models.DtoCampusResponse
}

// IsSuccess returns true when this get campuses Id o k response has a 2xx status code
func (o *GetCampusesIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get campuses Id o k response has a 3xx status code
func (o *GetCampusesIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get campuses Id o k response has a 4xx status code
func (o *GetCampusesIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get campuses Id o k response has a 5xx status code
func (o *GetCampusesIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get campuses Id o k response a status code equal to that given
func (o *GetCampusesIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get campuses Id o k response
func (o *GetCampusesIDOK) Code() int {
	return 200
}

func (o *GetCampusesIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{id}][%d] getCampusesIdOK %s", 200, payload)
}

func (o *GetCampusesIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{id}][%d] getCampusesIdOK %s", 200, payload)
}

func (o *GetCampusesIDOK) GetPayload() *models.DtoCampusResponse {
	return o.Payload
}

func (o *GetCampusesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoCampusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCampusesIDBadRequest creates a GetCampusesIDBadRequest with default headers values
func NewGetCampusesIDBadRequest() *GetCampusesIDBadRequest {
	return &GetCampusesIDBadRequest{}
}

// GetCampusesIDBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type GetCampusesIDBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get campuses Id bad request response has a 2xx status code
func (o *GetCampusesIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get campuses Id bad request response has a 3xx status code
func (o *GetCampusesIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get campuses Id bad request response has a 4xx status code
func (o *GetCampusesIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get campuses Id bad request response has a 5xx status code
func (o *GetCampusesIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get campuses Id bad request response a status code equal to that given
func (o *GetCampusesIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get campuses Id bad request response
func (o *GetCampusesIDBadRequest) Code() int {
	return 400
}

func (o *GetCampusesIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{id}][%d] getCampusesIdBadRequest %s", 400, payload)
}

func (o *GetCampusesIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{id}][%d] getCampusesIdBadRequest %s", 400, payload)
}

func (o *GetCampusesIDBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCampusesIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCampusesIDNotFound creates a GetCampusesIDNotFound with default headers values
func NewGetCampusesIDNotFound() *GetCampusesIDNotFound {
	return &GetCampusesIDNotFound{}
}

// GetCampusesIDNotFound describes a response with status code 404, with default header values.
//
// Not Found
type GetCampusesIDNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get campuses Id not found response has a 2xx status code
func (o *GetCampusesIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get campuses Id not found response has a 3xx status code
func (o *GetCampusesIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get campuses Id not found response has a 4xx status code
func (o *GetCampusesIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get campuses Id not found response has a 5xx status code
func (o *GetCampusesIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get campuses Id not found response a status code equal to that given
func (o *GetCampusesIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get campuses Id not found response
func (o *GetCampusesIDNotFound) Code() int {
	return 404
}

func (o *GetCampusesIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{id}][%d] getCampusesIdNotFound %s", 404, payload)
}

func (o *GetCampusesIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{id}][%d] getCampusesIdNotFound %s", 404, payload)
}

func (o *GetCampusesIDNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCampusesIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCampusesIDInternalServerError creates a GetCampusesIDInternalServerError with default headers values
func NewGetCampusesIDInternalServerError() *GetCampusesIDInternalServerError {
	return &GetCampusesIDInternalServerError{}
}

// GetCampusesIDInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type GetCampusesIDInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get campuses Id internal server error response has a 2xx status code
func (o *GetCampusesIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get campuses Id internal server error response has a 3xx status code
func (o *GetCampusesIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get campuses Id internal server error response has a 4xx status code
func (o *GetCampusesIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get campuses Id internal server error response has a 5xx status code
func (o *GetCampusesIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get campuses Id internal server error response a status code equal to that given
func (o *GetCampusesIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get campuses Id internal server error response
func (o *GetCampusesIDInternalServerError) Code() int {
	return 500
}

func (o *GetCampusesIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{id}][%d] getCampusesIdInternalServerError %s", 500, payload)
}

func (o *GetCampusesIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{id}][%d] getCampusesIdInternalServerError %s", 500, payload)
}

func (o *GetCampusesIDInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCampusesIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
