// Code generated by go-swagger; DO NOT EDIT.

package campuses

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetCampusesIDSchedulesLastReader is a Reader for the GetCampusesIDSchedulesLast structure.
type GetCampusesIDSchedulesLastReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCampusesIDSchedulesLastReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCampusesIDSchedulesLastOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCampusesIDSchedulesLastBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCampusesIDSchedulesLastNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCampusesIDSchedulesLastInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /campuses/{id}/schedules/last] GetCampusesIDSchedulesLast", response, response.Code())
	}
}

// NewGetCampusesIDSchedulesLastOK creates a GetCampusesIDSchedulesLastOK with default headers values
func NewGetCampusesIDSchedulesLastOK() *GetCampusesIDSchedulesLastOK {
	return &GetCampusesIDSchedulesLastOK{}
}

// GetCampusesIDSchedulesLastOK describes a response with status code 200, with default header values.
//
// OK
type GetCampusesIDSchedulesLastOK struct {
	Payload *models.DtoDateResponse
}

// IsSuccess returns true when this get campuses Id schedules last o k response has a 2xx status code
func (o *GetCampusesIDSchedulesLastOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get campuses Id schedules last o k response has a 3xx status code
func (o *GetCampusesIDSchedulesLastOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get campuses Id schedules last o k response has a 4xx status code
func (o *GetCampusesIDSchedulesLastOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get campuses Id schedules last o k response has a 5xx status code
func (o *GetCampusesIDSchedulesLastOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get campuses Id schedules last o k response a status code equal to that given
func (o *GetCampusesIDSchedulesLastOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get campuses Id schedules last o k response
func (o *GetCampusesIDSchedulesLastOK) Code() int {
	return 200
}

func (o *GetCampusesIDSchedulesLastOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{id}/schedules/last][%d] getCampusesIdSchedulesLastOK %s", 200, payload)
}

func (o *GetCampusesIDSchedulesLastOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{id}/schedules/last][%d] getCampusesIdSchedulesLastOK %s", 200, payload)
}

func (o *GetCampusesIDSchedulesLastOK) GetPayload() *models.DtoDateResponse {
	return o.Payload
}

func (o *GetCampusesIDSchedulesLastOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoDateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCampusesIDSchedulesLastBadRequest creates a GetCampusesIDSchedulesLastBadRequest with default headers values
func NewGetCampusesIDSchedulesLastBadRequest() *GetCampusesIDSchedulesLastBadRequest {
	return &GetCampusesIDSchedulesLastBadRequest{}
}

// GetCampusesIDSchedulesLastBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type GetCampusesIDSchedulesLastBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get campuses Id schedules last bad request response has a 2xx status code
func (o *GetCampusesIDSchedulesLastBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get campuses Id schedules last bad request response has a 3xx status code
func (o *GetCampusesIDSchedulesLastBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get campuses Id schedules last bad request response has a 4xx status code
func (o *GetCampusesIDSchedulesLastBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get campuses Id schedules last bad request response has a 5xx status code
func (o *GetCampusesIDSchedulesLastBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get campuses Id schedules last bad request response a status code equal to that given
func (o *GetCampusesIDSchedulesLastBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get campuses Id schedules last bad request response
func (o *GetCampusesIDSchedulesLastBadRequest) Code() int {
	return 400
}

func (o *GetCampusesIDSchedulesLastBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{id}/schedules/last][%d] getCampusesIdSchedulesLastBadRequest %s", 400, payload)
}

func (o *GetCampusesIDSchedulesLastBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{id}/schedules/last][%d] getCampusesIdSchedulesLastBadRequest %s", 400, payload)
}

func (o *GetCampusesIDSchedulesLastBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCampusesIDSchedulesLastBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCampusesIDSchedulesLastNotFound creates a GetCampusesIDSchedulesLastNotFound with default headers values
func NewGetCampusesIDSchedulesLastNotFound() *GetCampusesIDSchedulesLastNotFound {
	return &GetCampusesIDSchedulesLastNotFound{}
}

// GetCampusesIDSchedulesLastNotFound describes a response with status code 404, with default header values.
//
// Not Found
type GetCampusesIDSchedulesLastNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get campuses Id schedules last not found response has a 2xx status code
func (o *GetCampusesIDSchedulesLastNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get campuses Id schedules last not found response has a 3xx status code
func (o *GetCampusesIDSchedulesLastNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get campuses Id schedules last not found response has a 4xx status code
func (o *GetCampusesIDSchedulesLastNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get campuses Id schedules last not found response has a 5xx status code
func (o *GetCampusesIDSchedulesLastNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get campuses Id schedules last not found response a status code equal to that given
func (o *GetCampusesIDSchedulesLastNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get campuses Id schedules last not found response
func (o *GetCampusesIDSchedulesLastNotFound) Code() int {
	return 404
}

func (o *GetCampusesIDSchedulesLastNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{id}/schedules/last][%d] getCampusesIdSchedulesLastNotFound %s", 404, payload)
}

func (o *GetCampusesIDSchedulesLastNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{id}/schedules/last][%d] getCampusesIdSchedulesLastNotFound %s", 404, payload)
}

func (o *GetCampusesIDSchedulesLastNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCampusesIDSchedulesLastNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCampusesIDSchedulesLastInternalServerError creates a GetCampusesIDSchedulesLastInternalServerError with default headers values
func NewGetCampusesIDSchedulesLastInternalServerError() *GetCampusesIDSchedulesLastInternalServerError {
	return &GetCampusesIDSchedulesLastInternalServerError{}
}

// GetCampusesIDSchedulesLastInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type GetCampusesIDSchedulesLastInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get campuses Id schedules last internal server error response has a 2xx status code
func (o *GetCampusesIDSchedulesLastInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get campuses Id schedules last internal server error response has a 3xx status code
func (o *GetCampusesIDSchedulesLastInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get campuses Id schedules last internal server error response has a 4xx status code
func (o *GetCampusesIDSchedulesLastInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get campuses Id schedules last internal server error response has a 5xx status code
func (o *GetCampusesIDSchedulesLastInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get campuses Id schedules last internal server error response a status code equal to that given
func (o *GetCampusesIDSchedulesLastInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get campuses Id schedules last internal server error response
func (o *GetCampusesIDSchedulesLastInternalServerError) Code() int {
	return 500
}

func (o *GetCampusesIDSchedulesLastInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{id}/schedules/last][%d] getCampusesIdSchedulesLastInternalServerError %s", 500, payload)
}

func (o *GetCampusesIDSchedulesLastInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{id}/schedules/last][%d] getCampusesIdSchedulesLastInternalServerError %s", 500, payload)
}

func (o *GetCampusesIDSchedulesLastInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCampusesIDSchedulesLastInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
