// Code generated by go-swagger; DO NOT EDIT.

package campuses

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetCampusesIDParams creates a new GetCampusesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCampusesIDParams() *GetCampusesIDParams {
	return NewGetCampusesIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetCampusesIDParamsWithTimeout creates a new GetCampusesIDParams object
// with the ability to set a timeout on a request.
func NewGetCampusesIDParamsWithTimeout(timeout time.Duration) *GetCampusesIDParams {
	return &GetCampusesIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetCampusesIDParamsWithContext creates a new GetCampusesIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCampusesIDParams].
func NewGetCampusesIDParamsWithContext(ctx context.Context) *GetCampusesIDParams {
	return &GetCampusesIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetCampusesIDParamsWithHTTPClient creates a new GetCampusesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCampusesIDParamsWithHTTPClient(client *http.Client) *GetCampusesIDParams {
	return &GetCampusesIDParams{
		HTTPClient: client,
	}
}

/*
GetCampusesIDParams contains all the parameters to send to the API endpoint

	for the get campuses ID operation.

	Typically these are written to a http.Request.
*/
type GetCampusesIDParams struct {

	// ID.
	//
	// Campus ID
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get campuses ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCampusesIDParams) WithDefaults() *GetCampusesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get campuses ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCampusesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get campuses ID params.
func (o *GetCampusesIDParams) WithTimeout(timeout time.Duration) *GetCampusesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get campuses ID params.
func (o *GetCampusesIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get campuses ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCampusesIDParams].
func (o *GetCampusesIDParams) WithContext(ctx context.Context) *GetCampusesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get campuses ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCampusesIDParams].
func (o *GetCampusesIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get campuses ID params.
func (o *GetCampusesIDParams) WithHTTPClient(client *http.Client) *GetCampusesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get campuses ID params.
func (o *GetCampusesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get campuses ID params.
func (o *GetCampusesIDParams) WithID(id int64) *GetCampusesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get campuses ID params.
func (o *GetCampusesIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetCampusesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
