// Code generated by go-swagger; DO NOT EDIT.

package campuses

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetCollegesCollegeIDCampusesParams creates a new GetCollegesCollegeIDCampusesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCollegesCollegeIDCampusesParams() *GetCollegesCollegeIDCampusesParams {
	return NewGetCollegesCollegeIDCampusesParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetCollegesCollegeIDCampusesParamsWithTimeout creates a new GetCollegesCollegeIDCampusesParams object
// with the ability to set a timeout on a request.
func NewGetCollegesCollegeIDCampusesParamsWithTimeout(timeout time.Duration) *GetCollegesCollegeIDCampusesParams {
	return &GetCollegesCollegeIDCampusesParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetCollegesCollegeIDCampusesParamsWithContext creates a new GetCollegesCollegeIDCampusesParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesCollegeIDCampusesParams].
func NewGetCollegesCollegeIDCampusesParamsWithContext(ctx context.Context) *GetCollegesCollegeIDCampusesParams {
	return &GetCollegesCollegeIDCampusesParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetCollegesCollegeIDCampusesParamsWithHTTPClient creates a new GetCollegesCollegeIDCampusesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCollegesCollegeIDCampusesParamsWithHTTPClient(client *http.Client) *GetCollegesCollegeIDCampusesParams {
	return &GetCollegesCollegeIDCampusesParams{
		HTTPClient: client,
	}
}

/*
GetCollegesCollegeIDCampusesParams contains all the parameters to send to the API endpoint

	for the get colleges college ID campuses operation.

	Typically these are written to a http.Request.
*/
type GetCollegesCollegeIDCampusesParams struct {

	// CollegeID.
	//
	// College ID
	CollegeID int64

	// Name.
	//
	// Campus name
	Name *string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get colleges college ID campuses params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollegesCollegeIDCampusesParams) WithDefaults() *GetCollegesCollegeIDCampusesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get colleges college ID campuses params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollegesCollegeIDCampusesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get colleges college ID campuses params.
func (o *GetCollegesCollegeIDCampusesParams) WithTimeout(timeout time.Duration) *GetCollegesCollegeIDCampusesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get colleges college ID campuses params.
func (o *GetCollegesCollegeIDCampusesParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get colleges college ID campuses params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesCollegeIDCampusesParams].
func (o *GetCollegesCollegeIDCampusesParams) WithContext(ctx context.Context) *GetCollegesCollegeIDCampusesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get colleges college ID campuses params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesCollegeIDCampusesParams].
func (o *GetCollegesCollegeIDCampusesParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get colleges college ID campuses params.
func (o *GetCollegesCollegeIDCampusesParams) WithHTTPClient(client *http.Client) *GetCollegesCollegeIDCampusesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get colleges college ID campuses params.
func (o *GetCollegesCollegeIDCampusesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCollegeID adds the collegeID to the get colleges college ID campuses params.
func (o *GetCollegesCollegeIDCampusesParams) WithCollegeID(collegeID int64) *GetCollegesCollegeIDCampusesParams {
	o.SetCollegeID(collegeID)
	return o
}

// SetCollegeID adds the collegeId to the get colleges college ID campuses params.
func (o *GetCollegesCollegeIDCampusesParams) SetCollegeID(collegeID int64) {
	o.CollegeID = collegeID
}

// WithName adds the name to the get colleges college ID campuses params.
func (o *GetCollegesCollegeIDCampusesParams) WithName(name *string) *GetCollegesCollegeIDCampusesParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get colleges college ID campuses params.
func (o *GetCollegesCollegeIDCampusesParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetCollegesCollegeIDCampusesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param collegeId
	if err := r.SetPathParam("collegeId", conv.FormatInteger(o.CollegeID)); err != nil {
		return err
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
