// Code generated by go-swagger; DO NOT EDIT.

package parser

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetParserReader is a Reader for the GetParser structure.
type GetParserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetParserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetParserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetParserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetParserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /parser] GetParser", response, response.Code())
	}
}

// NewGetParserOK creates a GetParserOK with default headers values
func NewGetParserOK() *GetParserOK {
	return &GetParserOK{}
}

// GetParserOK describes a response with status code 200, with default header values.
//
// OK
type GetParserOK struct {
	Payload *models.DtoGetParserResponse
}

// IsSuccess returns true when this get parser o k response has a 2xx status code
func (o *GetParserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get parser o k response has a 3xx status code
func (o *GetParserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get parser o k response has a 4xx status code
func (o *GetParserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get parser o k response has a 5xx status code
func (o *GetParserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get parser o k response a status code equal to that given
func (o *GetParserOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get parser o k response
func (o *GetParserOK) Code() int {
	return 200
}

func (o *GetParserOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /parser][%d] getParserOK %s", 200, payload)
}

func (o *GetParserOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /parser][%d] getParserOK %s", 200, payload)
}

func (o *GetParserOK) GetPayload() *models.DtoGetParserResponse {
	return o.Payload
}

func (o *GetParserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoGetParserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetParserUnauthorized creates a GetParserUnauthorized with default headers values
func NewGetParserUnauthorized() *GetParserUnauthorized {
	return &GetParserUnauthorized{}
}

// GetParserUnauthorized describes a response with status code 401, with default header values.
//
// Unauthorized
type GetParserUnauthorized struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get parser unauthorized response has a 2xx status code
func (o *GetParserUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get parser unauthorized response has a 3xx status code
func (o *GetParserUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get parser unauthorized response has a 4xx status code
func (o *GetParserUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get parser unauthorized response has a 5xx status code
func (o *GetParserUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get parser unauthorized response a status code equal to that given
func (o *GetParserUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get parser unauthorized response
func (o *GetParserUnauthorized) Code() int {
	return 401
}

func (o *GetParserUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /parser][%d] getParserUnauthorized %s", 401, payload)
}

func (o *GetParserUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /parser][%d] getParserUnauthorized %s", 401, payload)
}

func (o *GetParserUnauthorized) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetParserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetParserInternalServerError creates a GetParserInternalServerError with default headers values
func NewGetParserInternalServerError() *GetParserInternalServerError {
	return &GetParserInternalServerError{}
}

// GetParserInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type GetParserInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get parser internal server error response has a 2xx status code
func (o *GetParserInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get parser internal server error response has a 3xx status code
func (o *GetParserInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get parser internal server error response has a 4xx status code
func (o *GetParserInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get parser internal server error response has a 5xx status code
func (o *GetParserInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get parser internal server error response a status code equal to that given
func (o *GetParserInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get parser internal server error response
func (o *GetParserInternalServerError) Code() int {
	return 500
}

func (o *GetParserInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /parser][%d] getParserInternalServerError %s", 500, payload)
}

func (o *GetParserInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /parser][%d] getParserInternalServerError %s", 500, payload)
}

func (o *GetParserInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetParserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
