// Code generated by go-swagger; DO NOT EDIT.

package parser

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetParserParams creates a new GetParserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetParserParams() *GetParserParams {
	return NewGetParserParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetParserParamsWithTimeout creates a new GetParserParams object
// with the ability to set a timeout on a request.
func NewGetParserParamsWithTimeout(timeout time.Duration) *GetParserParams {
	return &GetParserParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetParserParamsWithContext creates a new GetParserParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetParserParams].
func NewGetParserParamsWithContext(ctx context.Context) *GetParserParams {
	return &GetParserParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetParserParamsWithHTTPClient creates a new GetParserParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetParserParamsWithHTTPClient(client *http.Client) *GetParserParams {
	return &GetParserParams{
		HTTPClient: client,
	}
}

/*
GetParserParams contains all the parameters to send to the API endpoint

	for the get parser operation.

	Typically these are written to a http.Request.
*/
type GetParserParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get parser params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetParserParams) WithDefaults() *GetParserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get parser params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetParserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get parser params.
func (o *GetParserParams) WithTimeout(timeout time.Duration) *GetParserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get parser params.
func (o *GetParserParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get parser params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetParserParams].
func (o *GetParserParams) WithContext(ctx context.Context) *GetParserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get parser params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetParserParams].
func (o *GetParserParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get parser params.
func (o *GetParserParams) WithHTTPClient(client *http.Client) *GetParserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get parser params.
func (o *GetParserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetParserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
