// Code generated by go-swagger; DO NOT EDIT.

package parser

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new parser API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new parser API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new parser API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

// Client for parser API.
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// GetParser get parser information.
	GetParser(params *GetParserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetParserOK, error)

	// GetParserContext get parser information.
	GetParserContext(ctx context.Context, params *GetParserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetParserOK, error)

	// PostParserCalls update calls of parser college.
	PostParserCalls(params *PostParserCallsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostParserCallsNoContent, error)

	// PostParserCallsContext update calls of parser college.
	PostParserCallsContext(ctx context.Context, params *PostParserCallsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostParserCallsNoContent, error)

	// PostParserGroups update groups of parser college.
	PostParserGroups(params *PostParserGroupsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostParserGroupsNoContent, error)

	// PostParserGroupsContext update groups of parser college.
	PostParserGroupsContext(ctx context.Context, params *PostParserGroupsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostParserGroupsNoContent, error)

	// PostParserLessons add lessons to parser college.
	PostParserLessons(params *PostParserLessonsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostParserLessonsNoContent, error)

	// PostParserLessonsContext add lessons to parser college.
	PostParserLessonsContext(ctx context.Context, params *PostParserLessonsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostParserLessonsNoContent, error)

	SetTransport(transport runtime.ContextualTransport)
}

// GetParser gets parser information.
//
// get information about the college associated with the parser token.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetParserContext] instead.
func (a *Client) GetParser(params *GetParserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetParserOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetParserContext(ctx, params, authInfo, opts...)
}

// GetParserContext gets parser information.
//
// get information about the college associated with the parser token.
//
// Do not use the deprecated [GetParserParams.Context] with this method: it would be ignored.
func (a *Client) GetParserContext(ctx context.Context, params *GetParserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetParserOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetParserParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetParser",
		Method:             "GET",
		PathPattern:        "/parser",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetParserReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetParserOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetParser: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// PostParserCalls updates calls of parser college.
//
// update calls of parser college.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.PostParserCallsContext] instead.
func (a *Client) PostParserCalls(params *PostParserCallsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostParserCallsNoContent, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostParserCallsContext(ctx, params, authInfo, opts...)
}

// PostParserCallsContext updates calls of parser college.
//
// update calls of parser college.
//
// Do not use the deprecated [PostParserCallsParams.Context] with this method: it would be ignored.
func (a *Client) PostParserCallsContext(ctx context.Context, params *PostParserCallsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostParserCallsNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostParserCallsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostParserCalls",
		Method:             "POST",
		PathPattern:        "/parser/calls",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostParserCallsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostParserCallsNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostParserCalls: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// PostParserGroups updates groups of parser college.
//
// update groups of parser college.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.PostParserGroupsContext] instead.
func (a *Client) PostParserGroups(params *PostParserGroupsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostParserGroupsNoContent, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostParserGroupsContext(ctx, params, authInfo, opts...)
}

// PostParserGroupsContext updates groups of parser college.
//
// update groups of parser college.
//
// Do not use the deprecated [PostParserGroupsParams.Context] with this method: it would be ignored.
func (a *Client) PostParserGroupsContext(ctx context.Context, params *PostParserGroupsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostParserGroupsNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostParserGroupsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostParserGroups",
		Method:             "POST",
		PathPattern:        "/parser/groups",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostParserGroupsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostParserGroupsNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostParserGroups: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// PostParserLessons adds lessons to parser college.
//
// add lessons to parser college.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.PostParserLessonsContext] instead.
func (a *Client) PostParserLessons(params *PostParserLessonsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostParserLessonsNoContent, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostParserLessonsContext(ctx, params, authInfo, opts...)
}

// PostParserLessonsContext adds lessons to parser college.
//
// add lessons to parser college.
//
// Do not use the deprecated [PostParserLessonsParams.Context] with this method: it would be ignored.
func (a *Client) PostParserLessonsContext(ctx context.Context, params *PostParserLessonsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostParserLessonsNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostParserLessonsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostParserLessons",
		Method:             "POST",
		PathPattern:        "/parser/lessons",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostParserLessonsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostParserLessonsNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostParserLessons: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [ParserParams].
	ctx context.Context
}
