// Code generated by go-swagger; DO NOT EDIT.

package parser

import (
	"context"
	"net/http"
	"time"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostParserCallsParams creates a new PostParserCallsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostParserCallsParams() *PostParserCallsParams {
	return NewPostParserCallsParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostParserCallsParamsWithTimeout creates a new PostParserCallsParams object
// with the ability to set a timeout on a request.
func NewPostParserCallsParamsWithTimeout(timeout time.Duration) *PostParserCallsParams {
	return &PostParserCallsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostParserCallsParamsWithContext creates a new PostParserCallsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostParserCallsParams].
func NewPostParserCallsParamsWithContext(ctx context.Context) *PostParserCallsParams {
	return &PostParserCallsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostParserCallsParamsWithHTTPClient creates a new PostParserCallsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostParserCallsParamsWithHTTPClient(client *http.Client) *PostParserCallsParams {
	return &PostParserCallsParams{
		HTTPClient: client,
	}
}

/*
PostParserCallsParams contains all the parameters to send to the API endpoint

	for the post parser calls operation.

	Typically these are written to a http.Request.
*/
type PostParserCallsParams struct {

	// Calls.
	//
	// Calls
	Calls []*models.DtoCall

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post parser calls params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostParserCallsParams) WithDefaults() *PostParserCallsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post parser calls params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostParserCallsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post parser calls params.
func (o *PostParserCallsParams) WithTimeout(timeout time.Duration) *PostParserCallsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post parser calls params.
func (o *PostParserCallsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post parser calls params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostParserCallsParams].
func (o *PostParserCallsParams) WithContext(ctx context.Context) *PostParserCallsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post parser calls params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostParserCallsParams].
func (o *PostParserCallsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post parser calls params.
func (o *PostParserCallsParams) WithHTTPClient(client *http.Client) *PostParserCallsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post parser calls params.
func (o *PostParserCallsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCalls adds the calls to the post parser calls params.
func (o *PostParserCallsParams) WithCalls(calls []*models.DtoCall) *PostParserCallsParams {
	o.SetCalls(calls)
	return o
}

// SetCalls adds the calls to the post parser calls params.
func (o *PostParserCallsParams) SetCalls(calls []*models.DtoCall) {
	o.Calls = calls
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostParserCallsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Calls != nil {
		if err := r.SetBodyParam(o.Calls); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
