// Code generated by go-swagger; DO NOT EDIT.

package parser

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostParserLessonsReader is a Reader for the PostParserLessons structure.
type PostParserLessonsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostParserLessonsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewPostParserLessonsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostParserLessonsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostParserLessonsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostParserLessonsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /parser/lessons] PostParserLessons", response, response.Code())
	}
}

// NewPostParserLessonsNoContent creates a PostParserLessonsNoContent with default headers values
func NewPostParserLessonsNoContent() *PostParserLessonsNoContent {
	return &PostParserLessonsNoContent{}
}

// PostParserLessonsNoContent describes a response with status code 204, with default header values.
//
// No Content
type PostParserLessonsNoContent struct {
}

// IsSuccess returns true when this post parser lessons no content response has a 2xx status code
func (o *PostParserLessonsNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post parser lessons no content response has a 3xx status code
func (o *PostParserLessonsNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post parser lessons no content response has a 4xx status code
func (o *PostParserLessonsNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post parser lessons no content response has a 5xx status code
func (o *PostParserLessonsNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post parser lessons no content response a status code equal to that given
func (o *PostParserLessonsNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post parser lessons no content response
func (o *PostParserLessonsNoContent) Code() int {
	return 204
}

func (o *PostParserLessonsNoContent) Error() string {
	return fmt.Sprintf("[POST /parser/lessons][%d] postParserLessonsNoContent", 204)
}

func (o *PostParserLessonsNoContent) String() string {
	return fmt.Sprintf("[POST /parser/lessons][%d] postParserLessonsNoContent", 204)
}

func (o *PostParserLessonsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostParserLessonsBadRequest creates a PostParserLessonsBadRequest with default headers values
func NewPostParserLessonsBadRequest() *PostParserLessonsBadRequest {
	return &PostParserLessonsBadRequest{}
}

// PostParserLessonsBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type PostParserLessonsBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post parser lessons bad request response has a 2xx status code
func (o *PostParserLessonsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post parser lessons bad request response has a 3xx status code
func (o *PostParserLessonsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post parser lessons bad request response has a 4xx status code
func (o *PostParserLessonsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post parser lessons bad request response has a 5xx status code
func (o *PostParserLessonsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post parser lessons bad request response a status code equal to that given
func (o *PostParserLessonsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post parser lessons bad request response
func (o *PostParserLessonsBadRequest) Code() int {
	return 400
}

func (o *PostParserLessonsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/lessons][%d] postParserLessonsBadRequest %s", 400, payload)
}

func (o *PostParserLessonsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/lessons][%d] postParserLessonsBadRequest %s", 400, payload)
}

func (o *PostParserLessonsBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostParserLessonsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostParserLessonsUnauthorized creates a PostParserLessonsUnauthorized with default headers values
func NewPostParserLessonsUnauthorized() *PostParserLessonsUnauthorized {
	return &PostParserLessonsUnauthorized{}
}

// PostParserLessonsUnauthorized describes a response with status code 401, with default header values.
//
// Unauthorized
type PostParserLessonsUnauthorized struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post parser lessons unauthorized response has a 2xx status code
func (o *PostParserLessonsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post parser lessons unauthorized response has a 3xx status code
func (o *PostParserLessonsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post parser lessons unauthorized response has a 4xx status code
func (o *PostParserLessonsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post parser lessons unauthorized response has a 5xx status code
func (o *PostParserLessonsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post parser lessons unauthorized response a status code equal to that given
func (o *PostParserLessonsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post parser lessons unauthorized response
func (o *PostParserLessonsUnauthorized) Code() int {
	return 401
}

func (o *PostParserLessonsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/lessons][%d] postParserLessonsUnauthorized %s", 401, payload)
}

func (o *PostParserLessonsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/lessons][%d] postParserLessonsUnauthorized %s", 401, payload)
}

func (o *PostParserLessonsUnauthorized) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostParserLessonsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostParserLessonsInternalServerError creates a PostParserLessonsInternalServerError with default headers values
func NewPostParserLessonsInternalServerError() *PostParserLessonsInternalServerError {
	return &PostParserLessonsInternalServerError{}
}

// PostParserLessonsInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type PostParserLessonsInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post parser lessons internal server error response has a 2xx status code
func (o *PostParserLessonsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post parser lessons internal server error response has a 3xx status code
func (o *PostParserLessonsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post parser lessons internal server error response has a 4xx status code
func (o *PostParserLessonsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post parser lessons internal server error response has a 5xx status code
func (o *PostParserLessonsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post parser lessons internal server error response a status code equal to that given
func (o *PostParserLessonsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post parser lessons internal server error response
func (o *PostParserLessonsInternalServerError) Code() int {
	return 500
}

func (o *PostParserLessonsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/lessons][%d] postParserLessonsInternalServerError %s", 500, payload)
}

func (o *PostParserLessonsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/lessons][%d] postParserLessonsInternalServerError %s", 500, payload)
}

func (o *PostParserLessonsInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostParserLessonsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
