// Code generated by go-swagger; DO NOT EDIT.

package parser

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostParserCallsReader is a Reader for the PostParserCalls structure.
type PostParserCallsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostParserCallsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewPostParserCallsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostParserCallsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostParserCallsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostParserCallsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /parser/calls] PostParserCalls", response, response.Code())
	}
}

// NewPostParserCallsNoContent creates a PostParserCallsNoContent with default headers values
func NewPostParserCallsNoContent() *PostParserCallsNoContent {
	return &PostParserCallsNoContent{}
}

// PostParserCallsNoContent describes a response with status code 204, with default header values.
//
// No Content
type PostParserCallsNoContent struct {
}

// IsSuccess returns true when this post parser calls no content response has a 2xx status code
func (o *PostParserCallsNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post parser calls no content response has a 3xx status code
func (o *PostParserCallsNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post parser calls no content response has a 4xx status code
func (o *PostParserCallsNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post parser calls no content response has a 5xx status code
func (o *PostParserCallsNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post parser calls no content response a status code equal to that given
func (o *PostParserCallsNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post parser calls no content response
func (o *PostParserCallsNoContent) Code() int {
	return 204
}

func (o *PostParserCallsNoContent) Error() string {
	return fmt.Sprintf("[POST /parser/calls][%d] postParserCallsNoContent", 204)
}

func (o *PostParserCallsNoContent) String() string {
	return fmt.Sprintf("[POST /parser/calls][%d] postParserCallsNoContent", 204)
}

func (o *PostParserCallsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostParserCallsBadRequest creates a PostParserCallsBadRequest with default headers values
func NewPostParserCallsBadRequest() *PostParserCallsBadRequest {
	return &PostParserCallsBadRequest{}
}

// PostParserCallsBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type PostParserCallsBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post parser calls bad request response has a 2xx status code
func (o *PostParserCallsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post parser calls bad request response has a 3xx status code
func (o *PostParserCallsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post parser calls bad request response has a 4xx status code
func (o *PostParserCallsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post parser calls bad request response has a 5xx status code
func (o *PostParserCallsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post parser calls bad request response a status code equal to that given
func (o *PostParserCallsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post parser calls bad request response
func (o *PostParserCallsBadRequest) Code() int {
	return 400
}

func (o *PostParserCallsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/calls][%d] postParserCallsBadRequest %s", 400, payload)
}

func (o *PostParserCallsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/calls][%d] postParserCallsBadRequest %s", 400, payload)
}

func (o *PostParserCallsBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostParserCallsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostParserCallsUnauthorized creates a PostParserCallsUnauthorized with default headers values
func NewPostParserCallsUnauthorized() *PostParserCallsUnauthorized {
	return &PostParserCallsUnauthorized{}
}

// PostParserCallsUnauthorized describes a response with status code 401, with default header values.
//
// Unauthorized
type PostParserCallsUnauthorized struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post parser calls unauthorized response has a 2xx status code
func (o *PostParserCallsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post parser calls unauthorized response has a 3xx status code
func (o *PostParserCallsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post parser calls unauthorized response has a 4xx status code
func (o *PostParserCallsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post parser calls unauthorized response has a 5xx status code
func (o *PostParserCallsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post parser calls unauthorized response a status code equal to that given
func (o *PostParserCallsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post parser calls unauthorized response
func (o *PostParserCallsUnauthorized) Code() int {
	return 401
}

func (o *PostParserCallsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/calls][%d] postParserCallsUnauthorized %s", 401, payload)
}

func (o *PostParserCallsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/calls][%d] postParserCallsUnauthorized %s", 401, payload)
}

func (o *PostParserCallsUnauthorized) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostParserCallsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostParserCallsInternalServerError creates a PostParserCallsInternalServerError with default headers values
func NewPostParserCallsInternalServerError() *PostParserCallsInternalServerError {
	return &PostParserCallsInternalServerError{}
}

// PostParserCallsInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type PostParserCallsInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post parser calls internal server error response has a 2xx status code
func (o *PostParserCallsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post parser calls internal server error response has a 3xx status code
func (o *PostParserCallsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post parser calls internal server error response has a 4xx status code
func (o *PostParserCallsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post parser calls internal server error response has a 5xx status code
func (o *PostParserCallsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post parser calls internal server error response a status code equal to that given
func (o *PostParserCallsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post parser calls internal server error response
func (o *PostParserCallsInternalServerError) Code() int {
	return 500
}

func (o *PostParserCallsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/calls][%d] postParserCallsInternalServerError %s", 500, payload)
}

func (o *PostParserCallsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/calls][%d] postParserCallsInternalServerError %s", 500, payload)
}

func (o *PostParserCallsInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostParserCallsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
