// Code generated by go-swagger; DO NOT EDIT.

package parser

import (
	"context"
	"net/http"
	"time"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostParserLessonsParams creates a new PostParserLessonsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostParserLessonsParams() *PostParserLessonsParams {
	return NewPostParserLessonsParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostParserLessonsParamsWithTimeout creates a new PostParserLessonsParams object
// with the ability to set a timeout on a request.
func NewPostParserLessonsParamsWithTimeout(timeout time.Duration) *PostParserLessonsParams {
	return &PostParserLessonsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostParserLessonsParamsWithContext creates a new PostParserLessonsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostParserLessonsParams].
func NewPostParserLessonsParamsWithContext(ctx context.Context) *PostParserLessonsParams {
	return &PostParserLessonsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostParserLessonsParamsWithHTTPClient creates a new PostParserLessonsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostParserLessonsParamsWithHTTPClient(client *http.Client) *PostParserLessonsParams {
	return &PostParserLessonsParams{
		HTTPClient: client,
	}
}

/*
PostParserLessonsParams contains all the parameters to send to the API endpoint

	for the post parser lessons operation.

	Typically these are written to a http.Request.
*/
type PostParserLessonsParams struct {

	// Lessons.
	//
	// Lessons
	Lessons []*models.DtoLesson

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post parser lessons params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostParserLessonsParams) WithDefaults() *PostParserLessonsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post parser lessons params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostParserLessonsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post parser lessons params.
func (o *PostParserLessonsParams) WithTimeout(timeout time.Duration) *PostParserLessonsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post parser lessons params.
func (o *PostParserLessonsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post parser lessons params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostParserLessonsParams].
func (o *PostParserLessonsParams) WithContext(ctx context.Context) *PostParserLessonsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post parser lessons params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostParserLessonsParams].
func (o *PostParserLessonsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post parser lessons params.
func (o *PostParserLessonsParams) WithHTTPClient(client *http.Client) *PostParserLessonsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post parser lessons params.
func (o *PostParserLessonsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLessons adds the lessons to the post parser lessons params.
func (o *PostParserLessonsParams) WithLessons(lessons []*models.DtoLesson) *PostParserLessonsParams {
	o.SetLessons(lessons)
	return o
}

// SetLessons adds the lessons to the post parser lessons params.
func (o *PostParserLessonsParams) SetLessons(lessons []*models.DtoLesson) {
	o.Lessons = lessons
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostParserLessonsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Lessons != nil {
		if err := r.SetBodyParam(o.Lessons); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
