// Code generated by go-swagger; DO NOT EDIT.

package parser

import (
	"context"
	"net/http"
	"time"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostParserGroupsParams creates a new PostParserGroupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostParserGroupsParams() *PostParserGroupsParams {
	return NewPostParserGroupsParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostParserGroupsParamsWithTimeout creates a new PostParserGroupsParams object
// with the ability to set a timeout on a request.
func NewPostParserGroupsParamsWithTimeout(timeout time.Duration) *PostParserGroupsParams {
	return &PostParserGroupsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostParserGroupsParamsWithContext creates a new PostParserGroupsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostParserGroupsParams].
func NewPostParserGroupsParamsWithContext(ctx context.Context) *PostParserGroupsParams {
	return &PostParserGroupsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostParserGroupsParamsWithHTTPClient creates a new PostParserGroupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostParserGroupsParamsWithHTTPClient(client *http.Client) *PostParserGroupsParams {
	return &PostParserGroupsParams{
		HTTPClient: client,
	}
}

/*
PostParserGroupsParams contains all the parameters to send to the API endpoint

	for the post parser groups operation.

	Typically these are written to a http.Request.
*/
type PostParserGroupsParams struct {

	// UpdateGroupsRequest.
	//
	// Update groups request
	UpdateGroupsRequest *models.DtoUpdateGroupsRequest

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post parser groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostParserGroupsParams) WithDefaults() *PostParserGroupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post parser groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostParserGroupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post parser groups params.
func (o *PostParserGroupsParams) WithTimeout(timeout time.Duration) *PostParserGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post parser groups params.
func (o *PostParserGroupsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post parser groups params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostParserGroupsParams].
func (o *PostParserGroupsParams) WithContext(ctx context.Context) *PostParserGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post parser groups params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostParserGroupsParams].
func (o *PostParserGroupsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post parser groups params.
func (o *PostParserGroupsParams) WithHTTPClient(client *http.Client) *PostParserGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post parser groups params.
func (o *PostParserGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUpdateGroupsRequest adds the updateGroupsRequest to the post parser groups params.
func (o *PostParserGroupsParams) WithUpdateGroupsRequest(updateGroupsRequest *models.DtoUpdateGroupsRequest) *PostParserGroupsParams {
	o.SetUpdateGroupsRequest(updateGroupsRequest)
	return o
}

// SetUpdateGroupsRequest adds the updateGroupsRequest to the post parser groups params.
func (o *PostParserGroupsParams) SetUpdateGroupsRequest(updateGroupsRequest *models.DtoUpdateGroupsRequest) {
	o.UpdateGroupsRequest = updateGroupsRequest
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostParserGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.UpdateGroupsRequest != nil {
		if err := r.SetBodyParam(o.UpdateGroupsRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
