// Code generated by go-swagger; DO NOT EDIT.

package parser

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostParserReplacesReader is a Reader for the PostParserReplaces structure.
type PostParserReplacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostParserReplacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewPostParserReplacesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostParserReplacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostParserReplacesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostParserReplacesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /parser/replaces] PostParserReplaces", response, response.Code())
	}
}

// NewPostParserReplacesNoContent creates a PostParserReplacesNoContent with default headers values
func NewPostParserReplacesNoContent() *PostParserReplacesNoContent {
	return &PostParserReplacesNoContent{}
}

// PostParserReplacesNoContent describes a response with status code 204, with default header values.
//
// No Content
type PostParserReplacesNoContent struct {
}

// IsSuccess returns true when this post parser replaces no content response has a 2xx status code
func (o *PostParserReplacesNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post parser replaces no content response has a 3xx status code
func (o *PostParserReplacesNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post parser replaces no content response has a 4xx status code
func (o *PostParserReplacesNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post parser replaces no content response has a 5xx status code
func (o *PostParserReplacesNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post parser replaces no content response a status code equal to that given
func (o *PostParserReplacesNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post parser replaces no content response
func (o *PostParserReplacesNoContent) Code() int {
	return 204
}

func (o *PostParserReplacesNoContent) Error() string {
	return fmt.Sprintf("[POST /parser/replaces][%d] postParserReplacesNoContent", 204)
}

func (o *PostParserReplacesNoContent) String() string {
	return fmt.Sprintf("[POST /parser/replaces][%d] postParserReplacesNoContent", 204)
}

func (o *PostParserReplacesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostParserReplacesBadRequest creates a PostParserReplacesBadRequest with default headers values
func NewPostParserReplacesBadRequest() *PostParserReplacesBadRequest {
	return &PostParserReplacesBadRequest{}
}

// PostParserReplacesBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type PostParserReplacesBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post parser replaces bad request response has a 2xx status code
func (o *PostParserReplacesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post parser replaces bad request response has a 3xx status code
func (o *PostParserReplacesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post parser replaces bad request response has a 4xx status code
func (o *PostParserReplacesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post parser replaces bad request response has a 5xx status code
func (o *PostParserReplacesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post parser replaces bad request response a status code equal to that given
func (o *PostParserReplacesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post parser replaces bad request response
func (o *PostParserReplacesBadRequest) Code() int {
	return 400
}

func (o *PostParserReplacesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/replaces][%d] postParserReplacesBadRequest %s", 400, payload)
}

func (o *PostParserReplacesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/replaces][%d] postParserReplacesBadRequest %s", 400, payload)
}

func (o *PostParserReplacesBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostParserReplacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostParserReplacesUnauthorized creates a PostParserReplacesUnauthorized with default headers values
func NewPostParserReplacesUnauthorized() *PostParserReplacesUnauthorized {
	return &PostParserReplacesUnauthorized{}
}

// PostParserReplacesUnauthorized describes a response with status code 401, with default header values.
//
// Unauthorized
type PostParserReplacesUnauthorized struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post parser replaces unauthorized response has a 2xx status code
func (o *PostParserReplacesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post parser replaces unauthorized response has a 3xx status code
func (o *PostParserReplacesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post parser replaces unauthorized response has a 4xx status code
func (o *PostParserReplacesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post parser replaces unauthorized response has a 5xx status code
func (o *PostParserReplacesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post parser replaces unauthorized response a status code equal to that given
func (o *PostParserReplacesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post parser replaces unauthorized response
func (o *PostParserReplacesUnauthorized) Code() int {
	return 401
}

func (o *PostParserReplacesUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/replaces][%d] postParserReplacesUnauthorized %s", 401, payload)
}

func (o *PostParserReplacesUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/replaces][%d] postParserReplacesUnauthorized %s", 401, payload)
}

func (o *PostParserReplacesUnauthorized) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostParserReplacesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostParserReplacesInternalServerError creates a PostParserReplacesInternalServerError with default headers values
func NewPostParserReplacesInternalServerError() *PostParserReplacesInternalServerError {
	return &PostParserReplacesInternalServerError{}
}

// PostParserReplacesInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type PostParserReplacesInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post parser replaces internal server error response has a 2xx status code
func (o *PostParserReplacesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post parser replaces internal server error response has a 3xx status code
func (o *PostParserReplacesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post parser replaces internal server error response has a 4xx status code
func (o *PostParserReplacesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post parser replaces internal server error response has a 5xx status code
func (o *PostParserReplacesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post parser replaces internal server error response a status code equal to that given
func (o *PostParserReplacesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post parser replaces internal server error response
func (o *PostParserReplacesInternalServerError) Code() int {
	return 500
}

func (o *PostParserReplacesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/replaces][%d] postParserReplacesInternalServerError %s", 500, payload)
}

func (o *PostParserReplacesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/replaces][%d] postParserReplacesInternalServerError %s", 500, payload)
}

func (o *PostParserReplacesInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostParserReplacesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
