// Code generated by go-swagger; DO NOT EDIT.

package parser

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostParserGroupsReader is a Reader for the PostParserGroups structure.
type PostParserGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostParserGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewPostParserGroupsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostParserGroupsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostParserGroupsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostParserGroupsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /parser/groups] PostParserGroups", response, response.Code())
	}
}

// NewPostParserGroupsNoContent creates a PostParserGroupsNoContent with default headers values
func NewPostParserGroupsNoContent() *PostParserGroupsNoContent {
	return &PostParserGroupsNoContent{}
}

// PostParserGroupsNoContent describes a response with status code 204, with default header values.
//
// No Content
type PostParserGroupsNoContent struct {
}

// IsSuccess returns true when this post parser groups no content response has a 2xx status code
func (o *PostParserGroupsNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post parser groups no content response has a 3xx status code
func (o *PostParserGroupsNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post parser groups no content response has a 4xx status code
func (o *PostParserGroupsNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post parser groups no content response has a 5xx status code
func (o *PostParserGroupsNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post parser groups no content response a status code equal to that given
func (o *PostParserGroupsNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post parser groups no content response
func (o *PostParserGroupsNoContent) Code() int {
	return 204
}

func (o *PostParserGroupsNoContent) Error() string {
	return fmt.Sprintf("[POST /parser/groups][%d] postParserGroupsNoContent", 204)
}

func (o *PostParserGroupsNoContent) String() string {
	return fmt.Sprintf("[POST /parser/groups][%d] postParserGroupsNoContent", 204)
}

func (o *PostParserGroupsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostParserGroupsBadRequest creates a PostParserGroupsBadRequest with default headers values
func NewPostParserGroupsBadRequest() *PostParserGroupsBadRequest {
	return &PostParserGroupsBadRequest{}
}

// PostParserGroupsBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type PostParserGroupsBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post parser groups bad request response has a 2xx status code
func (o *PostParserGroupsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post parser groups bad request response has a 3xx status code
func (o *PostParserGroupsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post parser groups bad request response has a 4xx status code
func (o *PostParserGroupsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post parser groups bad request response has a 5xx status code
func (o *PostParserGroupsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post parser groups bad request response a status code equal to that given
func (o *PostParserGroupsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post parser groups bad request response
func (o *PostParserGroupsBadRequest) Code() int {
	return 400
}

func (o *PostParserGroupsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/groups][%d] postParserGroupsBadRequest %s", 400, payload)
}

func (o *PostParserGroupsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/groups][%d] postParserGroupsBadRequest %s", 400, payload)
}

func (o *PostParserGroupsBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostParserGroupsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostParserGroupsUnauthorized creates a PostParserGroupsUnauthorized with default headers values
func NewPostParserGroupsUnauthorized() *PostParserGroupsUnauthorized {
	return &PostParserGroupsUnauthorized{}
}

// PostParserGroupsUnauthorized describes a response with status code 401, with default header values.
//
// Unauthorized
type PostParserGroupsUnauthorized struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post parser groups unauthorized response has a 2xx status code
func (o *PostParserGroupsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post parser groups unauthorized response has a 3xx status code
func (o *PostParserGroupsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post parser groups unauthorized response has a 4xx status code
func (o *PostParserGroupsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post parser groups unauthorized response has a 5xx status code
func (o *PostParserGroupsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post parser groups unauthorized response a status code equal to that given
func (o *PostParserGroupsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post parser groups unauthorized response
func (o *PostParserGroupsUnauthorized) Code() int {
	return 401
}

func (o *PostParserGroupsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/groups][%d] postParserGroupsUnauthorized %s", 401, payload)
}

func (o *PostParserGroupsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/groups][%d] postParserGroupsUnauthorized %s", 401, payload)
}

func (o *PostParserGroupsUnauthorized) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostParserGroupsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostParserGroupsInternalServerError creates a PostParserGroupsInternalServerError with default headers values
func NewPostParserGroupsInternalServerError() *PostParserGroupsInternalServerError {
	return &PostParserGroupsInternalServerError{}
}

// PostParserGroupsInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type PostParserGroupsInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post parser groups internal server error response has a 2xx status code
func (o *PostParserGroupsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post parser groups internal server error response has a 3xx status code
func (o *PostParserGroupsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post parser groups internal server error response has a 4xx status code
func (o *PostParserGroupsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post parser groups internal server error response has a 5xx status code
func (o *PostParserGroupsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post parser groups internal server error response a status code equal to that given
func (o *PostParserGroupsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post parser groups internal server error response
func (o *PostParserGroupsInternalServerError) Code() int {
	return 500
}

func (o *PostParserGroupsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/groups][%d] postParserGroupsInternalServerError %s", 500, payload)
}

func (o *PostParserGroupsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /parser/groups][%d] postParserGroupsInternalServerError %s", 500, payload)
}

func (o *PostParserGroupsInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostParserGroupsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
