// Code generated by go-swagger; DO NOT EDIT.

package parser

import (
	"context"
	"net/http"
	"time"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostParserReplacesParams creates a new PostParserReplacesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostParserReplacesParams() *PostParserReplacesParams {
	return NewPostParserReplacesParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostParserReplacesParamsWithTimeout creates a new PostParserReplacesParams object
// with the ability to set a timeout on a request.
func NewPostParserReplacesParamsWithTimeout(timeout time.Duration) *PostParserReplacesParams {
	return &PostParserReplacesParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostParserReplacesParamsWithContext creates a new PostParserReplacesParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostParserReplacesParams].
func NewPostParserReplacesParamsWithContext(ctx context.Context) *PostParserReplacesParams {
	return &PostParserReplacesParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostParserReplacesParamsWithHTTPClient creates a new PostParserReplacesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostParserReplacesParamsWithHTTPClient(client *http.Client) *PostParserReplacesParams {
	return &PostParserReplacesParams{
		HTTPClient: client,
	}
}

/*
PostParserReplacesParams contains all the parameters to send to the API endpoint

	for the post parser replaces operation.

	Typically these are written to a http.Request.
*/
type PostParserReplacesParams struct {

	// Replaces.
	//
	// Replacements
	Replaces []*models.DtoReplace

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post parser replaces params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostParserReplacesParams) WithDefaults() *PostParserReplacesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post parser replaces params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostParserReplacesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post parser replaces params.
func (o *PostParserReplacesParams) WithTimeout(timeout time.Duration) *PostParserReplacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post parser replaces params.
func (o *PostParserReplacesParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post parser replaces params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostParserReplacesParams].
func (o *PostParserReplacesParams) WithContext(ctx context.Context) *PostParserReplacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post parser replaces params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostParserReplacesParams].
func (o *PostParserReplacesParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post parser replaces params.
func (o *PostParserReplacesParams) WithHTTPClient(client *http.Client) *PostParserReplacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post parser replaces params.
func (o *PostParserReplacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReplaces adds the replaces to the post parser replaces params.
func (o *PostParserReplacesParams) WithReplaces(replaces []*models.DtoReplace) *PostParserReplacesParams {
	o.SetReplaces(replaces)
	return o
}

// SetReplaces adds the replaces to the post parser replaces params.
func (o *PostParserReplacesParams) SetReplaces(replaces []*models.DtoReplace) {
	o.Replaces = replaces
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostParserReplacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Replaces != nil {
		if err := r.SetBodyParam(o.Replaces); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
