// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetGroupsIDReader is a Reader for the GetGroupsID structure.
type GetGroupsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGroupsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetGroupsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetGroupsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetGroupsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetGroupsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /groups/{id}] GetGroupsID", response, response.Code())
	}
}

// NewGetGroupsIDOK creates a GetGroupsIDOK with default headers values
func NewGetGroupsIDOK() *GetGroupsIDOK {
	return &GetGroupsIDOK{}
}

// GetGroupsIDOK describes a response with status code 200, with default header values.
//
// OK
type GetGroupsIDOK struct {
	Payload *models.DtoStudentGroupResponse
}

// IsSuccess returns true when this get groups Id o k response has a 2xx status code
func (o *GetGroupsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get groups Id o k response has a 3xx status code
func (o *GetGroupsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get groups Id o k response has a 4xx status code
func (o *GetGroupsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get groups Id o k response has a 5xx status code
func (o *GetGroupsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get groups Id o k response a status code equal to that given
func (o *GetGroupsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get groups Id o k response
func (o *GetGroupsIDOK) Code() int {
	return 200
}

func (o *GetGroupsIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{id}][%d] getGroupsIdOK %s", 200, payload)
}

func (o *GetGroupsIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{id}][%d] getGroupsIdOK %s", 200, payload)
}

func (o *GetGroupsIDOK) GetPayload() *models.DtoStudentGroupResponse {
	return o.Payload
}

func (o *GetGroupsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoStudentGroupResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetGroupsIDBadRequest creates a GetGroupsIDBadRequest with default headers values
func NewGetGroupsIDBadRequest() *GetGroupsIDBadRequest {
	return &GetGroupsIDBadRequest{}
}

// GetGroupsIDBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type GetGroupsIDBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get groups Id bad request response has a 2xx status code
func (o *GetGroupsIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get groups Id bad request response has a 3xx status code
func (o *GetGroupsIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get groups Id bad request response has a 4xx status code
func (o *GetGroupsIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get groups Id bad request response has a 5xx status code
func (o *GetGroupsIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get groups Id bad request response a status code equal to that given
func (o *GetGroupsIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get groups Id bad request response
func (o *GetGroupsIDBadRequest) Code() int {
	return 400
}

func (o *GetGroupsIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{id}][%d] getGroupsIdBadRequest %s", 400, payload)
}

func (o *GetGroupsIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{id}][%d] getGroupsIdBadRequest %s", 400, payload)
}

func (o *GetGroupsIDBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetGroupsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetGroupsIDNotFound creates a GetGroupsIDNotFound with default headers values
func NewGetGroupsIDNotFound() *GetGroupsIDNotFound {
	return &GetGroupsIDNotFound{}
}

// GetGroupsIDNotFound describes a response with status code 404, with default header values.
//
// Not Found
type GetGroupsIDNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get groups Id not found response has a 2xx status code
func (o *GetGroupsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get groups Id not found response has a 3xx status code
func (o *GetGroupsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get groups Id not found response has a 4xx status code
func (o *GetGroupsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get groups Id not found response has a 5xx status code
func (o *GetGroupsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get groups Id not found response a status code equal to that given
func (o *GetGroupsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get groups Id not found response
func (o *GetGroupsIDNotFound) Code() int {
	return 404
}

func (o *GetGroupsIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{id}][%d] getGroupsIdNotFound %s", 404, payload)
}

func (o *GetGroupsIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{id}][%d] getGroupsIdNotFound %s", 404, payload)
}

func (o *GetGroupsIDNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetGroupsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetGroupsIDInternalServerError creates a GetGroupsIDInternalServerError with default headers values
func NewGetGroupsIDInternalServerError() *GetGroupsIDInternalServerError {
	return &GetGroupsIDInternalServerError{}
}

// GetGroupsIDInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type GetGroupsIDInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get groups Id internal server error response has a 2xx status code
func (o *GetGroupsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get groups Id internal server error response has a 3xx status code
func (o *GetGroupsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get groups Id internal server error response has a 4xx status code
func (o *GetGroupsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get groups Id internal server error response has a 5xx status code
func (o *GetGroupsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get groups Id internal server error response a status code equal to that given
func (o *GetGroupsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get groups Id internal server error response
func (o *GetGroupsIDInternalServerError) Code() int {
	return 500
}

func (o *GetGroupsIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{id}][%d] getGroupsIdInternalServerError %s", 500, payload)
}

func (o *GetGroupsIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{id}][%d] getGroupsIdInternalServerError %s", 500, payload)
}

func (o *GetGroupsIDInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetGroupsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
