// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetCollegesCollegeIDGroupsParams creates a new GetCollegesCollegeIDGroupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCollegesCollegeIDGroupsParams() *GetCollegesCollegeIDGroupsParams {
	return NewGetCollegesCollegeIDGroupsParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetCollegesCollegeIDGroupsParamsWithTimeout creates a new GetCollegesCollegeIDGroupsParams object
// with the ability to set a timeout on a request.
func NewGetCollegesCollegeIDGroupsParamsWithTimeout(timeout time.Duration) *GetCollegesCollegeIDGroupsParams {
	return &GetCollegesCollegeIDGroupsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetCollegesCollegeIDGroupsParamsWithContext creates a new GetCollegesCollegeIDGroupsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesCollegeIDGroupsParams].
func NewGetCollegesCollegeIDGroupsParamsWithContext(ctx context.Context) *GetCollegesCollegeIDGroupsParams {
	return &GetCollegesCollegeIDGroupsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetCollegesCollegeIDGroupsParamsWithHTTPClient creates a new GetCollegesCollegeIDGroupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCollegesCollegeIDGroupsParamsWithHTTPClient(client *http.Client) *GetCollegesCollegeIDGroupsParams {
	return &GetCollegesCollegeIDGroupsParams{
		HTTPClient: client,
	}
}

/*
GetCollegesCollegeIDGroupsParams contains all the parameters to send to the API endpoint

	for the get colleges college ID groups operation.

	Typically these are written to a http.Request.
*/
type GetCollegesCollegeIDGroupsParams struct {

	// CollegeID.
	//
	// College ID
	CollegeID int64

	// Name.
	//
	// Group name
	Name *string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get colleges college ID groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollegesCollegeIDGroupsParams) WithDefaults() *GetCollegesCollegeIDGroupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get colleges college ID groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollegesCollegeIDGroupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get colleges college ID groups params.
func (o *GetCollegesCollegeIDGroupsParams) WithTimeout(timeout time.Duration) *GetCollegesCollegeIDGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get colleges college ID groups params.
func (o *GetCollegesCollegeIDGroupsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get colleges college ID groups params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesCollegeIDGroupsParams].
func (o *GetCollegesCollegeIDGroupsParams) WithContext(ctx context.Context) *GetCollegesCollegeIDGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get colleges college ID groups params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesCollegeIDGroupsParams].
func (o *GetCollegesCollegeIDGroupsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get colleges college ID groups params.
func (o *GetCollegesCollegeIDGroupsParams) WithHTTPClient(client *http.Client) *GetCollegesCollegeIDGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get colleges college ID groups params.
func (o *GetCollegesCollegeIDGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCollegeID adds the collegeID to the get colleges college ID groups params.
func (o *GetCollegesCollegeIDGroupsParams) WithCollegeID(collegeID int64) *GetCollegesCollegeIDGroupsParams {
	o.SetCollegeID(collegeID)
	return o
}

// SetCollegeID adds the collegeId to the get colleges college ID groups params.
func (o *GetCollegesCollegeIDGroupsParams) SetCollegeID(collegeID int64) {
	o.CollegeID = collegeID
}

// WithName adds the name to the get colleges college ID groups params.
func (o *GetCollegesCollegeIDGroupsParams) WithName(name *string) *GetCollegesCollegeIDGroupsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get colleges college ID groups params.
func (o *GetCollegesCollegeIDGroupsParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetCollegesCollegeIDGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param collegeId
	if err := r.SetPathParam("collegeId", conv.FormatInteger(o.CollegeID)); err != nil {
		return err
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
