// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetCampusesCampusIDGroupsReader is a Reader for the GetCampusesCampusIDGroups structure.
type GetCampusesCampusIDGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCampusesCampusIDGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCampusesCampusIDGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCampusesCampusIDGroupsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCampusesCampusIDGroupsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCampusesCampusIDGroupsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /campuses/{campusId}/groups] GetCampusesCampusIDGroups", response, response.Code())
	}
}

// NewGetCampusesCampusIDGroupsOK creates a GetCampusesCampusIDGroupsOK with default headers values
func NewGetCampusesCampusIDGroupsOK() *GetCampusesCampusIDGroupsOK {
	return &GetCampusesCampusIDGroupsOK{}
}

// GetCampusesCampusIDGroupsOK describes a response with status code 200, with default header values.
//
// OK
type GetCampusesCampusIDGroupsOK struct {
	Payload []*models.DtoStudentGroupResponse
}

// IsSuccess returns true when this get campuses campus Id groups o k response has a 2xx status code
func (o *GetCampusesCampusIDGroupsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get campuses campus Id groups o k response has a 3xx status code
func (o *GetCampusesCampusIDGroupsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get campuses campus Id groups o k response has a 4xx status code
func (o *GetCampusesCampusIDGroupsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get campuses campus Id groups o k response has a 5xx status code
func (o *GetCampusesCampusIDGroupsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get campuses campus Id groups o k response a status code equal to that given
func (o *GetCampusesCampusIDGroupsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get campuses campus Id groups o k response
func (o *GetCampusesCampusIDGroupsOK) Code() int {
	return 200
}

func (o *GetCampusesCampusIDGroupsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{campusId}/groups][%d] getCampusesCampusIdGroupsOK %s", 200, payload)
}

func (o *GetCampusesCampusIDGroupsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{campusId}/groups][%d] getCampusesCampusIdGroupsOK %s", 200, payload)
}

func (o *GetCampusesCampusIDGroupsOK) GetPayload() []*models.DtoStudentGroupResponse {
	return o.Payload
}

func (o *GetCampusesCampusIDGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCampusesCampusIDGroupsBadRequest creates a GetCampusesCampusIDGroupsBadRequest with default headers values
func NewGetCampusesCampusIDGroupsBadRequest() *GetCampusesCampusIDGroupsBadRequest {
	return &GetCampusesCampusIDGroupsBadRequest{}
}

// GetCampusesCampusIDGroupsBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type GetCampusesCampusIDGroupsBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get campuses campus Id groups bad request response has a 2xx status code
func (o *GetCampusesCampusIDGroupsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get campuses campus Id groups bad request response has a 3xx status code
func (o *GetCampusesCampusIDGroupsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get campuses campus Id groups bad request response has a 4xx status code
func (o *GetCampusesCampusIDGroupsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get campuses campus Id groups bad request response has a 5xx status code
func (o *GetCampusesCampusIDGroupsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get campuses campus Id groups bad request response a status code equal to that given
func (o *GetCampusesCampusIDGroupsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get campuses campus Id groups bad request response
func (o *GetCampusesCampusIDGroupsBadRequest) Code() int {
	return 400
}

func (o *GetCampusesCampusIDGroupsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{campusId}/groups][%d] getCampusesCampusIdGroupsBadRequest %s", 400, payload)
}

func (o *GetCampusesCampusIDGroupsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{campusId}/groups][%d] getCampusesCampusIdGroupsBadRequest %s", 400, payload)
}

func (o *GetCampusesCampusIDGroupsBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCampusesCampusIDGroupsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCampusesCampusIDGroupsNotFound creates a GetCampusesCampusIDGroupsNotFound with default headers values
func NewGetCampusesCampusIDGroupsNotFound() *GetCampusesCampusIDGroupsNotFound {
	return &GetCampusesCampusIDGroupsNotFound{}
}

// GetCampusesCampusIDGroupsNotFound describes a response with status code 404, with default header values.
//
// Not Found
type GetCampusesCampusIDGroupsNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get campuses campus Id groups not found response has a 2xx status code
func (o *GetCampusesCampusIDGroupsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get campuses campus Id groups not found response has a 3xx status code
func (o *GetCampusesCampusIDGroupsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get campuses campus Id groups not found response has a 4xx status code
func (o *GetCampusesCampusIDGroupsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get campuses campus Id groups not found response has a 5xx status code
func (o *GetCampusesCampusIDGroupsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get campuses campus Id groups not found response a status code equal to that given
func (o *GetCampusesCampusIDGroupsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get campuses campus Id groups not found response
func (o *GetCampusesCampusIDGroupsNotFound) Code() int {
	return 404
}

func (o *GetCampusesCampusIDGroupsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{campusId}/groups][%d] getCampusesCampusIdGroupsNotFound %s", 404, payload)
}

func (o *GetCampusesCampusIDGroupsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{campusId}/groups][%d] getCampusesCampusIdGroupsNotFound %s", 404, payload)
}

func (o *GetCampusesCampusIDGroupsNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCampusesCampusIDGroupsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCampusesCampusIDGroupsInternalServerError creates a GetCampusesCampusIDGroupsInternalServerError with default headers values
func NewGetCampusesCampusIDGroupsInternalServerError() *GetCampusesCampusIDGroupsInternalServerError {
	return &GetCampusesCampusIDGroupsInternalServerError{}
}

// GetCampusesCampusIDGroupsInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type GetCampusesCampusIDGroupsInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get campuses campus Id groups internal server error response has a 2xx status code
func (o *GetCampusesCampusIDGroupsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get campuses campus Id groups internal server error response has a 3xx status code
func (o *GetCampusesCampusIDGroupsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get campuses campus Id groups internal server error response has a 4xx status code
func (o *GetCampusesCampusIDGroupsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get campuses campus Id groups internal server error response has a 5xx status code
func (o *GetCampusesCampusIDGroupsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get campuses campus Id groups internal server error response a status code equal to that given
func (o *GetCampusesCampusIDGroupsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get campuses campus Id groups internal server error response
func (o *GetCampusesCampusIDGroupsInternalServerError) Code() int {
	return 500
}

func (o *GetCampusesCampusIDGroupsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{campusId}/groups][%d] getCampusesCampusIdGroupsInternalServerError %s", 500, payload)
}

func (o *GetCampusesCampusIDGroupsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /campuses/{campusId}/groups][%d] getCampusesCampusIdGroupsInternalServerError %s", 500, payload)
}

func (o *GetCampusesCampusIDGroupsInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCampusesCampusIDGroupsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
