// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetGroupsIDParams creates a new GetGroupsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGroupsIDParams() *GetGroupsIDParams {
	return NewGetGroupsIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetGroupsIDParamsWithTimeout creates a new GetGroupsIDParams object
// with the ability to set a timeout on a request.
func NewGetGroupsIDParamsWithTimeout(timeout time.Duration) *GetGroupsIDParams {
	return &GetGroupsIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetGroupsIDParamsWithContext creates a new GetGroupsIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetGroupsIDParams].
func NewGetGroupsIDParamsWithContext(ctx context.Context) *GetGroupsIDParams {
	return &GetGroupsIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetGroupsIDParamsWithHTTPClient creates a new GetGroupsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGroupsIDParamsWithHTTPClient(client *http.Client) *GetGroupsIDParams {
	return &GetGroupsIDParams{
		HTTPClient: client,
	}
}

/*
GetGroupsIDParams contains all the parameters to send to the API endpoint

	for the get groups ID operation.

	Typically these are written to a http.Request.
*/
type GetGroupsIDParams struct {

	// ID.
	//
	// Group ID
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get groups ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupsIDParams) WithDefaults() *GetGroupsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get groups ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get groups ID params.
func (o *GetGroupsIDParams) WithTimeout(timeout time.Duration) *GetGroupsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get groups ID params.
func (o *GetGroupsIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get groups ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetGroupsIDParams].
func (o *GetGroupsIDParams) WithContext(ctx context.Context) *GetGroupsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get groups ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetGroupsIDParams].
func (o *GetGroupsIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get groups ID params.
func (o *GetGroupsIDParams) WithHTTPClient(client *http.Client) *GetGroupsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get groups ID params.
func (o *GetGroupsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get groups ID params.
func (o *GetGroupsIDParams) WithID(id int64) *GetGroupsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get groups ID params.
func (o *GetGroupsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetGroupsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
