// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetGroupsIDSchedulesLastParams creates a new GetGroupsIDSchedulesLastParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGroupsIDSchedulesLastParams() *GetGroupsIDSchedulesLastParams {
	return NewGetGroupsIDSchedulesLastParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetGroupsIDSchedulesLastParamsWithTimeout creates a new GetGroupsIDSchedulesLastParams object
// with the ability to set a timeout on a request.
func NewGetGroupsIDSchedulesLastParamsWithTimeout(timeout time.Duration) *GetGroupsIDSchedulesLastParams {
	return &GetGroupsIDSchedulesLastParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetGroupsIDSchedulesLastParamsWithContext creates a new GetGroupsIDSchedulesLastParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetGroupsIDSchedulesLastParams].
func NewGetGroupsIDSchedulesLastParamsWithContext(ctx context.Context) *GetGroupsIDSchedulesLastParams {
	return &GetGroupsIDSchedulesLastParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetGroupsIDSchedulesLastParamsWithHTTPClient creates a new GetGroupsIDSchedulesLastParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGroupsIDSchedulesLastParamsWithHTTPClient(client *http.Client) *GetGroupsIDSchedulesLastParams {
	return &GetGroupsIDSchedulesLastParams{
		HTTPClient: client,
	}
}

/*
GetGroupsIDSchedulesLastParams contains all the parameters to send to the API endpoint

	for the get groups ID schedules last operation.

	Typically these are written to a http.Request.
*/
type GetGroupsIDSchedulesLastParams struct {

	// ID.
	//
	// Group ID
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get groups ID schedules last params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupsIDSchedulesLastParams) WithDefaults() *GetGroupsIDSchedulesLastParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get groups ID schedules last params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupsIDSchedulesLastParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get groups ID schedules last params.
func (o *GetGroupsIDSchedulesLastParams) WithTimeout(timeout time.Duration) *GetGroupsIDSchedulesLastParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get groups ID schedules last params.
func (o *GetGroupsIDSchedulesLastParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get groups ID schedules last params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetGroupsIDSchedulesLastParams].
func (o *GetGroupsIDSchedulesLastParams) WithContext(ctx context.Context) *GetGroupsIDSchedulesLastParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get groups ID schedules last params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetGroupsIDSchedulesLastParams].
func (o *GetGroupsIDSchedulesLastParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get groups ID schedules last params.
func (o *GetGroupsIDSchedulesLastParams) WithHTTPClient(client *http.Client) *GetGroupsIDSchedulesLastParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get groups ID schedules last params.
func (o *GetGroupsIDSchedulesLastParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get groups ID schedules last params.
func (o *GetGroupsIDSchedulesLastParams) WithID(id int64) *GetGroupsIDSchedulesLastParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get groups ID schedules last params.
func (o *GetGroupsIDSchedulesLastParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetGroupsIDSchedulesLastParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
