// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetGroupsIDSchedulesLastReader is a Reader for the GetGroupsIDSchedulesLast structure.
type GetGroupsIDSchedulesLastReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGroupsIDSchedulesLastReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetGroupsIDSchedulesLastOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetGroupsIDSchedulesLastBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetGroupsIDSchedulesLastNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetGroupsIDSchedulesLastInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /groups/{id}/schedules/last] GetGroupsIDSchedulesLast", response, response.Code())
	}
}

// NewGetGroupsIDSchedulesLastOK creates a GetGroupsIDSchedulesLastOK with default headers values
func NewGetGroupsIDSchedulesLastOK() *GetGroupsIDSchedulesLastOK {
	return &GetGroupsIDSchedulesLastOK{}
}

// GetGroupsIDSchedulesLastOK describes a response with status code 200, with default header values.
//
// OK
type GetGroupsIDSchedulesLastOK struct {
	Payload *models.DtoDateResponse
}

// IsSuccess returns true when this get groups Id schedules last o k response has a 2xx status code
func (o *GetGroupsIDSchedulesLastOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get groups Id schedules last o k response has a 3xx status code
func (o *GetGroupsIDSchedulesLastOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get groups Id schedules last o k response has a 4xx status code
func (o *GetGroupsIDSchedulesLastOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get groups Id schedules last o k response has a 5xx status code
func (o *GetGroupsIDSchedulesLastOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get groups Id schedules last o k response a status code equal to that given
func (o *GetGroupsIDSchedulesLastOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get groups Id schedules last o k response
func (o *GetGroupsIDSchedulesLastOK) Code() int {
	return 200
}

func (o *GetGroupsIDSchedulesLastOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{id}/schedules/last][%d] getGroupsIdSchedulesLastOK %s", 200, payload)
}

func (o *GetGroupsIDSchedulesLastOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{id}/schedules/last][%d] getGroupsIdSchedulesLastOK %s", 200, payload)
}

func (o *GetGroupsIDSchedulesLastOK) GetPayload() *models.DtoDateResponse {
	return o.Payload
}

func (o *GetGroupsIDSchedulesLastOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoDateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetGroupsIDSchedulesLastBadRequest creates a GetGroupsIDSchedulesLastBadRequest with default headers values
func NewGetGroupsIDSchedulesLastBadRequest() *GetGroupsIDSchedulesLastBadRequest {
	return &GetGroupsIDSchedulesLastBadRequest{}
}

// GetGroupsIDSchedulesLastBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type GetGroupsIDSchedulesLastBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get groups Id schedules last bad request response has a 2xx status code
func (o *GetGroupsIDSchedulesLastBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get groups Id schedules last bad request response has a 3xx status code
func (o *GetGroupsIDSchedulesLastBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get groups Id schedules last bad request response has a 4xx status code
func (o *GetGroupsIDSchedulesLastBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get groups Id schedules last bad request response has a 5xx status code
func (o *GetGroupsIDSchedulesLastBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get groups Id schedules last bad request response a status code equal to that given
func (o *GetGroupsIDSchedulesLastBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get groups Id schedules last bad request response
func (o *GetGroupsIDSchedulesLastBadRequest) Code() int {
	return 400
}

func (o *GetGroupsIDSchedulesLastBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{id}/schedules/last][%d] getGroupsIdSchedulesLastBadRequest %s", 400, payload)
}

func (o *GetGroupsIDSchedulesLastBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{id}/schedules/last][%d] getGroupsIdSchedulesLastBadRequest %s", 400, payload)
}

func (o *GetGroupsIDSchedulesLastBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetGroupsIDSchedulesLastBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetGroupsIDSchedulesLastNotFound creates a GetGroupsIDSchedulesLastNotFound with default headers values
func NewGetGroupsIDSchedulesLastNotFound() *GetGroupsIDSchedulesLastNotFound {
	return &GetGroupsIDSchedulesLastNotFound{}
}

// GetGroupsIDSchedulesLastNotFound describes a response with status code 404, with default header values.
//
// Not Found
type GetGroupsIDSchedulesLastNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get groups Id schedules last not found response has a 2xx status code
func (o *GetGroupsIDSchedulesLastNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get groups Id schedules last not found response has a 3xx status code
func (o *GetGroupsIDSchedulesLastNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get groups Id schedules last not found response has a 4xx status code
func (o *GetGroupsIDSchedulesLastNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get groups Id schedules last not found response has a 5xx status code
func (o *GetGroupsIDSchedulesLastNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get groups Id schedules last not found response a status code equal to that given
func (o *GetGroupsIDSchedulesLastNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get groups Id schedules last not found response
func (o *GetGroupsIDSchedulesLastNotFound) Code() int {
	return 404
}

func (o *GetGroupsIDSchedulesLastNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{id}/schedules/last][%d] getGroupsIdSchedulesLastNotFound %s", 404, payload)
}

func (o *GetGroupsIDSchedulesLastNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{id}/schedules/last][%d] getGroupsIdSchedulesLastNotFound %s", 404, payload)
}

func (o *GetGroupsIDSchedulesLastNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetGroupsIDSchedulesLastNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetGroupsIDSchedulesLastInternalServerError creates a GetGroupsIDSchedulesLastInternalServerError with default headers values
func NewGetGroupsIDSchedulesLastInternalServerError() *GetGroupsIDSchedulesLastInternalServerError {
	return &GetGroupsIDSchedulesLastInternalServerError{}
}

// GetGroupsIDSchedulesLastInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type GetGroupsIDSchedulesLastInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get groups Id schedules last internal server error response has a 2xx status code
func (o *GetGroupsIDSchedulesLastInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get groups Id schedules last internal server error response has a 3xx status code
func (o *GetGroupsIDSchedulesLastInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get groups Id schedules last internal server error response has a 4xx status code
func (o *GetGroupsIDSchedulesLastInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get groups Id schedules last internal server error response has a 5xx status code
func (o *GetGroupsIDSchedulesLastInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get groups Id schedules last internal server error response a status code equal to that given
func (o *GetGroupsIDSchedulesLastInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get groups Id schedules last internal server error response
func (o *GetGroupsIDSchedulesLastInternalServerError) Code() int {
	return 500
}

func (o *GetGroupsIDSchedulesLastInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{id}/schedules/last][%d] getGroupsIdSchedulesLastInternalServerError %s", 500, payload)
}

func (o *GetGroupsIDSchedulesLastInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /groups/{id}/schedules/last][%d] getGroupsIdSchedulesLastInternalServerError %s", 500, payload)
}

func (o *GetGroupsIDSchedulesLastInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetGroupsIDSchedulesLastInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
