// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetCollegesCollegeIDGroupsReader is a Reader for the GetCollegesCollegeIDGroups structure.
type GetCollegesCollegeIDGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCollegesCollegeIDGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCollegesCollegeIDGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCollegesCollegeIDGroupsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCollegesCollegeIDGroupsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCollegesCollegeIDGroupsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /colleges/{collegeId}/groups] GetCollegesCollegeIDGroups", response, response.Code())
	}
}

// NewGetCollegesCollegeIDGroupsOK creates a GetCollegesCollegeIDGroupsOK with default headers values
func NewGetCollegesCollegeIDGroupsOK() *GetCollegesCollegeIDGroupsOK {
	return &GetCollegesCollegeIDGroupsOK{}
}

// GetCollegesCollegeIDGroupsOK describes a response with status code 200, with default header values.
//
// OK
type GetCollegesCollegeIDGroupsOK struct {
	Payload []*models.DtoStudentGroupResponse
}

// IsSuccess returns true when this get colleges college Id groups o k response has a 2xx status code
func (o *GetCollegesCollegeIDGroupsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get colleges college Id groups o k response has a 3xx status code
func (o *GetCollegesCollegeIDGroupsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges college Id groups o k response has a 4xx status code
func (o *GetCollegesCollegeIDGroupsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get colleges college Id groups o k response has a 5xx status code
func (o *GetCollegesCollegeIDGroupsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get colleges college Id groups o k response a status code equal to that given
func (o *GetCollegesCollegeIDGroupsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get colleges college Id groups o k response
func (o *GetCollegesCollegeIDGroupsOK) Code() int {
	return 200
}

func (o *GetCollegesCollegeIDGroupsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/groups][%d] getCollegesCollegeIdGroupsOK %s", 200, payload)
}

func (o *GetCollegesCollegeIDGroupsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/groups][%d] getCollegesCollegeIdGroupsOK %s", 200, payload)
}

func (o *GetCollegesCollegeIDGroupsOK) GetPayload() []*models.DtoStudentGroupResponse {
	return o.Payload
}

func (o *GetCollegesCollegeIDGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCollegesCollegeIDGroupsBadRequest creates a GetCollegesCollegeIDGroupsBadRequest with default headers values
func NewGetCollegesCollegeIDGroupsBadRequest() *GetCollegesCollegeIDGroupsBadRequest {
	return &GetCollegesCollegeIDGroupsBadRequest{}
}

// GetCollegesCollegeIDGroupsBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type GetCollegesCollegeIDGroupsBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get colleges college Id groups bad request response has a 2xx status code
func (o *GetCollegesCollegeIDGroupsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get colleges college Id groups bad request response has a 3xx status code
func (o *GetCollegesCollegeIDGroupsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges college Id groups bad request response has a 4xx status code
func (o *GetCollegesCollegeIDGroupsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get colleges college Id groups bad request response has a 5xx status code
func (o *GetCollegesCollegeIDGroupsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get colleges college Id groups bad request response a status code equal to that given
func (o *GetCollegesCollegeIDGroupsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get colleges college Id groups bad request response
func (o *GetCollegesCollegeIDGroupsBadRequest) Code() int {
	return 400
}

func (o *GetCollegesCollegeIDGroupsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/groups][%d] getCollegesCollegeIdGroupsBadRequest %s", 400, payload)
}

func (o *GetCollegesCollegeIDGroupsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/groups][%d] getCollegesCollegeIdGroupsBadRequest %s", 400, payload)
}

func (o *GetCollegesCollegeIDGroupsBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCollegesCollegeIDGroupsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCollegesCollegeIDGroupsNotFound creates a GetCollegesCollegeIDGroupsNotFound with default headers values
func NewGetCollegesCollegeIDGroupsNotFound() *GetCollegesCollegeIDGroupsNotFound {
	return &GetCollegesCollegeIDGroupsNotFound{}
}

// GetCollegesCollegeIDGroupsNotFound describes a response with status code 404, with default header values.
//
// Not Found
type GetCollegesCollegeIDGroupsNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get colleges college Id groups not found response has a 2xx status code
func (o *GetCollegesCollegeIDGroupsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get colleges college Id groups not found response has a 3xx status code
func (o *GetCollegesCollegeIDGroupsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges college Id groups not found response has a 4xx status code
func (o *GetCollegesCollegeIDGroupsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get colleges college Id groups not found response has a 5xx status code
func (o *GetCollegesCollegeIDGroupsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get colleges college Id groups not found response a status code equal to that given
func (o *GetCollegesCollegeIDGroupsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get colleges college Id groups not found response
func (o *GetCollegesCollegeIDGroupsNotFound) Code() int {
	return 404
}

func (o *GetCollegesCollegeIDGroupsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/groups][%d] getCollegesCollegeIdGroupsNotFound %s", 404, payload)
}

func (o *GetCollegesCollegeIDGroupsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/groups][%d] getCollegesCollegeIdGroupsNotFound %s", 404, payload)
}

func (o *GetCollegesCollegeIDGroupsNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCollegesCollegeIDGroupsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCollegesCollegeIDGroupsInternalServerError creates a GetCollegesCollegeIDGroupsInternalServerError with default headers values
func NewGetCollegesCollegeIDGroupsInternalServerError() *GetCollegesCollegeIDGroupsInternalServerError {
	return &GetCollegesCollegeIDGroupsInternalServerError{}
}

// GetCollegesCollegeIDGroupsInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type GetCollegesCollegeIDGroupsInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get colleges college Id groups internal server error response has a 2xx status code
func (o *GetCollegesCollegeIDGroupsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get colleges college Id groups internal server error response has a 3xx status code
func (o *GetCollegesCollegeIDGroupsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges college Id groups internal server error response has a 4xx status code
func (o *GetCollegesCollegeIDGroupsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get colleges college Id groups internal server error response has a 5xx status code
func (o *GetCollegesCollegeIDGroupsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get colleges college Id groups internal server error response a status code equal to that given
func (o *GetCollegesCollegeIDGroupsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get colleges college Id groups internal server error response
func (o *GetCollegesCollegeIDGroupsInternalServerError) Code() int {
	return 500
}

func (o *GetCollegesCollegeIDGroupsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/groups][%d] getCollegesCollegeIdGroupsInternalServerError %s", 500, payload)
}

func (o *GetCollegesCollegeIDGroupsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{collegeId}/groups][%d] getCollegesCollegeIdGroupsInternalServerError %s", 500, payload)
}

func (o *GetCollegesCollegeIDGroupsInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCollegesCollegeIDGroupsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
