// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetCampusesCampusIDGroupsParams creates a new GetCampusesCampusIDGroupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCampusesCampusIDGroupsParams() *GetCampusesCampusIDGroupsParams {
	return NewGetCampusesCampusIDGroupsParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetCampusesCampusIDGroupsParamsWithTimeout creates a new GetCampusesCampusIDGroupsParams object
// with the ability to set a timeout on a request.
func NewGetCampusesCampusIDGroupsParamsWithTimeout(timeout time.Duration) *GetCampusesCampusIDGroupsParams {
	return &GetCampusesCampusIDGroupsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetCampusesCampusIDGroupsParamsWithContext creates a new GetCampusesCampusIDGroupsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCampusesCampusIDGroupsParams].
func NewGetCampusesCampusIDGroupsParamsWithContext(ctx context.Context) *GetCampusesCampusIDGroupsParams {
	return &GetCampusesCampusIDGroupsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetCampusesCampusIDGroupsParamsWithHTTPClient creates a new GetCampusesCampusIDGroupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCampusesCampusIDGroupsParamsWithHTTPClient(client *http.Client) *GetCampusesCampusIDGroupsParams {
	return &GetCampusesCampusIDGroupsParams{
		HTTPClient: client,
	}
}

/*
GetCampusesCampusIDGroupsParams contains all the parameters to send to the API endpoint

	for the get campuses campus ID groups operation.

	Typically these are written to a http.Request.
*/
type GetCampusesCampusIDGroupsParams struct {

	// CampusID.
	//
	// Campus ID
	CampusID int64

	// Name.
	//
	// Group name
	Name *string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get campuses campus ID groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCampusesCampusIDGroupsParams) WithDefaults() *GetCampusesCampusIDGroupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get campuses campus ID groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCampusesCampusIDGroupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get campuses campus ID groups params.
func (o *GetCampusesCampusIDGroupsParams) WithTimeout(timeout time.Duration) *GetCampusesCampusIDGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get campuses campus ID groups params.
func (o *GetCampusesCampusIDGroupsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get campuses campus ID groups params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCampusesCampusIDGroupsParams].
func (o *GetCampusesCampusIDGroupsParams) WithContext(ctx context.Context) *GetCampusesCampusIDGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get campuses campus ID groups params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCampusesCampusIDGroupsParams].
func (o *GetCampusesCampusIDGroupsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get campuses campus ID groups params.
func (o *GetCampusesCampusIDGroupsParams) WithHTTPClient(client *http.Client) *GetCampusesCampusIDGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get campuses campus ID groups params.
func (o *GetCampusesCampusIDGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCampusID adds the campusID to the get campuses campus ID groups params.
func (o *GetCampusesCampusIDGroupsParams) WithCampusID(campusID int64) *GetCampusesCampusIDGroupsParams {
	o.SetCampusID(campusID)
	return o
}

// SetCampusID adds the campusId to the get campuses campus ID groups params.
func (o *GetCampusesCampusIDGroupsParams) SetCampusID(campusID int64) {
	o.CampusID = campusID
}

// WithName adds the name to the get campuses campus ID groups params.
func (o *GetCampusesCampusIDGroupsParams) WithName(name *string) *GetCampusesCampusIDGroupsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get campuses campus ID groups params.
func (o *GetCampusesCampusIDGroupsParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetCampusesCampusIDGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param campusId
	if err := r.SetPathParam("campusId", conv.FormatInteger(o.CampusID)); err != nil {
		return err
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
