// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new groups API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new groups API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new groups API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

// Client for groups API.
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// GetCampusesCampusIDGroups get groups by campus ID.
	GetCampusesCampusIDGroups(params *GetCampusesCampusIDGroupsParams, opts ...ClientOption) (*GetCampusesCampusIDGroupsOK, error)

	// GetCampusesCampusIDGroupsContext get groups by campus ID.
	GetCampusesCampusIDGroupsContext(ctx context.Context, params *GetCampusesCampusIDGroupsParams, opts ...ClientOption) (*GetCampusesCampusIDGroupsOK, error)

	// GetCollegesCollegeIDGroups get groups by college ID.
	GetCollegesCollegeIDGroups(params *GetCollegesCollegeIDGroupsParams, opts ...ClientOption) (*GetCollegesCollegeIDGroupsOK, error)

	// GetCollegesCollegeIDGroupsContext get groups by college ID.
	GetCollegesCollegeIDGroupsContext(ctx context.Context, params *GetCollegesCollegeIDGroupsParams, opts ...ClientOption) (*GetCollegesCollegeIDGroupsOK, error)

	// GetGroupsID get a group by ID.
	GetGroupsID(params *GetGroupsIDParams, opts ...ClientOption) (*GetGroupsIDOK, error)

	// GetGroupsIDContext get a group by ID.
	GetGroupsIDContext(ctx context.Context, params *GetGroupsIDParams, opts ...ClientOption) (*GetGroupsIDOK, error)

	// GetGroupsIDSchedulesLast get last lesson date.
	GetGroupsIDSchedulesLast(params *GetGroupsIDSchedulesLastParams, opts ...ClientOption) (*GetGroupsIDSchedulesLastOK, error)

	// GetGroupsIDSchedulesLastContext get last lesson date.
	GetGroupsIDSchedulesLastContext(ctx context.Context, params *GetGroupsIDSchedulesLastParams, opts ...ClientOption) (*GetGroupsIDSchedulesLastOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

// GetCampusesCampusIDGroups gets groups by campus ID.
//
// get all groups by campus ID or a group by campus ID with specified name.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetCampusesCampusIDGroupsContext] instead.
func (a *Client) GetCampusesCampusIDGroups(params *GetCampusesCampusIDGroupsParams, opts ...ClientOption) (*GetCampusesCampusIDGroupsOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetCampusesCampusIDGroupsContext(ctx, params, opts...)
}

// GetCampusesCampusIDGroupsContext gets groups by campus ID.
//
// get all groups by campus ID or a group by campus ID with specified name.
//
// Do not use the deprecated [GetCampusesCampusIDGroupsParams.Context] with this method: it would be ignored.
func (a *Client) GetCampusesCampusIDGroupsContext(ctx context.Context, params *GetCampusesCampusIDGroupsParams, opts ...ClientOption) (*GetCampusesCampusIDGroupsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetCampusesCampusIDGroupsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetCampusesCampusIDGroups",
		Method:             "GET",
		PathPattern:        "/campuses/{campusId}/groups",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCampusesCampusIDGroupsReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetCampusesCampusIDGroupsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCampusesCampusIDGroups: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetCollegesCollegeIDGroups gets groups by college ID.
//
// get all groups by college ID or a group by college ID with specified name.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetCollegesCollegeIDGroupsContext] instead.
func (a *Client) GetCollegesCollegeIDGroups(params *GetCollegesCollegeIDGroupsParams, opts ...ClientOption) (*GetCollegesCollegeIDGroupsOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetCollegesCollegeIDGroupsContext(ctx, params, opts...)
}

// GetCollegesCollegeIDGroupsContext gets groups by college ID.
//
// get all groups by college ID or a group by college ID with specified name.
//
// Do not use the deprecated [GetCollegesCollegeIDGroupsParams.Context] with this method: it would be ignored.
func (a *Client) GetCollegesCollegeIDGroupsContext(ctx context.Context, params *GetCollegesCollegeIDGroupsParams, opts ...ClientOption) (*GetCollegesCollegeIDGroupsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetCollegesCollegeIDGroupsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetCollegesCollegeIDGroups",
		Method:             "GET",
		PathPattern:        "/colleges/{collegeId}/groups",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCollegesCollegeIDGroupsReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetCollegesCollegeIDGroupsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCollegesCollegeIDGroups: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetGroupsID gets a group by ID.
//
// get a single group by its ID.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetGroupsIDContext] instead.
func (a *Client) GetGroupsID(params *GetGroupsIDParams, opts ...ClientOption) (*GetGroupsIDOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetGroupsIDContext(ctx, params, opts...)
}

// GetGroupsIDContext gets a group by ID.
//
// get a single group by its ID.
//
// Do not use the deprecated [GetGroupsIDParams.Context] with this method: it would be ignored.
func (a *Client) GetGroupsIDContext(ctx context.Context, params *GetGroupsIDParams, opts ...ClientOption) (*GetGroupsIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetGroupsIDParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetGroupsID",
		Method:             "GET",
		PathPattern:        "/groups/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetGroupsIDReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetGroupsIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetGroupsID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetGroupsIDSchedulesLast gets last lesson date.
//
// get the last lesson date by group ID.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetGroupsIDSchedulesLastContext] instead.
func (a *Client) GetGroupsIDSchedulesLast(params *GetGroupsIDSchedulesLastParams, opts ...ClientOption) (*GetGroupsIDSchedulesLastOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetGroupsIDSchedulesLastContext(ctx, params, opts...)
}

// GetGroupsIDSchedulesLastContext gets last lesson date.
//
// get the last lesson date by group ID.
//
// Do not use the deprecated [GetGroupsIDSchedulesLastParams.Context] with this method: it would be ignored.
func (a *Client) GetGroupsIDSchedulesLastContext(ctx context.Context, params *GetGroupsIDSchedulesLastParams, opts ...ClientOption) (*GetGroupsIDSchedulesLastOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetGroupsIDSchedulesLastParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetGroupsIDSchedulesLast",
		Method:             "GET",
		PathPattern:        "/groups/{id}/schedules/last",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetGroupsIDSchedulesLastReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetGroupsIDSchedulesLastOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetGroupsIDSchedulesLast: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [GroupsParams].
	ctx context.Context
}
