// Code generated by go-swagger; DO NOT EDIT.

package colleges

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new colleges API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new colleges API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new colleges API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

// Client for colleges API.
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// GetColleges get colleges.
	GetColleges(params *GetCollegesParams, opts ...ClientOption) (*GetCollegesOK, error)

	// GetCollegesContext get colleges.
	GetCollegesContext(ctx context.Context, params *GetCollegesParams, opts ...ClientOption) (*GetCollegesOK, error)

	// GetCollegesID get a college by ID.
	GetCollegesID(params *GetCollegesIDParams, opts ...ClientOption) (*GetCollegesIDOK, error)

	// GetCollegesIDContext get a college by ID.
	GetCollegesIDContext(ctx context.Context, params *GetCollegesIDParams, opts ...ClientOption) (*GetCollegesIDOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

// GetColleges gets colleges.
//
// get all colleges or a college with specified name.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetCollegesContext] instead.
func (a *Client) GetColleges(params *GetCollegesParams, opts ...ClientOption) (*GetCollegesOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetCollegesContext(ctx, params, opts...)
}

// GetCollegesContext gets colleges.
//
// get all colleges or a college with specified name.
//
// Do not use the deprecated [GetCollegesParams.Context] with this method: it would be ignored.
func (a *Client) GetCollegesContext(ctx context.Context, params *GetCollegesParams, opts ...ClientOption) (*GetCollegesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetCollegesParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetColleges",
		Method:             "GET",
		PathPattern:        "/colleges",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCollegesReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetCollegesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetColleges: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// GetCollegesID gets a college by ID.
//
// get a single college by its ID.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.GetCollegesIDContext] instead.
func (a *Client) GetCollegesID(params *GetCollegesIDParams, opts ...ClientOption) (*GetCollegesIDOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetCollegesIDContext(ctx, params, opts...)
}

// GetCollegesIDContext gets a college by ID.
//
// get a single college by its ID.
//
// Do not use the deprecated [GetCollegesIDParams.Context] with this method: it would be ignored.
func (a *Client) GetCollegesIDContext(ctx context.Context, params *GetCollegesIDParams, opts ...ClientOption) (*GetCollegesIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetCollegesIDParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetCollegesID",
		Method:             "GET",
		PathPattern:        "/colleges/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCollegesIDReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetCollegesIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCollegesID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [CollegesParams].
	ctx context.Context
}
