// Code generated by go-swagger; DO NOT EDIT.

package colleges

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetCollegesIDSchedulesLastParams creates a new GetCollegesIDSchedulesLastParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCollegesIDSchedulesLastParams() *GetCollegesIDSchedulesLastParams {
	return NewGetCollegesIDSchedulesLastParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetCollegesIDSchedulesLastParamsWithTimeout creates a new GetCollegesIDSchedulesLastParams object
// with the ability to set a timeout on a request.
func NewGetCollegesIDSchedulesLastParamsWithTimeout(timeout time.Duration) *GetCollegesIDSchedulesLastParams {
	return &GetCollegesIDSchedulesLastParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetCollegesIDSchedulesLastParamsWithContext creates a new GetCollegesIDSchedulesLastParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesIDSchedulesLastParams].
func NewGetCollegesIDSchedulesLastParamsWithContext(ctx context.Context) *GetCollegesIDSchedulesLastParams {
	return &GetCollegesIDSchedulesLastParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetCollegesIDSchedulesLastParamsWithHTTPClient creates a new GetCollegesIDSchedulesLastParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCollegesIDSchedulesLastParamsWithHTTPClient(client *http.Client) *GetCollegesIDSchedulesLastParams {
	return &GetCollegesIDSchedulesLastParams{
		HTTPClient: client,
	}
}

/*
GetCollegesIDSchedulesLastParams contains all the parameters to send to the API endpoint

	for the get colleges ID schedules last operation.

	Typically these are written to a http.Request.
*/
type GetCollegesIDSchedulesLastParams struct {

	// ID.
	//
	// College ID
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get colleges ID schedules last params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollegesIDSchedulesLastParams) WithDefaults() *GetCollegesIDSchedulesLastParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get colleges ID schedules last params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollegesIDSchedulesLastParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get colleges ID schedules last params.
func (o *GetCollegesIDSchedulesLastParams) WithTimeout(timeout time.Duration) *GetCollegesIDSchedulesLastParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get colleges ID schedules last params.
func (o *GetCollegesIDSchedulesLastParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get colleges ID schedules last params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesIDSchedulesLastParams].
func (o *GetCollegesIDSchedulesLastParams) WithContext(ctx context.Context) *GetCollegesIDSchedulesLastParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get colleges ID schedules last params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesIDSchedulesLastParams].
func (o *GetCollegesIDSchedulesLastParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get colleges ID schedules last params.
func (o *GetCollegesIDSchedulesLastParams) WithHTTPClient(client *http.Client) *GetCollegesIDSchedulesLastParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get colleges ID schedules last params.
func (o *GetCollegesIDSchedulesLastParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get colleges ID schedules last params.
func (o *GetCollegesIDSchedulesLastParams) WithID(id int64) *GetCollegesIDSchedulesLastParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get colleges ID schedules last params.
func (o *GetCollegesIDSchedulesLastParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetCollegesIDSchedulesLastParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
