// Code generated by go-swagger; DO NOT EDIT.

package colleges

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetCollegesReader is a Reader for the GetColleges structure.
type GetCollegesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCollegesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCollegesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetCollegesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /colleges] GetColleges", response, response.Code())
	}
}

// NewGetCollegesOK creates a GetCollegesOK with default headers values
func NewGetCollegesOK() *GetCollegesOK {
	return &GetCollegesOK{}
}

// GetCollegesOK describes a response with status code 200, with default header values.
//
// OK
type GetCollegesOK struct {
	Payload []*models.DtoCollegeResponse
}

// IsSuccess returns true when this get colleges o k response has a 2xx status code
func (o *GetCollegesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get colleges o k response has a 3xx status code
func (o *GetCollegesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges o k response has a 4xx status code
func (o *GetCollegesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get colleges o k response has a 5xx status code
func (o *GetCollegesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get colleges o k response a status code equal to that given
func (o *GetCollegesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get colleges o k response
func (o *GetCollegesOK) Code() int {
	return 200
}

func (o *GetCollegesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges][%d] getCollegesOK %s", 200, payload)
}

func (o *GetCollegesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges][%d] getCollegesOK %s", 200, payload)
}

func (o *GetCollegesOK) GetPayload() []*models.DtoCollegeResponse {
	return o.Payload
}

func (o *GetCollegesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCollegesInternalServerError creates a GetCollegesInternalServerError with default headers values
func NewGetCollegesInternalServerError() *GetCollegesInternalServerError {
	return &GetCollegesInternalServerError{}
}

// GetCollegesInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type GetCollegesInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get colleges internal server error response has a 2xx status code
func (o *GetCollegesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get colleges internal server error response has a 3xx status code
func (o *GetCollegesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges internal server error response has a 4xx status code
func (o *GetCollegesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get colleges internal server error response has a 5xx status code
func (o *GetCollegesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get colleges internal server error response a status code equal to that given
func (o *GetCollegesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get colleges internal server error response
func (o *GetCollegesInternalServerError) Code() int {
	return 500
}

func (o *GetCollegesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges][%d] getCollegesInternalServerError %s", 500, payload)
}

func (o *GetCollegesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges][%d] getCollegesInternalServerError %s", 500, payload)
}

func (o *GetCollegesInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCollegesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
