// Code generated by go-swagger; DO NOT EDIT.

package colleges

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetCollegesIDReader is a Reader for the GetCollegesID structure.
type GetCollegesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCollegesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCollegesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCollegesIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCollegesIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCollegesIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /colleges/{id}] GetCollegesID", response, response.Code())
	}
}

// NewGetCollegesIDOK creates a GetCollegesIDOK with default headers values
func NewGetCollegesIDOK() *GetCollegesIDOK {
	return &GetCollegesIDOK{}
}

// GetCollegesIDOK describes a response with status code 200, with default header values.
//
// OK
type GetCollegesIDOK struct {
	Payload *models.DtoCollegeResponse
}

// IsSuccess returns true when this get colleges Id o k response has a 2xx status code
func (o *GetCollegesIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get colleges Id o k response has a 3xx status code
func (o *GetCollegesIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges Id o k response has a 4xx status code
func (o *GetCollegesIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get colleges Id o k response has a 5xx status code
func (o *GetCollegesIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get colleges Id o k response a status code equal to that given
func (o *GetCollegesIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get colleges Id o k response
func (o *GetCollegesIDOK) Code() int {
	return 200
}

func (o *GetCollegesIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{id}][%d] getCollegesIdOK %s", 200, payload)
}

func (o *GetCollegesIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{id}][%d] getCollegesIdOK %s", 200, payload)
}

func (o *GetCollegesIDOK) GetPayload() *models.DtoCollegeResponse {
	return o.Payload
}

func (o *GetCollegesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoCollegeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCollegesIDBadRequest creates a GetCollegesIDBadRequest with default headers values
func NewGetCollegesIDBadRequest() *GetCollegesIDBadRequest {
	return &GetCollegesIDBadRequest{}
}

// GetCollegesIDBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type GetCollegesIDBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get colleges Id bad request response has a 2xx status code
func (o *GetCollegesIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get colleges Id bad request response has a 3xx status code
func (o *GetCollegesIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges Id bad request response has a 4xx status code
func (o *GetCollegesIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get colleges Id bad request response has a 5xx status code
func (o *GetCollegesIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get colleges Id bad request response a status code equal to that given
func (o *GetCollegesIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get colleges Id bad request response
func (o *GetCollegesIDBadRequest) Code() int {
	return 400
}

func (o *GetCollegesIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{id}][%d] getCollegesIdBadRequest %s", 400, payload)
}

func (o *GetCollegesIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{id}][%d] getCollegesIdBadRequest %s", 400, payload)
}

func (o *GetCollegesIDBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCollegesIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCollegesIDNotFound creates a GetCollegesIDNotFound with default headers values
func NewGetCollegesIDNotFound() *GetCollegesIDNotFound {
	return &GetCollegesIDNotFound{}
}

// GetCollegesIDNotFound describes a response with status code 404, with default header values.
//
// Not Found
type GetCollegesIDNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get colleges Id not found response has a 2xx status code
func (o *GetCollegesIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get colleges Id not found response has a 3xx status code
func (o *GetCollegesIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges Id not found response has a 4xx status code
func (o *GetCollegesIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get colleges Id not found response has a 5xx status code
func (o *GetCollegesIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get colleges Id not found response a status code equal to that given
func (o *GetCollegesIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get colleges Id not found response
func (o *GetCollegesIDNotFound) Code() int {
	return 404
}

func (o *GetCollegesIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{id}][%d] getCollegesIdNotFound %s", 404, payload)
}

func (o *GetCollegesIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{id}][%d] getCollegesIdNotFound %s", 404, payload)
}

func (o *GetCollegesIDNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCollegesIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCollegesIDInternalServerError creates a GetCollegesIDInternalServerError with default headers values
func NewGetCollegesIDInternalServerError() *GetCollegesIDInternalServerError {
	return &GetCollegesIDInternalServerError{}
}

// GetCollegesIDInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type GetCollegesIDInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get colleges Id internal server error response has a 2xx status code
func (o *GetCollegesIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get colleges Id internal server error response has a 3xx status code
func (o *GetCollegesIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges Id internal server error response has a 4xx status code
func (o *GetCollegesIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get colleges Id internal server error response has a 5xx status code
func (o *GetCollegesIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get colleges Id internal server error response a status code equal to that given
func (o *GetCollegesIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get colleges Id internal server error response
func (o *GetCollegesIDInternalServerError) Code() int {
	return 500
}

func (o *GetCollegesIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{id}][%d] getCollegesIdInternalServerError %s", 500, payload)
}

func (o *GetCollegesIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{id}][%d] getCollegesIdInternalServerError %s", 500, payload)
}

func (o *GetCollegesIDInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCollegesIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
