// Code generated by go-swagger; DO NOT EDIT.

package colleges

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetCollegesIDParams creates a new GetCollegesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCollegesIDParams() *GetCollegesIDParams {
	return NewGetCollegesIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetCollegesIDParamsWithTimeout creates a new GetCollegesIDParams object
// with the ability to set a timeout on a request.
func NewGetCollegesIDParamsWithTimeout(timeout time.Duration) *GetCollegesIDParams {
	return &GetCollegesIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetCollegesIDParamsWithContext creates a new GetCollegesIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesIDParams].
func NewGetCollegesIDParamsWithContext(ctx context.Context) *GetCollegesIDParams {
	return &GetCollegesIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetCollegesIDParamsWithHTTPClient creates a new GetCollegesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCollegesIDParamsWithHTTPClient(client *http.Client) *GetCollegesIDParams {
	return &GetCollegesIDParams{
		HTTPClient: client,
	}
}

/*
GetCollegesIDParams contains all the parameters to send to the API endpoint

	for the get colleges ID operation.

	Typically these are written to a http.Request.
*/
type GetCollegesIDParams struct {

	// ID.
	//
	// College ID
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get colleges ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollegesIDParams) WithDefaults() *GetCollegesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get colleges ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollegesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get colleges ID params.
func (o *GetCollegesIDParams) WithTimeout(timeout time.Duration) *GetCollegesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get colleges ID params.
func (o *GetCollegesIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get colleges ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesIDParams].
func (o *GetCollegesIDParams) WithContext(ctx context.Context) *GetCollegesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get colleges ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesIDParams].
func (o *GetCollegesIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get colleges ID params.
func (o *GetCollegesIDParams) WithHTTPClient(client *http.Client) *GetCollegesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get colleges ID params.
func (o *GetCollegesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get colleges ID params.
func (o *GetCollegesIDParams) WithID(id int64) *GetCollegesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get colleges ID params.
func (o *GetCollegesIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetCollegesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
