// Code generated by go-swagger; DO NOT EDIT.

package colleges

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCollegesParams creates a new GetCollegesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCollegesParams() *GetCollegesParams {
	return NewGetCollegesParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetCollegesParamsWithTimeout creates a new GetCollegesParams object
// with the ability to set a timeout on a request.
func NewGetCollegesParamsWithTimeout(timeout time.Duration) *GetCollegesParams {
	return &GetCollegesParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetCollegesParamsWithContext creates a new GetCollegesParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesParams].
func NewGetCollegesParamsWithContext(ctx context.Context) *GetCollegesParams {
	return &GetCollegesParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetCollegesParamsWithHTTPClient creates a new GetCollegesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCollegesParamsWithHTTPClient(client *http.Client) *GetCollegesParams {
	return &GetCollegesParams{
		HTTPClient: client,
	}
}

/*
GetCollegesParams contains all the parameters to send to the API endpoint

	for the get colleges operation.

	Typically these are written to a http.Request.
*/
type GetCollegesParams struct {

	// Name.
	//
	// College name
	Name *string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get colleges params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollegesParams) WithDefaults() *GetCollegesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get colleges params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollegesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get colleges params.
func (o *GetCollegesParams) WithTimeout(timeout time.Duration) *GetCollegesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get colleges params.
func (o *GetCollegesParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get colleges params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesParams].
func (o *GetCollegesParams) WithContext(ctx context.Context) *GetCollegesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get colleges params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetCollegesParams].
func (o *GetCollegesParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get colleges params.
func (o *GetCollegesParams) WithHTTPClient(client *http.Client) *GetCollegesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get colleges params.
func (o *GetCollegesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get colleges params.
func (o *GetCollegesParams) WithName(name *string) *GetCollegesParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get colleges params.
func (o *GetCollegesParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetCollegesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
