// Code generated by go-swagger; DO NOT EDIT.

package colleges

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetCollegesIDSchedulesLastReader is a Reader for the GetCollegesIDSchedulesLast structure.
type GetCollegesIDSchedulesLastReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCollegesIDSchedulesLastReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCollegesIDSchedulesLastOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCollegesIDSchedulesLastBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCollegesIDSchedulesLastNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCollegesIDSchedulesLastInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /colleges/{id}/schedules/last] GetCollegesIDSchedulesLast", response, response.Code())
	}
}

// NewGetCollegesIDSchedulesLastOK creates a GetCollegesIDSchedulesLastOK with default headers values
func NewGetCollegesIDSchedulesLastOK() *GetCollegesIDSchedulesLastOK {
	return &GetCollegesIDSchedulesLastOK{}
}

// GetCollegesIDSchedulesLastOK describes a response with status code 200, with default header values.
//
// OK
type GetCollegesIDSchedulesLastOK struct {
	Payload *models.DtoDateResponse
}

// IsSuccess returns true when this get colleges Id schedules last o k response has a 2xx status code
func (o *GetCollegesIDSchedulesLastOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get colleges Id schedules last o k response has a 3xx status code
func (o *GetCollegesIDSchedulesLastOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges Id schedules last o k response has a 4xx status code
func (o *GetCollegesIDSchedulesLastOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get colleges Id schedules last o k response has a 5xx status code
func (o *GetCollegesIDSchedulesLastOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get colleges Id schedules last o k response a status code equal to that given
func (o *GetCollegesIDSchedulesLastOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get colleges Id schedules last o k response
func (o *GetCollegesIDSchedulesLastOK) Code() int {
	return 200
}

func (o *GetCollegesIDSchedulesLastOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{id}/schedules/last][%d] getCollegesIdSchedulesLastOK %s", 200, payload)
}

func (o *GetCollegesIDSchedulesLastOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{id}/schedules/last][%d] getCollegesIdSchedulesLastOK %s", 200, payload)
}

func (o *GetCollegesIDSchedulesLastOK) GetPayload() *models.DtoDateResponse {
	return o.Payload
}

func (o *GetCollegesIDSchedulesLastOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoDateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCollegesIDSchedulesLastBadRequest creates a GetCollegesIDSchedulesLastBadRequest with default headers values
func NewGetCollegesIDSchedulesLastBadRequest() *GetCollegesIDSchedulesLastBadRequest {
	return &GetCollegesIDSchedulesLastBadRequest{}
}

// GetCollegesIDSchedulesLastBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type GetCollegesIDSchedulesLastBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get colleges Id schedules last bad request response has a 2xx status code
func (o *GetCollegesIDSchedulesLastBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get colleges Id schedules last bad request response has a 3xx status code
func (o *GetCollegesIDSchedulesLastBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges Id schedules last bad request response has a 4xx status code
func (o *GetCollegesIDSchedulesLastBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get colleges Id schedules last bad request response has a 5xx status code
func (o *GetCollegesIDSchedulesLastBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get colleges Id schedules last bad request response a status code equal to that given
func (o *GetCollegesIDSchedulesLastBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get colleges Id schedules last bad request response
func (o *GetCollegesIDSchedulesLastBadRequest) Code() int {
	return 400
}

func (o *GetCollegesIDSchedulesLastBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{id}/schedules/last][%d] getCollegesIdSchedulesLastBadRequest %s", 400, payload)
}

func (o *GetCollegesIDSchedulesLastBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{id}/schedules/last][%d] getCollegesIdSchedulesLastBadRequest %s", 400, payload)
}

func (o *GetCollegesIDSchedulesLastBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCollegesIDSchedulesLastBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCollegesIDSchedulesLastNotFound creates a GetCollegesIDSchedulesLastNotFound with default headers values
func NewGetCollegesIDSchedulesLastNotFound() *GetCollegesIDSchedulesLastNotFound {
	return &GetCollegesIDSchedulesLastNotFound{}
}

// GetCollegesIDSchedulesLastNotFound describes a response with status code 404, with default header values.
//
// Not Found
type GetCollegesIDSchedulesLastNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get colleges Id schedules last not found response has a 2xx status code
func (o *GetCollegesIDSchedulesLastNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get colleges Id schedules last not found response has a 3xx status code
func (o *GetCollegesIDSchedulesLastNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges Id schedules last not found response has a 4xx status code
func (o *GetCollegesIDSchedulesLastNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get colleges Id schedules last not found response has a 5xx status code
func (o *GetCollegesIDSchedulesLastNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get colleges Id schedules last not found response a status code equal to that given
func (o *GetCollegesIDSchedulesLastNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get colleges Id schedules last not found response
func (o *GetCollegesIDSchedulesLastNotFound) Code() int {
	return 404
}

func (o *GetCollegesIDSchedulesLastNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{id}/schedules/last][%d] getCollegesIdSchedulesLastNotFound %s", 404, payload)
}

func (o *GetCollegesIDSchedulesLastNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{id}/schedules/last][%d] getCollegesIdSchedulesLastNotFound %s", 404, payload)
}

func (o *GetCollegesIDSchedulesLastNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCollegesIDSchedulesLastNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCollegesIDSchedulesLastInternalServerError creates a GetCollegesIDSchedulesLastInternalServerError with default headers values
func NewGetCollegesIDSchedulesLastInternalServerError() *GetCollegesIDSchedulesLastInternalServerError {
	return &GetCollegesIDSchedulesLastInternalServerError{}
}

// GetCollegesIDSchedulesLastInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type GetCollegesIDSchedulesLastInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this get colleges Id schedules last internal server error response has a 2xx status code
func (o *GetCollegesIDSchedulesLastInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get colleges Id schedules last internal server error response has a 3xx status code
func (o *GetCollegesIDSchedulesLastInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get colleges Id schedules last internal server error response has a 4xx status code
func (o *GetCollegesIDSchedulesLastInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get colleges Id schedules last internal server error response has a 5xx status code
func (o *GetCollegesIDSchedulesLastInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get colleges Id schedules last internal server error response a status code equal to that given
func (o *GetCollegesIDSchedulesLastInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get colleges Id schedules last internal server error response
func (o *GetCollegesIDSchedulesLastInternalServerError) Code() int {
	return 500
}

func (o *GetCollegesIDSchedulesLastInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{id}/schedules/last][%d] getCollegesIdSchedulesLastInternalServerError %s", 500, payload)
}

func (o *GetCollegesIDSchedulesLastInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /colleges/{id}/schedules/last][%d] getCollegesIdSchedulesLastInternalServerError %s", 500, payload)
}

func (o *GetCollegesIDSchedulesLastInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *GetCollegesIDSchedulesLastInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
