// Code generated by go-swagger; DO NOT EDIT.

package admin

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new admin API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new admin API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new admin API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

// Client for admin API.
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// DeleteAdminParserID delete a parser.
	DeleteAdminParserID(params *DeleteAdminParserIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteAdminParserIDNoContent, error)

	// DeleteAdminParserIDContext delete a parser.
	DeleteAdminParserIDContext(ctx context.Context, params *DeleteAdminParserIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteAdminParserIDNoContent, error)

	// PostAdminParser create a new parser.
	PostAdminParser(params *PostAdminParserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostAdminParserCreated, error)

	// PostAdminParserContext create a new parser.
	PostAdminParserContext(ctx context.Context, params *PostAdminParserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostAdminParserCreated, error)

	SetTransport(transport runtime.ContextualTransport)
}

// DeleteAdminParserID deletes a parser.
//
// delete a parser by ID.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.DeleteAdminParserIDContext] instead.
func (a *Client) DeleteAdminParserID(params *DeleteAdminParserIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteAdminParserIDNoContent, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteAdminParserIDContext(ctx, params, authInfo, opts...)
}

// DeleteAdminParserIDContext deletes a parser.
//
// delete a parser by ID.
//
// Do not use the deprecated [DeleteAdminParserIDParams.Context] with this method: it would be ignored.
func (a *Client) DeleteAdminParserIDContext(ctx context.Context, params *DeleteAdminParserIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteAdminParserIDNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteAdminParserIDParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "DeleteAdminParserID",
		Method:             "DELETE",
		PathPattern:        "/admin/parser/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteAdminParserIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteAdminParserIDNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteAdminParserID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// PostAdminParser creates a new parser.
//
// create a new parser.
//
// This method does not support injected context.
// However, timeout and opentracing contexts are honored whenever enabled.
//
// If you need to pass a specific context, use [Client.PostAdminParserContext] instead.
func (a *Client) PostAdminParser(params *PostAdminParserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostAdminParserCreated, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostAdminParserContext(ctx, params, authInfo, opts...)
}

// PostAdminParserContext creates a new parser.
//
// create a new parser.
//
// Do not use the deprecated [PostAdminParserParams.Context] with this method: it would be ignored.
func (a *Client) PostAdminParserContext(ctx context.Context, params *PostAdminParserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostAdminParserCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAdminParserParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostAdminParser",
		Method:             "POST",
		PathPattern:        "/admin/parser",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAdminParserReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAdminParserCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAdminParser: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [AdminParams].
	ctx context.Context
}
