// Code generated by go-swagger; DO NOT EDIT.

package admin

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAdminParserIDReader is a Reader for the DeleteAdminParserID structure.
type DeleteAdminParserIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAdminParserIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAdminParserIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAdminParserIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteAdminParserIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAdminParserIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAdminParserIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /admin/parser/{id}] DeleteAdminParserID", response, response.Code())
	}
}

// NewDeleteAdminParserIDNoContent creates a DeleteAdminParserIDNoContent with default headers values
func NewDeleteAdminParserIDNoContent() *DeleteAdminParserIDNoContent {
	return &DeleteAdminParserIDNoContent{}
}

// DeleteAdminParserIDNoContent describes a response with status code 204, with default header values.
//
// No Content
type DeleteAdminParserIDNoContent struct {
}

// IsSuccess returns true when this delete admin parser Id no content response has a 2xx status code
func (o *DeleteAdminParserIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete admin parser Id no content response has a 3xx status code
func (o *DeleteAdminParserIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete admin parser Id no content response has a 4xx status code
func (o *DeleteAdminParserIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete admin parser Id no content response has a 5xx status code
func (o *DeleteAdminParserIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete admin parser Id no content response a status code equal to that given
func (o *DeleteAdminParserIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete admin parser Id no content response
func (o *DeleteAdminParserIDNoContent) Code() int {
	return 204
}

func (o *DeleteAdminParserIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /admin/parser/{id}][%d] deleteAdminParserIdNoContent", 204)
}

func (o *DeleteAdminParserIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /admin/parser/{id}][%d] deleteAdminParserIdNoContent", 204)
}

func (o *DeleteAdminParserIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAdminParserIDBadRequest creates a DeleteAdminParserIDBadRequest with default headers values
func NewDeleteAdminParserIDBadRequest() *DeleteAdminParserIDBadRequest {
	return &DeleteAdminParserIDBadRequest{}
}

// DeleteAdminParserIDBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type DeleteAdminParserIDBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this delete admin parser Id bad request response has a 2xx status code
func (o *DeleteAdminParserIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete admin parser Id bad request response has a 3xx status code
func (o *DeleteAdminParserIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete admin parser Id bad request response has a 4xx status code
func (o *DeleteAdminParserIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete admin parser Id bad request response has a 5xx status code
func (o *DeleteAdminParserIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete admin parser Id bad request response a status code equal to that given
func (o *DeleteAdminParserIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete admin parser Id bad request response
func (o *DeleteAdminParserIDBadRequest) Code() int {
	return 400
}

func (o *DeleteAdminParserIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /admin/parser/{id}][%d] deleteAdminParserIdBadRequest %s", 400, payload)
}

func (o *DeleteAdminParserIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /admin/parser/{id}][%d] deleteAdminParserIdBadRequest %s", 400, payload)
}

func (o *DeleteAdminParserIDBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *DeleteAdminParserIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAdminParserIDUnauthorized creates a DeleteAdminParserIDUnauthorized with default headers values
func NewDeleteAdminParserIDUnauthorized() *DeleteAdminParserIDUnauthorized {
	return &DeleteAdminParserIDUnauthorized{}
}

// DeleteAdminParserIDUnauthorized describes a response with status code 401, with default header values.
//
// Unauthorized
type DeleteAdminParserIDUnauthorized struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this delete admin parser Id unauthorized response has a 2xx status code
func (o *DeleteAdminParserIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete admin parser Id unauthorized response has a 3xx status code
func (o *DeleteAdminParserIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete admin parser Id unauthorized response has a 4xx status code
func (o *DeleteAdminParserIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete admin parser Id unauthorized response has a 5xx status code
func (o *DeleteAdminParserIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete admin parser Id unauthorized response a status code equal to that given
func (o *DeleteAdminParserIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete admin parser Id unauthorized response
func (o *DeleteAdminParserIDUnauthorized) Code() int {
	return 401
}

func (o *DeleteAdminParserIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /admin/parser/{id}][%d] deleteAdminParserIdUnauthorized %s", 401, payload)
}

func (o *DeleteAdminParserIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /admin/parser/{id}][%d] deleteAdminParserIdUnauthorized %s", 401, payload)
}

func (o *DeleteAdminParserIDUnauthorized) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *DeleteAdminParserIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAdminParserIDNotFound creates a DeleteAdminParserIDNotFound with default headers values
func NewDeleteAdminParserIDNotFound() *DeleteAdminParserIDNotFound {
	return &DeleteAdminParserIDNotFound{}
}

// DeleteAdminParserIDNotFound describes a response with status code 404, with default header values.
//
// Not Found
type DeleteAdminParserIDNotFound struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this delete admin parser Id not found response has a 2xx status code
func (o *DeleteAdminParserIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete admin parser Id not found response has a 3xx status code
func (o *DeleteAdminParserIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete admin parser Id not found response has a 4xx status code
func (o *DeleteAdminParserIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete admin parser Id not found response has a 5xx status code
func (o *DeleteAdminParserIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete admin parser Id not found response a status code equal to that given
func (o *DeleteAdminParserIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete admin parser Id not found response
func (o *DeleteAdminParserIDNotFound) Code() int {
	return 404
}

func (o *DeleteAdminParserIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /admin/parser/{id}][%d] deleteAdminParserIdNotFound %s", 404, payload)
}

func (o *DeleteAdminParserIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /admin/parser/{id}][%d] deleteAdminParserIdNotFound %s", 404, payload)
}

func (o *DeleteAdminParserIDNotFound) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *DeleteAdminParserIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAdminParserIDInternalServerError creates a DeleteAdminParserIDInternalServerError with default headers values
func NewDeleteAdminParserIDInternalServerError() *DeleteAdminParserIDInternalServerError {
	return &DeleteAdminParserIDInternalServerError{}
}

// DeleteAdminParserIDInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type DeleteAdminParserIDInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this delete admin parser Id internal server error response has a 2xx status code
func (o *DeleteAdminParserIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete admin parser Id internal server error response has a 3xx status code
func (o *DeleteAdminParserIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete admin parser Id internal server error response has a 4xx status code
func (o *DeleteAdminParserIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete admin parser Id internal server error response has a 5xx status code
func (o *DeleteAdminParserIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete admin parser Id internal server error response a status code equal to that given
func (o *DeleteAdminParserIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete admin parser Id internal server error response
func (o *DeleteAdminParserIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteAdminParserIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /admin/parser/{id}][%d] deleteAdminParserIdInternalServerError %s", 500, payload)
}

func (o *DeleteAdminParserIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /admin/parser/{id}][%d] deleteAdminParserIdInternalServerError %s", 500, payload)
}

func (o *DeleteAdminParserIDInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *DeleteAdminParserIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
