// Code generated by go-swagger; DO NOT EDIT.

package admin

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewDeleteAdminParserIDParams creates a new DeleteAdminParserIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAdminParserIDParams() *DeleteAdminParserIDParams {
	return NewDeleteAdminParserIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewDeleteAdminParserIDParamsWithTimeout creates a new DeleteAdminParserIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAdminParserIDParamsWithTimeout(timeout time.Duration) *DeleteAdminParserIDParams {
	return &DeleteAdminParserIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDeleteAdminParserIDParamsWithContext creates a new DeleteAdminParserIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteAdminParserIDParams].
func NewDeleteAdminParserIDParamsWithContext(ctx context.Context) *DeleteAdminParserIDParams {
	return &DeleteAdminParserIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDeleteAdminParserIDParamsWithHTTPClient creates a new DeleteAdminParserIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAdminParserIDParamsWithHTTPClient(client *http.Client) *DeleteAdminParserIDParams {
	return &DeleteAdminParserIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAdminParserIDParams contains all the parameters to send to the API endpoint

	for the delete admin parser ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAdminParserIDParams struct {

	// ID.
	//
	// Parser ID
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the delete admin parser ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAdminParserIDParams) WithDefaults() *DeleteAdminParserIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete admin parser ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAdminParserIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete admin parser ID params.
func (o *DeleteAdminParserIDParams) WithTimeout(timeout time.Duration) *DeleteAdminParserIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete admin parser ID params.
func (o *DeleteAdminParserIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the delete admin parser ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteAdminParserIDParams].
func (o *DeleteAdminParserIDParams) WithContext(ctx context.Context) *DeleteAdminParserIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete admin parser ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteAdminParserIDParams].
func (o *DeleteAdminParserIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the delete admin parser ID params.
func (o *DeleteAdminParserIDParams) WithHTTPClient(client *http.Client) *DeleteAdminParserIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete admin parser ID params.
func (o *DeleteAdminParserIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete admin parser ID params.
func (o *DeleteAdminParserIDParams) WithID(id int64) *DeleteAdminParserIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete admin parser ID params.
func (o *DeleteAdminParserIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DeleteAdminParserIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
