// Code generated by go-swagger; DO NOT EDIT.

package admin

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostAdminParserReader is a Reader for the PostAdminParser structure.
type PostAdminParserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAdminParserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewPostAdminParserCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAdminParserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAdminParserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostAdminParserConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAdminParserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /admin/parser] PostAdminParser", response, response.Code())
	}
}

// NewPostAdminParserCreated creates a PostAdminParserCreated with default headers values
func NewPostAdminParserCreated() *PostAdminParserCreated {
	return &PostAdminParserCreated{}
}

// PostAdminParserCreated describes a response with status code 201, with default header values.
//
// Created
type PostAdminParserCreated struct {
	Payload *models.DtoNewParserResponse
}

// IsSuccess returns true when this post admin parser created response has a 2xx status code
func (o *PostAdminParserCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post admin parser created response has a 3xx status code
func (o *PostAdminParserCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post admin parser created response has a 4xx status code
func (o *PostAdminParserCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post admin parser created response has a 5xx status code
func (o *PostAdminParserCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post admin parser created response a status code equal to that given
func (o *PostAdminParserCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post admin parser created response
func (o *PostAdminParserCreated) Code() int {
	return 201
}

func (o *PostAdminParserCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/parser][%d] postAdminParserCreated %s", 201, payload)
}

func (o *PostAdminParserCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/parser][%d] postAdminParserCreated %s", 201, payload)
}

func (o *PostAdminParserCreated) GetPayload() *models.DtoNewParserResponse {
	return o.Payload
}

func (o *PostAdminParserCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoNewParserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAdminParserBadRequest creates a PostAdminParserBadRequest with default headers values
func NewPostAdminParserBadRequest() *PostAdminParserBadRequest {
	return &PostAdminParserBadRequest{}
}

// PostAdminParserBadRequest describes a response with status code 400, with default header values.
//
// Bad Request
type PostAdminParserBadRequest struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post admin parser bad request response has a 2xx status code
func (o *PostAdminParserBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post admin parser bad request response has a 3xx status code
func (o *PostAdminParserBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post admin parser bad request response has a 4xx status code
func (o *PostAdminParserBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post admin parser bad request response has a 5xx status code
func (o *PostAdminParserBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post admin parser bad request response a status code equal to that given
func (o *PostAdminParserBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post admin parser bad request response
func (o *PostAdminParserBadRequest) Code() int {
	return 400
}

func (o *PostAdminParserBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/parser][%d] postAdminParserBadRequest %s", 400, payload)
}

func (o *PostAdminParserBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/parser][%d] postAdminParserBadRequest %s", 400, payload)
}

func (o *PostAdminParserBadRequest) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostAdminParserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAdminParserUnauthorized creates a PostAdminParserUnauthorized with default headers values
func NewPostAdminParserUnauthorized() *PostAdminParserUnauthorized {
	return &PostAdminParserUnauthorized{}
}

// PostAdminParserUnauthorized describes a response with status code 401, with default header values.
//
// Unauthorized
type PostAdminParserUnauthorized struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post admin parser unauthorized response has a 2xx status code
func (o *PostAdminParserUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post admin parser unauthorized response has a 3xx status code
func (o *PostAdminParserUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post admin parser unauthorized response has a 4xx status code
func (o *PostAdminParserUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post admin parser unauthorized response has a 5xx status code
func (o *PostAdminParserUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post admin parser unauthorized response a status code equal to that given
func (o *PostAdminParserUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post admin parser unauthorized response
func (o *PostAdminParserUnauthorized) Code() int {
	return 401
}

func (o *PostAdminParserUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/parser][%d] postAdminParserUnauthorized %s", 401, payload)
}

func (o *PostAdminParserUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/parser][%d] postAdminParserUnauthorized %s", 401, payload)
}

func (o *PostAdminParserUnauthorized) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostAdminParserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAdminParserConflict creates a PostAdminParserConflict with default headers values
func NewPostAdminParserConflict() *PostAdminParserConflict {
	return &PostAdminParserConflict{}
}

// PostAdminParserConflict describes a response with status code 409, with default header values.
//
// Conflict
type PostAdminParserConflict struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post admin parser conflict response has a 2xx status code
func (o *PostAdminParserConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post admin parser conflict response has a 3xx status code
func (o *PostAdminParserConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post admin parser conflict response has a 4xx status code
func (o *PostAdminParserConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this post admin parser conflict response has a 5xx status code
func (o *PostAdminParserConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this post admin parser conflict response a status code equal to that given
func (o *PostAdminParserConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the post admin parser conflict response
func (o *PostAdminParserConflict) Code() int {
	return 409
}

func (o *PostAdminParserConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/parser][%d] postAdminParserConflict %s", 409, payload)
}

func (o *PostAdminParserConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/parser][%d] postAdminParserConflict %s", 409, payload)
}

func (o *PostAdminParserConflict) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostAdminParserConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAdminParserInternalServerError creates a PostAdminParserInternalServerError with default headers values
func NewPostAdminParserInternalServerError() *PostAdminParserInternalServerError {
	return &PostAdminParserInternalServerError{}
}

// PostAdminParserInternalServerError describes a response with status code 500, with default header values.
//
// Internal Server Error
type PostAdminParserInternalServerError struct {
	Payload *models.DtoErrorResponse
}

// IsSuccess returns true when this post admin parser internal server error response has a 2xx status code
func (o *PostAdminParserInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post admin parser internal server error response has a 3xx status code
func (o *PostAdminParserInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post admin parser internal server error response has a 4xx status code
func (o *PostAdminParserInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post admin parser internal server error response has a 5xx status code
func (o *PostAdminParserInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post admin parser internal server error response a status code equal to that given
func (o *PostAdminParserInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post admin parser internal server error response
func (o *PostAdminParserInternalServerError) Code() int {
	return 500
}

func (o *PostAdminParserInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/parser][%d] postAdminParserInternalServerError %s", 500, payload)
}

func (o *PostAdminParserInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/parser][%d] postAdminParserInternalServerError %s", 500, payload)
}

func (o *PostAdminParserInternalServerError) GetPayload() *models.DtoErrorResponse {
	return o.Payload
}

func (o *PostAdminParserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
