// Code generated by go-swagger; DO NOT EDIT.

package admin

import (
	"context"
	"net/http"
	"time"

	"github.com/ThisIsHyum/osago/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAdminParserParams creates a new PostAdminParserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAdminParserParams() *PostAdminParserParams {
	return NewPostAdminParserParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostAdminParserParamsWithTimeout creates a new PostAdminParserParams object
// with the ability to set a timeout on a request.
func NewPostAdminParserParamsWithTimeout(timeout time.Duration) *PostAdminParserParams {
	return &PostAdminParserParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostAdminParserParamsWithContext creates a new PostAdminParserParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAdminParserParams].
func NewPostAdminParserParamsWithContext(ctx context.Context) *PostAdminParserParams {
	return &PostAdminParserParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostAdminParserParamsWithHTTPClient creates a new PostAdminParserParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAdminParserParamsWithHTTPClient(client *http.Client) *PostAdminParserParams {
	return &PostAdminParserParams{
		HTTPClient: client,
	}
}

/*
PostAdminParserParams contains all the parameters to send to the API endpoint

	for the post admin parser operation.

	Typically these are written to a http.Request.
*/
type PostAdminParserParams struct {

	// NewParserRequest.
	//
	// new parser request
	NewParserRequest *models.DtoNewParserRequest

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post admin parser params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAdminParserParams) WithDefaults() *PostAdminParserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post admin parser params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAdminParserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post admin parser params.
func (o *PostAdminParserParams) WithTimeout(timeout time.Duration) *PostAdminParserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post admin parser params.
func (o *PostAdminParserParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post admin parser params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAdminParserParams].
func (o *PostAdminParserParams) WithContext(ctx context.Context) *PostAdminParserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post admin parser params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAdminParserParams].
func (o *PostAdminParserParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post admin parser params.
func (o *PostAdminParserParams) WithHTTPClient(client *http.Client) *PostAdminParserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post admin parser params.
func (o *PostAdminParserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNewParserRequest adds the newParserRequest to the post admin parser params.
func (o *PostAdminParserParams) WithNewParserRequest(newParserRequest *models.DtoNewParserRequest) *PostAdminParserParams {
	o.SetNewParserRequest(newParserRequest)
	return o
}

// SetNewParserRequest adds the newParserRequest to the post admin parser params.
func (o *PostAdminParserParams) SetNewParserRequest(newParserRequest *models.DtoNewParserRequest) {
	o.NewParserRequest = newParserRequest
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostAdminParserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.NewParserRequest != nil {
		if err := r.SetBodyParam(o.NewParserRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
