// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// DtoScheduleReplaceResponse dto schedule replace response
//
// swagger:model dto.ScheduleReplaceResponse
type DtoScheduleReplaceResponse struct {

	// cabinet
	Cabinet string `json:"cabinet,omitempty"`

	// teacher
	Teacher string `json:"teacher,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this dto schedule replace response
func (m *DtoScheduleReplaceResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto schedule replace response based on context it is used
func (m *DtoScheduleReplaceResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoScheduleReplaceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoScheduleReplaceResponse) UnmarshalBinary(b []byte) error {
	var res DtoScheduleReplaceResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
