// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// DtoCollegeResponse dto college response
//
// swagger:model dto.CollegeResponse
type DtoCollegeResponse struct {

	// campuses
	Campuses []*DtoCampusResponse `json:"campuses"`

	// college Id
	CollegeID int64 `json:"collegeId,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this dto college response
func (m *DtoCollegeResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCampuses(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoCollegeResponse) validateCampuses(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Campuses) { // not required
		return nil
	}

	for i := 0; i < len(m.Campuses); i++ {
		if typeutils.IsZero(m.Campuses[i]) { // not required
			continue
		}

		if m.Campuses[i] != nil {
			if err := m.Campuses[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("campuses" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("campuses" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this dto college response based on the context it is used
func (m *DtoCollegeResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCampuses(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoCollegeResponse) contextValidateCampuses(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Campuses); i++ {

		if m.Campuses[i] != nil {

			if typeutils.IsZero(m.Campuses[i]) { // not required
				return nil
			}

			if err := m.Campuses[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("campuses" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("campuses" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DtoCollegeResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoCollegeResponse) UnmarshalBinary(b []byte) error {
	var res DtoCollegeResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
