// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// DtoErrorResponse dto error response
//
// swagger:model dto.ErrorResponse
type DtoErrorResponse struct {

	// error
	Error string `json:"error,omitempty"`

	// status code
	StatusCode int64 `json:"statusCode,omitempty"`
}

// Validate validates this dto error response
func (m *DtoErrorResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto error response based on context it is used
func (m *DtoErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoErrorResponse) UnmarshalBinary(b []byte) error {
	var res DtoErrorResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
