// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// DtoUpdateGroupsRequest dto update groups request
//
// swagger:model dto.UpdateGroupsRequest
type DtoUpdateGroupsRequest struct {

	// campus Id
	CampusID int64 `json:"campusId,omitempty"`

	// student group names
	StudentGroupNames []string `json:"studentGroupNames"`
}

// Validate validates this dto update groups request
func (m *DtoUpdateGroupsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto update groups request based on context it is used
func (m *DtoUpdateGroupsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoUpdateGroupsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoUpdateGroupsRequest) UnmarshalBinary(b []byte) error {
	var res DtoUpdateGroupsRequest
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
