// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// DtoLesson dto lesson
//
// swagger:model dto.Lesson
type DtoLesson struct {

	// cabinet
	Cabinet string `json:"cabinet,omitempty"`

	// date
	Date string `json:"date,omitempty"`

	// lesson Id
	LessonID int64 `json:"lessonId,omitempty"`

	// order
	Order int64 `json:"order,omitempty"`

	// student group ID
	StudentGroupID int64 `json:"studentGroupID,omitempty"`

	// teacher
	Teacher string `json:"teacher,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this dto lesson
func (m *DtoLesson) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto lesson based on context it is used
func (m *DtoLesson) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoLesson) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoLesson) UnmarshalBinary(b []byte) error {
	var res DtoLesson
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
