// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// DtoDateResponse dto date response
//
// swagger:model dto.DateResponse
type DtoDateResponse struct {

	// date
	Date string `json:"date,omitempty"`
}

// Validate validates this dto date response
func (m *DtoDateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto date response based on context it is used
func (m *DtoDateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoDateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoDateResponse) UnmarshalBinary(b []byte) error {
	var res DtoDateResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
