// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// DtoScheduleLessonResponse dto schedule lesson response
//
// swagger:model dto.ScheduleLessonResponse
type DtoScheduleLessonResponse struct {

	// cabinet
	Cabinet string `json:"cabinet,omitempty"`

	// end time
	EndTime string `json:"endTime,omitempty"`

	// order
	Order int64 `json:"order,omitempty"`

	// start time
	StartTime string `json:"startTime,omitempty"`

	// teacher
	Teacher string `json:"teacher,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this dto schedule lesson response
func (m *DtoScheduleLessonResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto schedule lesson response based on context it is used
func (m *DtoScheduleLessonResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoScheduleLessonResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoScheduleLessonResponse) UnmarshalBinary(b []byte) error {
	var res DtoScheduleLessonResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
