// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// DtoReplace dto replace
//
// swagger:model dto.Replace
type DtoReplace struct {

	// cabinet
	Cabinet *string `json:"cabinet,omitempty"`

	// date
	Date string `json:"date,omitempty"`

	// order
	Order int64 `json:"order,omitempty"`

	// replace Id
	ReplaceID int64 `json:"replaceId,omitempty"`

	// student group ID
	StudentGroupID int64 `json:"studentGroupID,omitempty"`

	// teacher
	Teacher *string `json:"teacher,omitempty"`

	// title
	Title *string `json:"title,omitempty"`
}

// Validate validates this dto replace
func (m *DtoReplace) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto replace based on context it is used
func (m *DtoReplace) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoReplace) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoReplace) UnmarshalBinary(b []byte) error {
	var res DtoReplace
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
