// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// DtoDate dto date
//
// swagger:model dto.Date
type DtoDate struct {

	// time time
	TimeTime string `json:"time.Time,omitempty"`
}

// Validate validates this dto date
func (m *DtoDate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto date based on context it is used
func (m *DtoDate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoDate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoDate) UnmarshalBinary(b []byte) error {
	var res DtoDate
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
