// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// DtoNewParserResponse dto new parser response
//
// swagger:model dto.NewParserResponse
type DtoNewParserResponse struct {

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this dto new parser response
func (m *DtoNewParserResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto new parser response based on context it is used
func (m *DtoNewParserResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoNewParserResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoNewParserResponse) UnmarshalBinary(b []byte) error {
	var res DtoNewParserResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
