// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// DtoNewParserRequest dto new parser request
//
// swagger:model dto.NewParserRequest
type DtoNewParserRequest struct {

	// campus names
	CampusNames []string `json:"campusNames"`

	// college name
	CollegeName string `json:"collegeName,omitempty"`
}

// Validate validates this dto new parser request
func (m *DtoNewParserRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto new parser request based on context it is used
func (m *DtoNewParserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoNewParserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoNewParserRequest) UnmarshalBinary(b []byte) error {
	var res DtoNewParserRequest
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
