// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// DtoScheduleResponse dto schedule response
//
// swagger:model dto.ScheduleResponse
type DtoScheduleResponse struct {

	// date
	Date string `json:"date,omitempty"`

	// group Id
	GroupID int64 `json:"groupId,omitempty"`

	// lessons
	Lessons []*DtoScheduleLessonResponse `json:"lessons"`
}

// Validate validates this dto schedule response
func (m *DtoScheduleResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLessons(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoScheduleResponse) validateLessons(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Lessons) { // not required
		return nil
	}

	for i := 0; i < len(m.Lessons); i++ {
		if typeutils.IsZero(m.Lessons[i]) { // not required
			continue
		}

		if m.Lessons[i] != nil {
			if err := m.Lessons[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("lessons" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("lessons" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this dto schedule response based on the context it is used
func (m *DtoScheduleResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLessons(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoScheduleResponse) contextValidateLessons(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Lessons); i++ {

		if m.Lessons[i] != nil {

			if typeutils.IsZero(m.Lessons[i]) { // not required
				return nil
			}

			if err := m.Lessons[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("lessons" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("lessons" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DtoScheduleResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoScheduleResponse) UnmarshalBinary(b []byte) error {
	var res DtoScheduleResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
