// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// DtoScheduleLessonResponse dto schedule lesson response
//
// swagger:model dto.ScheduleLessonResponse
type DtoScheduleLessonResponse struct {

	// cabinet
	Cabinet string `json:"cabinet,omitempty"`

	// end time
	EndTime string `json:"endTime,omitempty"`

	// order
	Order int64 `json:"order,omitempty"`

	// replace
	Replace *DtoScheduleReplaceResponse `json:"replace,omitempty"`

	// start time
	StartTime string `json:"startTime,omitempty"`

	// teacher
	Teacher string `json:"teacher,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this dto schedule lesson response
func (m *DtoScheduleLessonResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReplace(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoScheduleLessonResponse) validateReplace(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Replace) { // not required
		return nil
	}

	if m.Replace != nil {
		if err := m.Replace.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("replace")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("replace")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this dto schedule lesson response based on the context it is used
func (m *DtoScheduleLessonResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateReplace(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoScheduleLessonResponse) contextValidateReplace(ctx context.Context, formats strfmt.Registry) error {

	if m.Replace != nil {

		if typeutils.IsZero(m.Replace) { // not required
			return nil
		}

		if err := m.Replace.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("replace")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("replace")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DtoScheduleLessonResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoScheduleLessonResponse) UnmarshalBinary(b []byte) error {
	var res DtoScheduleLessonResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
