// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// DtoGetParserResponse dto get parser response
//
// swagger:model dto.GetParserResponse
type DtoGetParserResponse struct {

	// college Id
	CollegeID int64 `json:"collegeId,omitempty"`
}

// Validate validates this dto get parser response
func (m *DtoGetParserResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto get parser response based on context it is used
func (m *DtoGetParserResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoGetParserResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoGetParserResponse) UnmarshalBinary(b []byte) error {
	var res DtoGetParserResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
