// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// DtoStudentGroupResponse dto student group response
//
// swagger:model dto.StudentGroupResponse
type DtoStudentGroupResponse struct {

	// campus Id
	CampusID int64 `json:"campusId,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// student group Id
	StudentGroupID int64 `json:"studentGroupId,omitempty"`
}

// Validate validates this dto student group response
func (m *DtoStudentGroupResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto student group response based on context it is used
func (m *DtoStudentGroupResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoStudentGroupResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoStudentGroupResponse) UnmarshalBinary(b []byte) error {
	var res DtoStudentGroupResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
