// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// TimeWeekday time weekday
//
// swagger:model time.Weekday
type TimeWeekday int64

// for schema
var timeWeekdayEnum []any

func init() {
	var res []TimeWeekday
	if err := json.Unmarshal([]byte(`[0,1,2,3,4,5,6]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		timeWeekdayEnum = append(timeWeekdayEnum, v)
	}
}

func (m TimeWeekday) validateTimeWeekdayEnum(path, location string, value TimeWeekday) error {
	if err := validate.EnumCase(path, location, value, timeWeekdayEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this time weekday
func (m TimeWeekday) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTimeWeekdayEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this time weekday based on context it is used
func (m TimeWeekday) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
